### ISSUE TITLE
All outstanding PRs were closed during a merge

### ISSUE THREAD

**Issue by mgalgs** [Reviewable/Reviewable#477] opened 2017-05-09 03:31 UTC
I just used the awesome button to merge a PR.  For some reason, though, it also closed *all* outstanding PRs in my repo.  The other PRs weren't merged, they were just closed, so it was easy enough for me to just open them back up.  But still weird and a bit disconcerting.

Here they all are with identical timestamps:

![image](https://cloud.githubusercontent.com/assets/152014/25834485/1132af54-342d-11e7-9e90-98eb4d1028e0.png)

I didn't notice anything out of the ordinary when I had the bunny merge the PR.

**Comment by pkaminski** [comment] 2017-05-09 04:20
Wow, that's rather drastic!  However, looking at my code it's pretty much impossible for Reviewable to be the cause -- closing a PR requires a `PATCH` API call against the PR with `state: "closed"` that 1) Reviewable never issues when merging and 2) when it does in other places it never uses the `state` parameter.

Assuming that Reviewable really did trigger this disaster, though, my best guess is some kind of wild API malfunction on GitHub's side.  Could you please checked the organization's Audit Log (in its settings) to see if the PR update events show up, and if so who's the initiator?  If no other plausible explanation appears, please also loop in support@github.com, since I think we'll need their help (with your permission) to figure this out.

Thanks!

**Comment by pkaminski** [comment] 2017-05-10 21:07
Ping -- I'd really like to get to the bottom of this.

**Comment by mgalgs** [comment] 2017-05-10 21:27
I don't see any PR update events in the audit log...  I'll report the bug to GitHub and will link them back here.

**Comment by mgalgs** [comment] 2017-05-12 16:01
Got a response back from the 'Hub:

> Thanks, Mitchel. I think I see what happened. All those pull requests was closed because their base branch, develop, was deleted (the base branch is the target branch). If a branch is deleted -- pull requests targeted at that branch are auto-closed since it doesn't really make sense to keep them open (there's nothing to merge them into).
>
> According to our logs, the base branch (develop) was deleted by the Reviewable OAuth application on your behalf, at 2017-05-09T03:11:30Z. After that, it was manually re-created by you at 2017-05-09T03:14:41Z. After you re-created the base branch, you were able to re-open the pull requests.
>
> We can't tell you why that deletion happened, since it wasn't triggered by us. I recommend reaching out to the Reviewable folks to confirm that.
>
> Hope this helps. If you need any other information from us -- let me know.

Now I understand what happened.

I have two main "long-lived" branches in my repo: `master` and `develop`.  Most of our PRs are from feature branches to `develop`, but last week I had a hotfix that I pushed straight to `develop` and then did a PR from `develop` to `master`.  So when I clicked "Merge and delete branch" it... obviously... deleted the base branch (`develop`), which then closed all of those other PRs.

So in the end this was really user error.  I should have unchecked the "delete branch" option.  I do think there are some things that could be improved in the Reviewable UI to avoid this kind of mistake.  For example, maybe you could check if the base branch has other PRs open against it, and if it does give a little warning message stating that X number of open PRs against the branch you're about to delete it will be closed.

In any case, the good news is that there isn't a wild API bug anywhere, it was just a user error.

**Comment by mgalgs** [comment] 2017-05-12 16:26
In the meantime, I've made `develop` a protected branch in my repo :)

**Comment by pkaminski** [comment] 2017-05-12 16:53
Ah, that scenario makes sense -- thanks for figuring it out!  I think make the branch protected is the right thing to do, since Reviewable will respect the setting (automatically switching to "& Retain" for that review) and it'll prevent accidents in GitHub (and other apps) as well.  But I agree that having a bit of extra warning in Reviewable would certainly be nice too.  :)

**Closed by pkaminski** 2017-05-12 16:53 UTC
Labels: invalid
