### ISSUE TITLE
truncated comments

### ISSUE THREAD

**Issue by bejito** [Reviewable/Reviewable#588] opened 2018-09-11 09:49 UTC
Most of my comments get truncated as soon as I try to backquote some text.
e.g. writing "hello `world`" results in "hello `"

**Comment by pkaminski** [comment] 2018-09-11 19:20
Duplicate of #558, please follow up there with details.  Obviously this is not happening for the vast majority of users so let's try to figure out what's different about your environment.  Thanks!

**Closed by pkaminski** 2018-09-11 19:20 UTC
Labels: duplicate

**Comment by jellonek** [comment] 2018-10-04 09:05
I had similar issue when i tried to suggest in comment to use:
~~~
```yaml
~~~
in place of:
~~~
```
~~~
In the same time using similar text later in line - works perfectly.
Effect can be visible in https://github.com/Mirantis/virtlet/pull/772#pullrequestreview-160915201

**Comment by jellonek** [comment] 2018-10-05 08:30
The tricky thing is that there is no way to look on source of original comment (btw. it would be nice to have such option, maybe i'll add new one or look if there is already such feature request :P ), only on it's rendered version ;) but i'm almost sure that i've used ` ```yaml ` as a single line comment.

In case of single line comment rendering that as empty block was unnecessary (it was proposal for replacement, and you are right - it was not escaped at all), but I understand that it's hard to guess comment authors intention.

Hmmm... Maybe reviews for .md files should have a separate set of rules? I'll pass information in my team that proposing replacements for things in .md files always should be enclosed in `~~~` or ` ``` `.

**Comment by pkaminski** [comment] 2018-10-05 16:50
I checked in the database and AFAICT you entered literally <code>```yaml</code> as a single line comment -- I just wanted to check with you in case the purported content-munching bug was even earlier in the pipeline than expected.  At this point, I think people just need to be aware that the comment box is Markdown, and the usual Markdown rules apply.

**Comment by jellonek** [comment] 2018-10-05 18:49
Yeah, i'm now aware, but the question is how many users are aware about that ;)
Also it would be nice to have a preview for comment, what e.g. github have. Just nice to have idea.

**Comment by pkaminski** [comment] 2018-10-05 19:38
There's a preview tab just like on GitHub.  Eventually I'd like to do inline style preview for some stuff, but that wouldn't help for code quotes I think.
