### ISSUE TITLE
Having many revisions can make it difficult to review a PR

### ISSUE THREAD

**Issue by EricCousineau-TRI** [Reviewable/Reviewable#591] opened 2018-09-27 01:39 UTC
For the following PR:
https://github.com/RobotLocomotion/drake/pull/9510
https://reviewable.io/reviews/robotlocomotion/drake/9510#-
We pushed quite a few updates to this PR, and got to the point of having `r40`. Without a large monitor (at least on Firefox), I couldn't really view all of the revisions.

Here is a screenshot of an entire window, shrunk down to emphasize the issue:
![image](https://user-images.githubusercontent.com/26719449/46118401-5d755c00-c1d4-11e8-8065-d9f43c061b16.png)

Is there a way to collapse the number of reviews, or at least permit horizontal scrolling on the web page?

**Comment by pkaminski** [comment] 2018-09-27 02:17
Yep, these are known issues:  #220 for the "lots of revisions is hard to deal with" and #514 for the more recent bug of disappearing horizontal scrollbar.  I'm getting close to ready to rebuilding this UI in Vue and moving it to a sidebar, at which point the horizontal scroll bar at least will come back.  I also spent some time thinking about ways to compress or collapse the revisions but never came up with an idea that I would consider acceptable UX (and that would still allow you to see all the revisions when necessary).

Going to close this as duplicate of #514, but if you have ideas on how to do collapsing/compressing please share!

**Closed by pkaminski** 2018-09-27 02:17 UTC
Labels: duplicate
