### ISSUE TITLE
Speed / usability on mobile

### ISSUE THREAD

**Issue by ryan-williams** [Reviewable/Reviewable#139] opened 2015-07-29 05:40 UTC
I did some reviewable reviews on my phone (Nexus 6, Chrome) today for the first time. I was able to do them but it was somewhat painful. Two things otomh:
- text boxes kept losing my cursor and the only way I could get it back was to hit "Preview" then "Write" again.
- page load time and general responsiveness was very slow, e.g. 10s of seconds to jump to the comment that I'd clicked a link to from an email on initial page load. Presumably loading one file at a time and slimming down some of the JS would help a lot here. Almost every tap resulted in a several-seconds delay without any indication that work was being done.

Even with these difficulties, it was cool that it basically worked; I wouldn't have thought that doing code reviews from my phone would be very feasible but now I think that with a little effort it could be made to be a really great experience. Very handy for downtime / AFK time.

**Comment by pkaminski** [comment] 2015-07-29 05:46
Wow, I'm amazed it worked at all, given that I never even tried to load a review page on my phone, or make it work on screens that small!  (I only test the home page and dashboard on mobile, and even then just occasionally.)  Cool!

I'll put this on my to-do list, but it's not a very high priority and I'll probably need to buy a newer phone for testing first (I'm still using a "vintage" Galaxy Nexus circa 2011).

**Comment by ryan-williams** [comment] 2015-07-29 06:04
Sounds good. I'd encourage you to try actually doing a review on mobile; you might be more convinced that it'd be really useful than you think, as I was :)

**Comment by jjcomer** [comment] 2015-08-06 19:17
There are a few people on our team that like to use the site on their phones. It works really well except for the fact that you can't merge the PR (you can't hold the button to arm it (at least on a nexus)).

**Comment by pkaminski** [comment] 2015-08-08 07:31
@jjcomer I tried to fix the merge button on touchscreens, and it should now be working -- at least according to Chrome's device emulator.  Can you confirm?

**Comment by ianbishop** [comment] 2015-08-11 17:28
@pkaminski Just tried this on my Nexus 6, worked perfectly. Cheers

**Comment by puremourning** [comment] 2015-10-29 21:53
+1 to this. I know it sounds *mad* to do code reviews on a mobile device, but I often try and grab a few minutes to review some OSS stuff or make a quick comment when, say on a train or whatever. Moreover, a tablet is actually a really handy device for code reviews - i can do them on my sofa :). 

However, I can totally see how difficult it would be to have a UI as complex as reviewable work reliably on multiple device paradigms, though :)

**Comment by pkaminski** [comment] 2015-10-29 22:53
Honestly, I planned for this from the start, which is why (for example) I avoid hover interactions and make use of drags.  And getting a new phone is on my Christmas shopping list so there's a good chance I'll be motivated to play with this more early next year.  :)  But it's also possible that the overhead for Angular is just too much, and it won't be possible to significantly improve performance until I switch to a new framework, which may happen later next year...

**Comment by andschwa** [comment] 2016-03-23 20:45
Piggy backing on this: I can't get past the sign in with GitHub step in Chrome on my Nexus 6. The authentication window pops up and immediately closes, leaving me not signed in.

I would definitely like mobile access.

**Comment by andschwa** [comment] 2016-03-23 20:55
After explicitly disabling all pop-up blocking, I was able to sign in. For the most part everything worked fine, but modifying text proved a little hairy.

**Comment by pkaminski** [comment] 2016-03-24 06:55
@andschwa I wasn't able to reproduce the sign-in issues in Chrome 49.0.2623.91 on Android 5.1.1, even though I have pop-ups set to "blocked" for all sites in my settings.

I wasn't able to edit drafts at all, had trouble picking from some dropdown menus, and had menus that didn't disappear when they should have.  A bunch of layout was also screwy on my fairly small screen.

Surprisingly, performance was overall decent, even on my 2-year-old Snapdragon 801 chipset.  Still, it will take a lot of work to hunt down all the issues...

**Comment by pkaminski** [comment] 2016-08-22 09:30
I fixed the most egregious issues with touch compatibility: you can now create and edit drafts, and swipe to select diff ranges.  Lots more work left to do (performance not least of all), but at least you should be able to do basic review work on reasonably large and powerful mobile devices.

**Comment by puremourning** [comment] 2016-08-22 10:00
Woooo. Thanks Piotr!

**Comment by pkaminski** [comment] 2018-06-03 07:27
I'm going to guess that between the improvements to mobile CPUs and better performance since the move to Vue models, Reviewable is working well enough on mobile devices to close this issue.

**Closed by pkaminski** 2018-06-03 07:27 UTC
Labels: enhancement, low priority
