### ISSUE TITLE
Click to open a new comment is slow

### ISSUE THREAD

**Issue by thockin** [Reviewable/Reviewable#60] opened 2015-03-05 18:26 UTC
When I click a line to add a new comment I get about 2 seconds of lag before the edit box pops up.

**Comment by pkaminski** [comment] 2015-03-05 21:16
This sounds like a general performance issue (hello Angular digest!) that I keep hearing about but haven't been able to reproduce yet.  I'll need to think of some way to instrument the code further, or go debug it on site if somebody affected is willing and not too far from Mountain View...

**Comment by thockin** [comment] 2015-03-05 22:24
I'm not a heavy user, but I am in Mountain View and would happily let you
shoulder surf as I futz with your demo.

**Comment by pkaminski** [comment] 2015-03-06 07:03
If it's still happening, could you try loading the page with `?debug=digest` and reporting the min/med/max values from the bottom-right corner after using the app for a bit and creating a few comments?  Depending on what that reveals, I may take you up on the shoulder-surfing offer.  Thanks!

**Comment by thockin** [comment] 2015-03-06 07:29
It isn't so bad now, mostly just the animation feels slow, but I swear I
could count 2 seconds earlier today.

digest 13ms 18ms 75ms d

**Comment by pkaminski** [comment] 2015-03-06 07:30
Was it on a different review?  The digest latency will go up as the number of files and revisions rise.

**Comment by thockin** [comment] 2015-03-06 07:38
Could be.  Loading a larger review...

https://reviewable.io/reviews/GoogleCloudPlatform/kubernetes/4055?debug=digest#-Jji06H8uzN_TyPLToDU

yeah, that takes about 3 seconds to open each edit box.

**Comment by pkaminski** [comment] 2015-03-06 07:44
Yeah, that's pushing at Reviewable's current performance limits.  I'll add it as a test case for our next round of performance optimizations.  Thanks.

**Comment by thockin** [comment] 2015-03-06 08:10
heh, that's not such an unusual review for us.

**Comment by danvk** [comment] 2015-03-10 19:00
I'm also noticing this on https://reviewable.io/reviews/hammerlab/cycledash/510, which has ~40 files in the review. Opening a draft comment box takes ~3 seconds. Time to revisit #17?

**Comment by pkaminski** [comment] 2015-03-10 19:14
Do you know if this is a recent regression, by any chance?

**Comment by danvk** [comment] 2015-03-10 19:53
I don't; this review was just sent out today.

**Comment by pkaminski** [comment] 2015-03-11 20:17
Tracking down this problem proved to be very educational (in a late night, swearing at the browser kind of way), but it should be fixed now.  Actions still won't feel instantaneous (or smooth) in large reviews but latency should now be in the quite usable 200-300ms range.  Please let me know if this works (or doesn't!) for you, and if you notice any side-effects (most likely in being unable to select text).  Thanks.

**Closed by pkaminski** 2015-03-11 20:17 UTC
Labels: bug

**Comment by thockin** [comment] 2015-03-12 03:59
I'm seeing (empirically) about 750ms from click to fully visible.  And then
the cursor is not in the box, so I can't even type (is that worthy of
another issue?)

**Comment by pkaminski** [comment] 2015-03-12 04:39
Well, the animation is another 300ms, but even if I turn those on I can't get close to 750ms on the sample review you linked to above.  Are you running without `?debug=digest`, which slows things down a bit?  Can you try to estimate the latency with the animation turned off to get a more accurate number?

I noticed the focusing issue earlier today and I'm looking into it, though it appears to be intermittent.  Probably another race condition somewhere.

**Comment by thockin** [comment] 2015-03-12 04:44
IMO that 300ms just makes everything feel sluggish.  I may be the odd man
out on this - I feel the same way about all of MacOS - it feels slow
because of silly animations.  Just show me what I want to see.

It's a bit better with debug off, but still well beyond a half second -
using the PR I linked above

**Comment by pkaminski** [comment] 2015-03-12 04:50
Grumpy developers is precisely who the animation toggle in the account
settings was made for.  :smile:  Turn it off and everything will become
snappier, if not as pretty.

I can try to squeeze some more performance out of the code, but I'm quickly
reaching the point of diminishing returns.  I may have asked this before,
but what vintage machine are you observing these high latencies on?

On Wed, Mar 11, 2015 at 9:44 PM, Tim Hockin <notifications@github.com>
wrote:

> IMO that 300ms just makes everything feel sluggish. I may be the odd man
> out on this - I feel the same way about all of MacOS - it feels slow
> because of silly animations. Just show me what I want to see.
>
> It's a bit better with debug off, but still well beyond a half second -
> using the PR I linked above
>
> On Wed, Mar 11, 2015 at 9:39 PM, Piotr Kaminski <notifications@github.com>
> wrote:
>
> > Well, the animation is another 300ms, but even if I turn those on I can't
> > get close to 750ms on the sample review you linked to above. Are you
> > running without ?debug=digest, which slows things down a bit? Can you try
> > to estimate the latency with the animation turned off to get a more
> > accurate number?
> >
> > I noticed the focusing issue earlier today and I'm looking into it,
> though
> > it appears to be intermittent. Probably another race condition somewhere.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Reviewable/Reviewable/issues/60#issuecomment-78422864>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/60#issuecomment-78423151>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by thockin** [comment] 2015-03-12 04:55
I'm on a Thinkpad T430s, running Chrome on Ubuntu - not so vintage.

Now that I flipped that toggle (it still looks nice, don't feel bad :) I
would say that the latency is "acceptable" though not amazing.  Thanks for
the followup :)

**Comment by pkaminski** [comment] 2015-03-12 05:24
Yeah, it's probably closer to 500ms on my T440s (Chrome / Windows), so your
experience sounds about right.  I don't think I'll be able to milk much
more out of the current framework, though.  Longer-term, I want to
replatform on something that takes advantage of Object.observe() instead of
Angular's dirty-checking, but that's Q3/Q4 at best since those frameworks
aren't even baked yet.  In the meantime, we're at the mercy of Moore's Law.
 :)


On Wed, Mar 11, 2015 at 9:55 PM, Tim Hockin <notifications@github.com>
wrote:

> I'm on a Thinkpad T430s, running Chrome on Ubuntu - not so vintage.
>
> Now that I flipped that toggle (it still looks nice, don't feel bad :) I
> would say that the latency is "acceptable" though not amazing. Thanks for
> the followup :)
>
> On Wed, Mar 11, 2015 at 9:50 PM, Piotr Kaminski <notifications@github.com>
>
> wrote:
>
> > Grumpy developers is precisely who the animation toggle in the account
> > settings was made for. :smile: Turn it off and everything will become
> > snappier, if not as pretty.
> >
> > I can try to squeeze some more performance out of the code, but I'm
> quickly
> > reaching the point of diminishing returns. I may have asked this before,
> > but what vintage machine are you observing these high latencies on?
> >
> > On Wed, Mar 11, 2015 at 9:44 PM, Tim Hockin <notifications@github.com>
> > wrote:
> >
> >
> > > IMO that 300ms just makes everything feel sluggish. I may be the odd
> man
> > > out on this - I feel the same way about all of MacOS - it feels slow
> > > because of silly animations. Just show me what I want to see.
> > >
> > > It's a bit better with debug off, but still well beyond a half second -
> > > using the PR I linked above
> > >
> > > On Wed, Mar 11, 2015 at 9:39 PM, Piotr Kaminski <
> > notifications@github.com>
> > > wrote:
> > >
> > > > Well, the animation is another 300ms, but even if I turn those on I
> > can't
> > > > get close to 750ms on the sample review you linked to above. Are you
> > > > running without ?debug=digest, which slows things down a bit? Can you
> > try
> > > > to estimate the latency with the animation turned off to get a more
> > > > accurate number?
> > > >
> > > > I noticed the focusing issue earlier today and I'm looking into it,
> > > though
> > > > it appears to be intermittent. Probably another race condition
> > somewhere.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> https://github.com/Reviewable/Reviewable/issues/60#issuecomment-78422864
> > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/Reviewable/Reviewable/issues/60#issuecomment-78423151
> >
> > > .
> > >
> >
> >
> >
> > --
> > Piotr Kaminski, Founder, reviewable.io
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Reviewable/Reviewable/issues/60#issuecomment-78423562>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/60#issuecomment-78423872>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io
