### ISSUE TITLE
Deleting a commit from a PR doesn't always generate a new revision

### ISSUE THREAD

**Issue by mkow** [Reviewable/Reviewable#1067] opened 2023-05-25 23:48 UTC
This is a similar problem to https://github.com/Reviewable/Reviewable/issues/690, but now on the revisions/commit level (https://github.com/Reviewable/Reviewable/issues/690 was on file level).

Example of the problem:
1. A contributor creates a PR with commit A
2. A reviewer comes and asks the contributor to add a test for the added feature
3. The contributor pushes commit B with the test
4. The reviewer approves the PR
5. The contributor accidentally force-pushes a version without B to the PR branch

If I understand correctly, what happens currently is that Reviewable would create only the following revisions:
- r1 for commit A
- r2 for the state containing commit A + commit B

On the force-push r2 would be marked as obsolete, but no new revision is created. This is confusing for at least two reasons:
- The reviewer can't see that the test was removed since their last review (at point 4.). They would actually want to diff r2 against r3, but r3 was never created. Moreover, I think that "show unreviewed diffs" button would be grey, meaning that there are no new changes to review.
- Revisions are not chronological now - the current state of the PR is in r1, despite r2 being present. r1 represents a merge of r1 and (non-existent) r3.

Ideally (at least for me :) ) at point 5. a new revision should be created, so the reviewer could clearly see that something was deleted from the PR since their last review. And also, I think most people expect the revisions to be chronological.

Overall, I'd expect the "show unreviewed diffs" button always show exactly `diff(last_state_I_verified, current_state)`, regardless whether the changes are adding or removing code.

From the discussion on Gitter with @pkaminski the original idea behind the current Reviewable behavior was to not require re-approvals unnecessarily. But I'll leave more detailed explanations to him :)

**Comment by pkaminski** [comment] 2023-06-24 21:26
I did some digging and AFAICT the current logic of "reusing snapshotted commits" has been in place since day one, with no recorded rationale.  It looks like I originally didn't realize that this could lead to the latest revision(s) being obsolete, and about 6 years ago I started guarding against that eventuality by looking for the last non-obsolete revision to be considered as the "latest".  Again, no rationale was recorded, though I believe it was intended to fix https://github.com/Reviewable/Reviewable/issues/483.

I'm guessing that my reason for taking this approach was indeed to recognize past review marks, but I now agree with the argument above that this rationale is flawed, perhaps fatally so.  And honestly, "last revision is latest revision" would a great invariant to have, as having the last revision obsolete has led to all kind of other complications over the years.

This would be a pretty big change, though, so let me ask a few other folks for comments first.

**Comment by pkaminski** [comment] 2023-06-24 21:28
@fahhem, @jwnimmer-tri, I'd be curious to hear your take on this issue.  Thanks!

**Comment by fahhem** [comment] 2023-06-24 21:56
Yes, any time I've seen this it's felt more like a bug than a feature.

Having the reused revision show up twice, or some other UI affordance, to show that the revision is reused would be good, especially if the now-obsolete revision has review marks. If the obsolete revision is short-lived enough that nobody reviewed or commented on it, then completely eliding it would be reasonable.

That means either showing `r1 | r2 | r1` or `r2 | r1` in mkow's example would be fine, since `r2` was approved. However, if `r2` was never interacted with (such as faulty rebases that users clean up) then just `r1` and maybe an icon who's tooltip says `r2 was removed and nothing was marked review or commented on` would work too.

**Comment by jwnimmer-tri** [comment] 2023-06-26 13:57
This all sounds fine to me.  (I think my team rarely/never encounters this, since we use local squash and force-push in almost all cases.)

**Comment by marczych-zoox** [comment] 2023-06-26 21:37
It makes sense to me to have every change to a PR result in a new revision even if it's a revert. Otherwise it could be hard to see what has changed since your last review in the case of a force push.

And if I understand it correctly, right now a PR could incorrectly be considered reviewed after a force push in this scenario:

 - r1, all files reviewed, 1 outstanding discussion
 - r2, fix for discussion pushed, all files reviewed, 0 outstanding discussions
 - force pushed back to r1, all files reviewed, 0 outstanding discussions

In this case, the PR could be merged without the reviewer approving it in its new state.

Are there any downsides to changing the behavior? Perhaps more files would need to be reviewed when reverting changes?

**Comment by pkaminski** [comment] 2023-06-27 03:55
Thanks for your input folks!  A couple clarifications:
1.  If nobody but the PR author has seen the reverted revision it will remain provisional and be automatically discarded once reverted, so this issue doesn't apply in that scenario.  (I have some changes in the pipeline to make the "no one has seen" condition be more accurate, so revisions are less likely to be snapshotted accidentally.)
2.  We can't just reuse / reorder previous revisions, as it would retain their review marks and fail to solve the original problem.

So it appears that the right thing to do is to introduce a new revision if the PR's head doesn't match the (chronologically / numerically) last revision's head commit.  The trade-off is that the files would need to be "reviewed" again, but it sounds like a bit more friction is actually desirable and we can minimize it by making it clear that the files were previous reviewed (if that's in fact the case!).

I think there are some potentially knotty UX questions to work through here, such as:
- Do we only reintroduce one revision, or possibly a larger group of them if it's a commit-by-commit review so the diffs make sense?
- How do we make it clear that the new revisions' contents correspond exactly to previous ones?

I'll dig into this in the near future and follow up here if I need some feedback on the design.  Thanks!

**Comment by fahhem** [comment] 2023-06-27 05:31
> How do we make it clear that the new revisions' contents correspond exactly to previous ones?

Maybe something like this UI:
![image](https://github.com/Reviewable/Reviewable/assets/306100/fce0b079-cf95-417f-a5c3-c91501e6c578)

But where the text/buttons are, if they reviewed the file at that revision already:
`File reviewed at r3, then updated and reverted to r3. [Review Again]`

And if they didn't review it already, then just show the diff. Or if they approved it:
`PR approved at r3, then updated and reverted to r3. [Review Again]`

However, the diff is always shown, to reduce clicks needed. The button simply dismisses the UI.

Alternatively, maybe eye-catching enough is to red-out all the reverted revisions?
![image](https://github.com/Reviewable/Reviewable/assets/306100/71bf25c3-af51-4fd6-beee-b1e436a4765f)
Then, if a file was reviewed at that revision, the eye is red-out as well as a sign that it's not "fresh". If we go with this, then we'd red-out the revisions in the file-matrix too, maybe more subtly since a pageful of red isn't pleasant UI.

With this, I think it's clear that there was a reversion, not a new revision (even though in the backend it's a new revision still, and all the comments, etc are tied to that new revision). I would even say the new revision's number (r11 in this example) should show up anywhere we put the revision number, but it shows up in the reverted-to revision's position (r3).

**Comment by pkaminski** [comment] 2024-01-14 18:26
I thought of an additional complication.  Consider the following scenario:
1. Author pushes r1 and it's reviewed by A and B.
2. Author pushes r2 and it's reviewed by B.
3. Author reverts r2, so we create an r3 equivalent to r1.

At this point, r3 should not be considered reviewed by B, since the state of the PR has changed since the last one they approved (r2).  However, I posit that it _should_ be considered reviewed by A, since as far as they're concerned r2 never happened so their review still stands.  (Another way to think about it is that if B visits the review they'd get the r2-r3 diff by default, whereas A would get a nil r1-r3 diff with no deltas, which is pointless to review.)

I think the rule could be articulated as:  a file's revision is considered reviewed by a user if a previous revision with the same SHA has been reviewed, and no obsolete revisions between them have been reviewed.  (This accounts for multi-commit reverts in a commit-by-commit review.)

<details><summary>This poses some implementation problems though:</summary>
We can't mark the file as reviewed since there's an invariant that 1) only snapshotted revisions can be marked as reviewed, and 2) if a revision has a review mark then all previous revisions must have one as well.  We may be able to get away with ignoring the first one with a bit of care, but the second one is problematic:  if we mark r3 as reviewed by A, then we have to mark r2 as well, but then if r3 gets reverted (assume there's more prior revisions) we end up with a spurious mark on r2 that will prevent and automatically created r4, etc., from being considered as reviewed since an obsolete revision has a review mark.

We could make the inferred review marks virtual, computed on the fly on the client and server.  This would work reasonably well, except on the dashboard where we don't load full revision information (to save on bandwidth) and so wouldn't know which revisions have the same SHA.  A potential workaround would be to shift the computation of per-user files-to-review to the server so the dashboard can just load the final number.  This would also address other problems (having to load all file info on the dashboard, inaccurate dashboard to-review counts due to renamed files) but it's tricky since the result relies on the user's draft state, which generally doesn't trigger server-side reconciliation when it changes.  We do trigger draft state condition evaluations now, though, so perhaps we could hook summary updates into that.

It's not clear whether relaxing or refining the invariants in some way (likely faster, but less benefit) or figuring out per-user summary computation (tricky, but higher impact) is a better approach.
</details>

**Comment by mkow** [comment] 2024-01-22 20:05
> 2) if a revision has a review mark then all previous revisions must have one as well

Do you have to have this invariant? It sounds a bit fishy to me :upside_down_face:
I often review PRs after a few revisions were already submitted, and I might have never seen the older versions of the PR. It sounds a bit dangerous to mark them as reviewed by me.

**Comment by pkaminski** [comment] 2024-01-25 04:40
Never mind, I got lost in my own code.  😅  Review marks are strictly per revision; it's revision snapshots that must be extended to the left.  I think the first implementation approach above would thus work.  We can automatically carry any review marks to an equivalent revision (per the rules sketched out).  We don't need to snapshot the revision since this is effectively an inferred review mark and we lose nothing if the revision is deleted.  (Though we'll need to make sure the review marks are deleted if the revision is replaced since currently the code assumes that only immutable, snapshotted revisions will have marks.)

No plan survives contact with the ~~enemy~~ code, but at least we have a viable starting point!

**Closed** 2024-02-07 18:50 UTC
Labels: enhancement, design needed

**Comment by pkaminski** [comment] 2024-02-07 20:14
Fix deployed, let's see if it holds up in practice.
