### ISSUE TITLE
Latency loading very large reviews

### ISSUE THREAD

**Issue by larsbergstrom** [Reviewable/Reviewable#251] opened 2016-02-11 15:03 UTC
This is a follow-up to my tweet here: https://twitter.com/larsberg_/status/690159889851752448

When loading moderately-sized (for Servo) reviews, such as https://reviewable.io/reviews/servo/servo/9589, they automatically now load in the single-file view, which definitely helps initial load time. However, many of us prefer to just be able to scroll through & see the whole, expanded set of diffs. Unfortunately, that takes several minutes. A casual profile of such an interaction (Firefox Dev edition, 46.0a2, Early 2013 Macbook Pro) is below:

```
Total time Total Cost Self Time Self Cost Samples Function
28,726.69 ms	26.58%	28,726.69 ms	26.58%	28396	Graphics
14,938.97 ms	13.82%	14,938.97 ms	13.82%	14767	Gecko
14,914.69 ms	13.80%	14,914.69 ms	13.80%	14743	b38e8a1bf.libs.js:1reviewable.io
11,905.05 ms	11.02%	11,905.05 ms	11.02%	11768	GC
5,227.17 ms	4.84%	5,227.17 ms	4.84%	5167	Styles
3,728.93 ms	3.45%	3,728.93 ms	3.45%	3686	Q38e8a1bf.libs.js:7reviewable.io
3,440.61 ms	3.18%	3,440.61 ms	3.18%	3401	JIT
2,646.47 ms	2.45%	2,646.47 ms	2.45%	2616	Input & Events
2,538.22 ms	2.35%	2,538.22 ms	2.35%	2509	rc/this.$get</o.prototype.$digest38e8a1bf.libs.js:9reviewable.io
2,260.02 ms	2.09%	2,260.02 ms	2.09%	2234	anonymous/fn38e8a1bf.libs.js%20line%2010%20%3E%20Function:2reviewable.io
1,413.27 ms	1.31%	1,413.27 ms	1.31%	1397	GC
1,230.16 ms	1.14%	1,230.16 ms	1.14%	1216	anonymous/fn038e8a1bf.libs.js%20line%2010%20%3E%20Function:2reviewable.io
1,174.52 ms	1.09%	1,174.52 ms	1.09%	1161	Tools
```

What I mentioned in the tweet is that while our previous review system, critic (http://critic.hoppipolla.co.uk/) had many flaws relative to Reviewable, the one thing that it did very nicely was prepare on the server side all the info required for reviewing such huge diffs, so loading it was incredibly fast.

It's not clear to me if the actual reason it was so much faster is that the graphics demands were much lower ("Graphics" do show up pretty high in the profile here!) or what, but I wanted to follow up on this after the initial tweet and our e-mail thread. As I mentioned, if supporting this scenario better is something that would require additional servers on your side, that might be something where we (Mozilla) would be willing to purchase a subscription of some form.

**Comment by pkaminski** [comment] 2016-02-13 15:37
Hey @larsbergstrom, thanks for a concrete, reproducible case!  However, what do you mean when you say:

> Unfortunately, that takes several minutes.

For me, the page loads in seconds, and updates in seconds again when I opt into showing all the files.  It chugs for a bit longer (~10-15 seconds) while some diffs are computed, but then it gives up and computes them just-in-time (specifically, when a file shows up or is the next file after the one currently showing, so you should almost never see a diff being computed).  Is this the behavior you see, and if so is it acceptable or do  you really need all the diffs computed ahead of time (and why)?  What is it exactly that takes several minutes?

Interestingly, your profile doesn't actually show anything in the diff worker proper, which runs in a web worker loaded from `*.diff_worker.js` and is the only part that could potentially be shifted to the server.  (Though perhaps that's because you only captured performance data for the main thread.)

**Comment by larsbergstrom** [comment] 2016-02-14 01:24
Interesting! What I did here was just load the review, clicked to show all of the files and diffs, and then tried to scroll to the bottom. The scrollbar would stop as it filled in files every few seconds, and it ended up taking a few minutes to finally reach the bottom of the page.

Would you like me to try this again, with additional profiling on? I have to admit I mainly profile Servo and am a bit of a novice at profiling Firefox.

**Comment by pkaminski** [comment] 2016-02-14 02:12
Before jumping into more profiling I'd like to better understand your needs and how you picked your methodology.  Is scrolling to the bottom while waiting for all diffs to fill in something you normally do in a review?  Or is it important to have all diffs pre-loaded, and if so for what reason?  (Ones I can think of include "I use ctrl+f to search through diffs" and "I don't review files in order and don't want to wait for diffs to load".)  When doing a normal review, how much time do you actually spend waiting for diffs to load, or are otherwise inconvenienced by the diffing?

BTW, I'm not terribly familiar with Firefox profiling either, but it looks like there's no way to pick a specific thread so it probably either measures all of them, or can't measure workers at all.

**Comment by bholley** [comment] 2016-02-14 21:18
I expanded all the files in https://reviewable.io/reviews/servo/servo/9567 , and then scrolled around with a profiler on.
<img width="1567" alt="screen shot 2016-02-14 at 1 15 15 pm" src="https://cloud.githubusercontent.com/assets/377435/13036473/0cfcdfa8-d31d-11e5-90fa-1330ed79dc11.png">

Each of those is a ~500ms restyle. The fact that these things are so closely stacked together suggests to me that script is doing something dumb to repeatedly trigger a restyle of the entire document. As a comparison, restyling the entire HTML spec [1] takes about 1s on my machine. So I'm guessing there's a lot of duplicated work here. Let me know if you need more information on the kinds of things tend to trigger restyles.

[1] http://www.whatwg.org/specs/web-apps/current-work/

**Comment by pkaminski** [comment] 2016-02-15 03:02
Hey @bholley, I can certainly take a look at that, but could you please open a separate issue?  I think yours is about steady-state performance on large reviews, whereas @larsbergstrom is specifically concerned about loading time.  Also, I can't reproduce 500ms repaints in Chrome (even on my somewhat outdated laptop), so another explanation is that the Firefox renderer is sub-optimal.  :wink:

**Comment by larsbergstrom** [comment] 2016-02-15 14:54
@pkaminski I suspect that Bobby has tracked down what was causing the perf issue in my scenario - that is, that there's some bit of JavaScript that is triggering a restyle as you attempt to scroll down the page.

Re: Firefox, all browsers have some set of hacks & optimizations to attempt to reduce the pain inflicted on users by scripts that are doing something that can kill performance. If this site was developed against one browser (e.g., Chrome), it's likely that the code takes an optimized path that works only on browsers from that codebase. I've noticed that this review loads fine in webkit-based browsers (Chrome and Safari), but on Firefox and Edge the experience is much worse. Edge, even on my super high-end desktop machine, also has pauses and flickering during scrolling on the review that @bholley mentioned.

**Comment by larsbergstrom** [comment] 2016-02-15 14:56
In fact, I just noticed that on Edge even though the page appears to be completely loaded, the browser never stops restyling. You continuously have a spinning cursor and the titlebar flickers as the page continues to restyle forever.

**Comment by bholley** [comment] 2016-02-15 19:23
To clarify my earlier STR, the problem reproduces very easily when leaving a comment. Every couple of keystrokes seems to trigger a restyle of the entire document, which suggests that there's a keyboard handler that is dirtying the entire document on each call.

In general, ditto to what @larsbergstrom said. The issue here is not restyle performance itself (where Firefox and Chrome are very competitive), but rather the set of fast-paths that each engine uses when a restyle is technically required but a certain set of very-specific conditions allow the engine to prove that the restyle is actually unnecessary.

It's generally infeasible to fast-path everything, and different browsers make different bets as to the set of fast-paths that yield the best performance across the entire web. But as the web drifts more towards Chrome-monoculture, developers are starting to develop and test their products exclusively in Chrome, which makes it very easily to do something that relies on one of Chrome's fast-paths to optimize out pessimally-slow behavior (like dirtying the style of the entire document on every keystroke). When this happens, other engines have no choice but to mimic Chrome's performance tradeoffs, making them a de-facto (but undocumented) standard that reduces the room for performance innovation on the web.

Given the above, it would be great if you fixed reviewable. But given the state of the world, we also probably need to investigate and duplicate whatever Chrome behavior this is relying on (déjà vu 1999...). I'll try to get that looked at in the next day or two, but please give me a heads-up before deploying any fixes to production, since that will make our testcase go away. ;-)

**Comment by pkaminski** [comment] 2016-02-16 07:40
I hear you, and I'm certainly guilty of testing primarily on Chrome (since it accounts for 70%+ of my user base).  I'm sympathetic to maintaining a diverse browser ecosystem, though, and would love to investigate this, but just trying to explore a captured Firefox profile brings my laptop to its knees so it'll have to wait until I'm back home next week.

FWIW, the Edge issue is captured in https://github.com/Reviewable/Reviewable/issues/237.  I haven't made any effort to track it down yet, though, since Edge makes up a trivial part of my user base and it's young enough to have a bunch of other weird, not-easily-reproducible issues that I don't want to sink time into.  Perhaps when it has matured a bit.

**Comment by larsbergstrom** [comment] 2016-02-16 16:18
@pkaminski In case you're interested, the amazing @heycam has done some initial investigation as to what's going on here: https://bugzilla.mozilla.org/show_bug.cgi?id=1248509

**Comment by pkaminski** [comment] 2016-02-17 03:58
I'm very interested but the cause @heycam identified leaves me confused, and I can't reproduce it.  Assuming he's referring to the `.diff.pane`, I do manipulate the height manually but only when the diff is updated (e.g., bounds change).  The update can be a bit delayed due to animation but it only happens once, as confirmed by instrumenting my code and looking for changes in the Chrome and Firefox inspectors.  Whereas what you appear to be seeing is that it happens at each Angular digest (which is what happens when, e.g., you type in a few characters in a comment).

So I'm still not sure what's going on here...

**Comment by pkaminski** [comment] 2016-03-06 09:03
I tried digging into this some more.  Unfortunately, the Firefox profiler is still broken for me even on my desktop machine -- the perf viewer is so slow that it's unusable.  Maybe I'm doing something wrong.  The profiler in Edge worked nicely, though, and led me to figure out that changing `pointer-events` on some elements (even fairly small ones) leads to a full-page layout in Edge.  This is a problem since, by default, it gets changed twice every 200ms (and twice again on a separate 1000ms cycle).

I'm guessing that Firefox has the same problem since I don't think any other styles are being changed regularly when the page is idle.  While I tear out my hair looking for a workaround, could you please confirm that this is indeed the issue?  I added a new flag so you can turn off the `pointer-events` changes by appending `?debug=pointerevents` to any Reviewable URL, e.g. https://reviewable.io/reviews/servo/servo/9567?debug=pointerevents.  If I'm right, this should significantly improve steady-state performance.  The only side-effect will be slight breakage of the help feature (butterfly prompts, help overlay, etc.).

Thanks!

**Comment by pkaminski** [comment] 2016-03-06 10:03
Surprisingly, finding and implementing a workaround only took an extra hour.  I refactored the code to use `elementsFromPoint` when available to avoid switching `pointer-events` around.  This is already present in Chrome and Edge, and coming to Firefox in v46.  I tested with FF Developer Edition v46 and it seems to work fine -- everything was smooth, and even the profiler worked!

Can somebody confirm that the performance issue is now gone in FF46?  If so, I'll close this issue, since apparently it's scheduled for general release on April 19, which is close enough.

**Comment by larsbergstrom** [comment] 2016-03-06 14:15
@pkaminski I'm on Firefox Nightly (47.0a1), and that seem to have massively improved the performance while scrolling - thanks a ton!

**Comment by pkaminski** [comment] 2016-03-06 23:48
Great!  I updated the Bugzilla issue with root cause information.  Closing.

**Closed by pkaminski** 2016-03-06 23:48 UTC
Labels: bug

**Comment by munrobasher** [comment] 2016-11-20 02:20
Found here whilst researching "Is Edge really getting worse rather than better" kind of thing. The link at the top of this page ( https://reviewable.io/reviews/servo/servo/9589) crashes on Edge... opens fine on Chrome or IE11

**Comment by pkaminski** [comment] 2016-11-20 19:59
Yeah, see #267 for the ongoing story of Edge problems.
