### ISSUE TITLE
Reviews button in the top bar is broken

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#713] opened 2020-01-15 17:00 UTC
Recent regression.

**Expected:** Reviewable button in the top bar on a review page links to My Reviews
**Actual:** the button links to the current review itself

**Comment by pkaminski** [comment] 2020-01-15 18:00
I assume you mean the leftmost button in the header bar, with the bunny logo?  It seems to work for me, though it links to the home page (as intended).  The Reviews button works too FWIW.  What exact sequence of clicks (starting with a fresh page load) are you following?  Which browser?

@badz0 can you repro?

**Comment by feldgendler** [comment] 2020-01-15 19:06
No, sorry, I mean the Reviews button (eye icon). I can't reproduce it anymore, either, although for a while it was broken for me on all reviews.

**Comment by feldgendler** [comment] 2020-01-30 17:28
Accidentally reproduced again in one browser tab. Doesn't happen in another tab if I open the same URL.

**Comment by feldgendler** [comment] 2020-01-30 17:30
Using the Chrome developer tools on the button reveals that the A element points to the review itself:
```
<a class="reviews item" ng-href="/reviews/ridge/mage/8" ng-click="loginAndGoTo(lastReviewsPath, 'visitedReviews')" ng-class="{hover: $route.current.controller === 'dashboardController' &amp;&amp; !$route.current.params.repo}" href="/reviews/ridge/mage/8"><i class="unhide icon" alt=""></i> Reviews </a>
```

**Comment by pkaminski** [comment] 2020-01-30 21:43
Thanks!  @badz0 I think that `beforeDestroy` may be racing with `openPullRequestUrl` in `dashboard.vue`, could you take a look please?

**Comment by badz0** [comment] 2020-01-31 18:40
Sure. The `$location` changes faster then `beforeDestroy` hook is called. Working on that.

**Comment by pkaminski** [comment] 2020-02-12 06:35
This should be fixed as of a week ago.

**Closed by pkaminski** 2020-02-12 06:35 UTC
Labels: bug
