### ISSUE TITLE
Pressing shift in large reviews hangs the browser for several seconds

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#128] opened 2015-07-18 14:54 UTC
In https://reviewable.io/reviews/servo/servo/6490#- I selected the full range of all revisions, then left a comment on a file. Every time I used a capital letter (or even switched tabs using keyboard shortcuts that included shift) the browser would hang for several seconds. Performance was fine if I only used lowercase letters.

**Comment by pkaminski** [comment] 2015-07-18 20:45
Thanks, reproduced.  I think this is caused by the very large diff for `hsts_preload.json`.  Can you confirm that if you nil out that diff (e.g., diff r19-r20 just for that file), the delays go away?

FYI, if you're curious why holding down shift might have this effect: shift-clicking on a path will open the file in a new window, and I try to make this somewhat discoverable by fading in "external link" icons next to the pathnames when shift (or ctrl/cmd) is held down.  Apparently the browser's renderer is having some trouble with the global style change, even though it doesn't affect the diffs proper.

**Comment by pkaminski** [comment] 2015-07-18 23:37
I haven't been able to get to the bottom of what the browser is doing when the large diff is there; Chrome just says "other" or "program" for 99% of time spent!  I added some code to hide diffs with more than 1000 lines of delta by default -- if you decide to display them anyway, at least you'll know what you're in for.

**Comment by jdm** [comment] 2015-07-19 00:36
I agree with your conclusions.

**Comment by pkaminski** [comment] 2015-07-19 03:33
OK, closing.

**Closed by pkaminski** 2015-07-19 03:33 UTC
Labels: bug
