### ISSUE TITLE
"No response required" comments

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#118] opened 2015-07-06 16:24 UTC
Sometimes a comment requires no response, e.g. "I like how you're doing this here."

Critique had a "No response required" checkbox when you drafted a comment and I used frequently. It would be nice to have something similar for Reviewable. These comments shouldn't count towards the number of unreplied comments in the review.

**Comment by pkaminski** [comment] 2015-07-06 21:50
Reviewable purposely simplifies this and conflates the "unreplied", "new message", and "unresolved" flags.  As with all things in life, this is a trade-off: a less complex mental model that occasionally requires a bit of extra work from the users.  Since taking care of a "no response required" comment is just a matter of hitting "Acknowledge", in practice this limitation only matters in the last round of the review prior to merging the PR (since an unresolved comment will block the merge in Reviewable).  A workaround is that the person who wants to do the merge can acknowledge all the comments first to resolve them, merge the PR, then post any "no response required" follow-ups.

Do you have another scenario where this limitation has a big impact?

**Comment by pkaminski** [comment] 2015-07-14 18:46
Ping @danvk?

**Comment by danvk** [comment] 2015-07-14 18:51
My proposal is to add a "no action required" checkbox on the new comment draft form. If this isn't something you want to model explicitly, that's fine. I did find this useful in the past when using Critique.

**Comment by pkaminski** [comment] 2015-07-14 18:52
I try to avoid unnecessary complications, so I wanted to get a feel from you for the real impact of requiring people to acknowledge explicitly (see message above).

**Comment by danvk** [comment] 2015-07-14 18:55
Right, the workaround is that the PR author has to click "Acknowledge". It's not that big a deal.

The nice thing about modeling this explicitly is that the PR author knows exactly when the reviewer wants them to take action. So there's less ambiguity.

**Comment by pkaminski** [comment] 2015-07-14 19:01
OK, thanks.  This doesn't pass my complexity / value trade-off test so I'm closing as won't fix, but will reopen if there's further evidence of demand or benefits I didn't consider.

**Comment by danvk** [comment] 2015-07-14 20:01
The other use case is when you'd like to resolve a thread by saying something like "Nicely done!" rather than clicking the silent "Acknowledged" button. Saying "Nicely done!" currently forces the other person on the review to sign off.

**Comment by pkaminski** [comment] 2015-07-14 20:26
Presumably you'd like the other person to read the "Nicely done!" comment, in which case clicking Acknowledge seems like a fairly minor imposition once they're already there.

**Comment by pkaminski** [comment] 2015-09-30 22:22
I've gotten lots more inquiries about this feature (from @jdm, @fearphage, @dallasgutauckis, and @apinstein, among others I've probably forgotten) so it's clear that the status quo isn't satisfying.  Reopening.

**Comment by bpflanz-adfin** [comment] 2015-10-01 18:16
I'd like to drop a +1 here too (perhaps because I'm coming from the same environment as danvk).

**Comment by pkaminski** [comment] 2015-10-05 21:13
This is now implemented.  The UI is intentionally discreet so let me know if you have trouble finding it.  Adding this introduced a new discussion state throughout the app (resolved but unreplied) and I may not have correctly adjusted all the code to deal with it -- please keep an eye out for oddities if you use this feature and yell at me if you see any!  Thanks.

**Closed by pkaminski** 2015-10-05 21:13 UTC
Labels: enhancement

**Comment by apinstein** [comment] 2015-10-05 21:33
Will do, thanks!

**Comment by pkaminski** [comment] 2015-10-11 07:00
I added a further feature in this vein:  "author response required" comments, which won't let a comment be resolved until the PR author has replied (they can't just acknowledge).  Also reworked the UI a bit to support this so the "FYI only" icon has changed.

**Comment by apinstein** [comment] 2015-10-11 12:59
Eeesh. I fear that this starts to go down the road of too many features that make it really hard to understand what's going on. The product is great from a core functionality standpoint, but I'd prefer to see the simplest possible experience. It's already getting frustrating trying to understand what state things are in...

**Comment by pkaminski** [comment] 2015-10-11 18:55
@apinstein "Don't need it, don't use it."  :smile: I bet you wouldn't even have noticed the new feature if I hadn't mentioned it here...  It's definitely only for experts users who want fine control over the resolution of discussions.

**Comment by apinstein** [comment] 2015-10-14 15:01
Why do the general comments work differently from line comments?

Sometimes if something is left out, I cannot make a comment on a line, but it is also not opening an “unresolved item”. I don’t understand the point of having those two types of comments behave differently.

Thoughts?

**Comment by pkaminski** [comment] 2015-10-14 23:24
Indeed, all top-level comments are effectively treated as "FYI".  My reasoning is that, in a multi-party review, the top-level discussion is likely to pick up almost everyone as a participant since it's common to add a "cover message" prior to hitting publish.  If it were to be treated as unresolved, everyone would need to acknowledge every message before the review would count as completed, which could end up quite inconvenient.

I made this decision long before the per-message disposition control became available, though, so I could certainly imagine revisiting it.  #182 may also have bearing on this.

In the meantime, the workaround is to use a line discussion on some random location.  (The convention I've seen is to put it on the first line of the most relevant file, e.g., another one in the same directory.)

**Comment by apinstein** [comment] 2015-10-15 02:54
Good thought.

I’ll add some context of my thinking to see if it helps.

1. It seems someone must acknowledge commits; at least if you don’t you don’t 0 out one of the counters (tho it’s grey, not red). In any case this always feels totally pointless, b/c already if the commits have changes then it appears red as un-reviewed files. Beyond that, I frequently forget to acknowledge commits and have to go back to do that, usually after publishing, which then triggers another publish. So that doesn’t quite feel like “FYI”, unless I’m missing something.
2. A huge part of the appear of Reviewable is the confidence that any comment I make results in an open to-do; so the current default behavior is an accidental > /dev/null for global comments, and is definitely a source of WTF’s for the team.

Your stated workaround does work for now, however when there is *missing* code sometimes there’s not an obvious place to make a comment.

Anyway clearly you grok what I’m saying so I’ll leave it at that for now. :)

**Comment by pkaminski** [comment] 2015-10-15 07:50
Yep, I definitely understand your concern and will try to work out what the right thing to do is.

I'll double-check that the synthetic commit messages don't need to be acknowledged -- that's certainly the intent, anyway.  Also note that acknowledging a discussion is instantaneous and doesn't require publishing.

**Comment by apinstein** [comment] 2015-10-16 20:38
I’ve been paying attention to this; it seems that when a PR is opened, the synthetic msg from the initial set of commits does cause a RED “to reply” warning, whereas subsequent manual messages in the “top area” don’t trigger that. I think that makes it even more confusing, since the UX of the initial one requiring reply makes me think that if I respond there it’d do the same thing….

**Comment by pkaminski** [comment] 2015-10-17 02:47
I tested this again just now and can't reproduce what you're reporting.
Note that the red "to reply" counts are not the same across users: only
people other than the message poster will get their count incremented by
1.  The synthetic messages are a bit trickier (they're "posted" by the PR
author, but if the discussion was unreplied for the author before the
synthetic messages, it'll remain so).

But the message that all this is confusing has been received loud and
clear.  :)


On Fri, Oct 16, 2015 at 1:38 PM, Alan Pinstein <notifications@github.com>
wrote:

> I’ve been paying attention to this; it seems that when a PR is opened, the
> synthetic msg from the initial set of commits does cause a RED “to reply”
> warning, whereas subsequent manual messages in the “top area” don’t trigger
> that. I think that makes it even more confusing, since the UX of the
> initial one requiring reply makes me think that if I respond there it’d do
> the same thing….
>
> > On Oct 15, 2015, at 3:50 AM, Piotr Kaminski <notifications@github.com>
> wrote:
> >
> > Yep, I definitely understand your concern and will try to work out what
> the right thing to do is.
> >
> > I'll double-check that the synthetic commit messages don't need to be
> acknowledged -- that's certainly the intent, anyway. Also note that
> acknowledging a discussion is instantaneous and doesn't require publishing.
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/Reviewable/Reviewable/issues/118#issuecomment-148308551
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/118#issuecomment-148827865>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by apinstein** [comment] 2015-10-17 12:15
Oh so I just realized I left out an important detail. Someone else on my team posted the pr, so that explains why it was red. And actually that makes sense. 

I will continue to think about why it confuses me. 

It's a really great tool and has vastly improved our workflow - we can handle complex pr's much faster now. I just found I've had trouble explaining the mental model for it to the team!

Maybe I should write down the "intro to reviewable" I've been giving and share it with you.
