### ISSUE TITLE
Pasting into a comment field removes keyboard focus

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#360] opened 2016-07-15 20:02 UTC
When I paste anything into a review comment, the content pastes, but the textarea loses focus afterwards. I'm using Firefox nightly on OS X.

**Comment by pkaminski** [comment] 2016-07-15 21:47
Unable to reproduce in Firefox 49.0a2 on OS X 10.10.5.  Absent further details (can you repro with 49.0a2? what's your OS X version?) I'm going to assume this is a regression in the nightlies and let it be unless and until it rears its ugly head in a more mainstream release.

**Comment by jdm** [comment] 2016-07-15 23:06
You're right; I can't reproduce it in FF 48, so this is clearly a Firefox regression.

**Comment by mystor** [comment] 2016-07-19 20:46
@pkaminski, This bug appears to have been caused by Firefox implementing the `DataTransferItemList` specification. I believe that this error is on your side, due to user-agent sniffing.

From my testing, you can reproduce this error in chromium by spoofing the Firefox user agent, and can avoid the problem in Firefox nightly by spoofing the chrome user agent.

It seems like in the "paste" listener you sniff the user agent, and use that to decide what action to perform. If the Firefox user agent is detected, you then check for the presence of `e.clipboardData.items`. In versions of Firefox less than 50, `e.clipboardData.items` will not be present, but in Firefox 50, we now implement this interface. This is probably what is breaking in your code.

**Comment by pkaminski** [comment] 2016-07-19 20:56
Thanks @mystor, I opened an [issue](https://github.com/layerssss/paste.js/issues/29) against the paste handling library that Reviewable uses.

**Comment by pkaminski** [comment] 2016-09-07 06:32
Fix merged, should be OK now.

**Closed by pkaminski** 2016-09-07 06:32 UTC
Labels: bug
