### ISSUE TITLE
GitHub 404 blocks merge, ff, etc.

### ISSUE THREAD

**Issue by macmason-tri** [Reviewable/Reviewable#401] opened 2016-09-26 17:45 UTC
We're getting GitHub 404s on attempts to merge, ff, etc:

"Unable to merge branch: GitHub 404 error on PUT https://api.github.com/repos/toyotaresearchinstitute/cartographer_hsr/pulls/1/merge"

Thoughts?

(Related, minor, UI issue: I can't select the error message text, so I had to retype it here.)

**Comment by pkaminski** [comment] 2016-09-26 19:28
That's very odd -- the repo and PR show up through the API, you have full permissions, and 404 is not even a documented error for this call.  Do you mind if I try to merge the PR in your name to see if I can get any more information about what's going on?  If that's OK, what kind of merge would you prefer?

I'll also make error message text selectable in the next release, thanks for the nudge!

**Comment by macmason-tri** [comment] 2016-09-26 19:29
Feel free to merge. Squash-commit, delete the branch, please. Commit message:

"Address code review comments for initial checkin."

**Comment by pkaminski** [comment] 2016-09-26 19:43
Never mind, I see what happened: GitHub updated the squashing API without notice (fair enough, as it's still in preview).  I update Reviewable to match -- could you give it another try please?  Thanks.

**Comment by macmason-tri** [comment] 2016-09-26 19:46
No luck; did a force-reload on the page, triggered the submit, same error.

**Comment by pkaminski** [comment] 2016-09-26 19:47
Back to the drawing board...

**Comment by pkaminski** [comment] 2016-09-26 19:56
I can reproduce the error on your PR, but not on my own ones.  I'm going to need to ping GitHub support to see if they can assist since it looks like a potential bug in their merge API preview.  They usually respond within a few hours and it would be invaluable if you could keep the PR open until then!  Thanks.

**Comment by pkaminski** [comment] 2016-09-26 20:02
A random thought: do you have third party apps restricted on this organization by any chance?  That has been responsible for mysterious 404 errors in the past.

**Comment by david-german-tri** [comment] 2016-09-26 20:24
> do you have third party apps restricted on this organization by any chance?

Yes, we do.  That's probably the culprit.

We'll look into lifting the restriction.  It's a little unclear to us what additional privileges GitHub would grant if we do.

**Comment by pkaminski** [comment] 2016-09-26 20:28
OK, that's likely the cause -- closing issue, but please reopen if it recurs after you lift the restrictions.

Allowing Reviewable as a third-party app basically means that whenever a user grants Reviewable the right to access GitHub in their name, those rights can be exercised against the organization's resources too.  So, for example, you granted `public_repo` scope to Reviewable; since Reviewable isn't white-listed as a third-party app, this scope currently doesn't apply to your interactions with the organization's resources and Reviewable has effectively anonymous user privileges wrt to the organization.  If you white-list Reviewable, it'll gain full read/write access to the organization's public repos under your name.

**Closed by pkaminski** 2016-09-26 20:28 UTC
Labels: bug
