### ISSUE TITLE
"Looking for base changes" indefinitely

### ISSUE THREAD

**Issue by jwnimmer-tri** [Reviewable/Reviewable#974] opened 2022-10-20 22:17 UTC
When I open https://reviewable.io/reviews/RobotLocomotion/drake/17572#-, the spinner gets stuck on "Looking for base changes" seemingly indefinitely (at least, longer than a minute or two).

FF 105.0 on Ubuntu 20

**Comment by pkaminski** [comment] 2022-10-20 23:05
Sorry about that -- I've been trying to track down the issue since this morning, with no luck so far.  I've put in a failsafe that should at least ensure it doesn't spin forever.  Could you give it another try?  Thanks.

**Comment by jwnimmer-tri** [comment] 2022-10-20 23:21
I waited for about a minute, still spinning.  So I typed Ctrl-Shift-R which I think is FF's "force reload".... still spinning after waiting 5 more minutes.

**Comment by pkaminski** [comment] 2022-10-21 00:10
Fix attempt number two is up, please reload to try again.  It shouldn't spin for more than a few seconds at most.

**Comment by jwnimmer-tri** [comment] 2022-10-21 00:17
Yup, it works now.  The response is nearly instantaneous (well under a second).

**Comment by pkaminski** [comment] 2022-10-21 00:39
Thanks.  I'll need to revisit the fix since I think it might be too aggressive in some cases, but at least it'll do for now.

**Comment by pkaminski** [comment] 2022-10-22 21:52
I redesigned much of the basemap capturing logic, so please be on the lookout for any regressions!  Thanks.

**Comment by hongkai-dai** [comment] 2022-10-23 18:33
The problem seems to pertain after I force-pushed to the same branch again. Now reviewable stalls on this PR and keeps saying "Looking for base changes".

**Comment by pkaminski** [comment] 2022-10-23 18:35
Is this on the same PR as mentioned above?

**Comment by hongkai-dai** [comment] 2022-10-23 18:38
Yes, this is the same PR mentioned above.

**Comment by pkaminski** [comment] 2022-10-23 18:39
On it.

**Comment by pkaminski** [comment] 2022-10-23 18:48
I can't seem to reproduce the issue but it could be user-dependent.  Could you please run the following line in your JS console and report the result?
```js
JSON.stringify(_(truss.store.services.reviewContext.current.review.files).flatMap(file => file.revisions.list).filter('basemapNeeded').keyBy(rev => `${rev.file.$key}:${rev.$key}`).mapValues(rev => ({ready: rev.basemapReady, flag: rev._basemapFetches[rev.basemapKey]})).value())
```

**Comment by jwnimmer-tri** [comment] 2022-10-23 18:52
```
"{\"-NDUkqWHNHUVGFZ65UQR:r6\":{\"ready\":true},\"-NEgwV2LgG2g50bSk2Ho:r10\":{\"ready\":true},\"r0-N6urAJqZKe6dzDjtT2p-r5-NDUkqWHNHUVGFZ65UQU-r9-NEgwV2LgG2g50bSk2Hr:r10\":{\"ready\":false},\"r0-N6urAJqZKe6dzDjtT2q-r5-NDUkqWHNHUVGFZ65UQV-r9-NEgwV2LgG2g50bSk2Hs:r10\":{\"ready\":false},\"r0-N6urAJqZKe6dzDjtT2r-r5-NDUkqWHNHUVGFZ65UQW-r9-NEgwV2LgG2g50bSk2Ht:r10\":{\"ready\":false},\"r0-N6urAJqZKe6dzDjtT2t-r5-NDUkqWHNHUVGFZ65UQY-r9-NEgwV2LgG2g50bSk2Hv:r10\":{\"ready\":false},\"r0-N6urAJqZKe6dzDjtT2u-r5-NDUkqWHNHUVGFZ65UQZ-r9-NEgwV2LgG2g50bSk2Hw:r10\":{\"ready\":true}}"
```

**Comment by pkaminski** [comment] 2022-10-23 18:53
Did you reload the page since yesterday?  The values I'm seeing don't make sense wrt the updated code.

**Comment by jwnimmer-tri** [comment] 2022-10-23 19:00
I had closed the page yesterday.  This morning I happened to reboot, and just before posting the above I had opened the page afresh today.

Here's another grab from today after a Ctrl-Shift-R.  It seems identical on first glance.

```
"{\"-NDUkqWHNHUVGFZ65UQR:r6\":{\"ready\":true},\"-NEgwV2LgG2g50bSk2Ho:r10\":{\"ready\":true},\"r0-N6urAJqZKe6dzDjtT2p-r5-NDUkqWHNHUVGFZ65UQU-r9-NEgwV2LgG2g50bSk2Hr:r10\":{\"ready\":false},\"r0-N6urAJqZKe6dzDjtT2q-r5-NDUkqWHNHUVGFZ65UQV-r9-NEgwV2LgG2g50bSk2Hs:r10\":{\"ready\":false},\"r0-N6urAJqZKe6dzDjtT2r-r5-NDUkqWHNHUVGFZ65UQW-r9-NEgwV2LgG2g50bSk2Ht:r10\":{\"ready\":false},\"r0-N6urAJqZKe6dzDjtT2t-r5-NDUkqWHNHUVGFZ65UQY-r9-NEgwV2LgG2g50bSk2Hv:r10\":{\"ready\":false},\"r0-N6urAJqZKe6dzDjtT2u-r5-NDUkqWHNHUVGFZ65UQZ-r9-NEgwV2LgG2g50bSk2Hw:r10\":{\"ready\":true}}"
```

**Comment by pkaminski** [comment] 2022-10-23 19:16
I'm onto something but will need a bit more time to figure it out, sorry.  I'll update on progress within an hour.

**Comment by pkaminski** [comment] 2022-10-23 20:00
So I found a small oversight, that required restructuring hundreds of lines of code to resolve... Sigh.  Anyway, should be better now with a bit of luck -- please reload the page and give it another try.  Thanks for your patience!

**Comment by jwnimmer-tri** [comment] 2022-10-23 20:48
Shortly after you posted is still wasn't working, but I just tried again and it's back to happy now.

**Comment by pkaminski** [comment] 2022-10-23 21:12
There's a potential 5 minute cache timeout if you don't force reload, so you probably hit that.  I'll close this again, but I'll be around for the rest of the day in case I didn't quite get this bug beaten down.

**Closed by pkaminski** 2022-10-23 21:12 UTC
Labels: bug
