### ISSUE TITLE
Not closed quoted code block used in the previous comment affects the new comment

### ISSUE THREAD

**Issue by prashant-shahi** [Reviewable/Reviewable#663] opened 2019-07-24 11:40 UTC
If someone uses quoted code block *```* in a comment and doesn't close it, the same one affects any following comments.

**Comment by badz0** [comment] 2019-07-26 17:19
I couldn't reproduce the issue. @prashant-shahi could you provide more details on this?

**Comment by pkaminski** [comment] 2019-09-11 16:02
Closing due to lack of details.

**Closed by pkaminski** 2019-09-11 16:02 UTC
Labels: invalid
