### ISSUE TITLE
files reviewed by other reviewers are marked as already reviewed even with "Include changes in files previously reviewed only by others." set

### ISSUE THREAD

**Issue by seansfkelley** [Reviewable/Reviewable#455] opened 2017-02-09 23:35 UTC
I like to do code reviews entirely independently of others. If there are files that I am not familiar with I will mark-as-reviewed/tag others, but I like to read files that others have reviewed because there might be (is often) something helpful to the reading of the review and/or something I spot that others didn't. For that reason, having others' reviews mark files as reviewed is problematic for me.

To fix this I enabled the "Include changes in files previously reviewed only by others." option on a couple weeks ago, but I just had a review where I was a few files in, took a break, and came back and all the files had been reviewed by someone else and marked as such. The option was on at the start of the review and is still on now. "Show Unreviewed Diffs", though enabled and clicked, has no discernible effect.

This unfortunately makes Reviewable a lot more useless! Navigation becomes a lot slower and context is easily lost, as n/p no longer work (shift + n/p does, though) and my reviewed/unreviewed markers are clobbered.

**Comment by pkaminski** [comment] 2017-02-10 03:24
Hey Sean, from your description this sounds like a potential bug since the intended behavior is the one you want.  Could you please let me know the PR you're seeing this in, and thrown in a screenshot of the Changes box and the file matrix?  If this is for a private review, you can send the info to support@reviewable.io instead.  Thanks!

**Comment by pkaminski** [comment] 2017-02-14 04:32
After looking at the additional material you sent in, I think this is a duplicate of #404.  Can you look at the discussion and follow up there if the resolution is not satisfactory?  Or if you have a better idea how to simplify the semantics.  :)  Thanks.

**Closed by pkaminski** 2017-02-14 04:32 UTC
Labels: duplicate

**Comment by seansfkelley** [comment] 2017-02-15 17:06
Yup, looks like it is. Changing my hotkeys works! FWIW, I think https://github.com/Reviewable/Reviewable/issues/404#issuecomment-252347862 hits the nail square on the head, in particular, the first half:

> I think the confusion here is that marking a file is reviewed has two completely separate meanings. The first meaning is the reviewer has seen that state of the file and wants any future reviews by them to only look at subsequent diffs. The second meaning is actually "signing off" on the file as valid. We only care about the first meaning.

**Comment by pkaminski** [comment] 2017-02-16 03:55
Yeah, Reviewable often confounds two separate meanings on purpose (also see: acknowledge), which simplifies the common workflow but makes some edge cases more confusing.  It's a judgement call, but I'm pretty sure separating every intention into its own action is not a valid solution either...

**Comment by seansfkelley** [comment] 2017-02-17 02:48
Yeah, agreed. Between tweaking the hotkeys and telling people that all reviewers must approve regardless of file-reviewed status, we get what we want.
