### ISSUE TITLE
Links to comments in resolved diffs are not opened

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#98] opened 2015-05-15 19:17 UTC
In #29 the comment the OP linked to never opens. This means that when trying to create a new issue out of comments from review, the context has to be re-written or its location described as opposed to just linking to the conversation.

**Comment by pkaminski** [comment] 2015-05-15 22:33
Unable to reproduce.  Did you wait for the review to fully load, i.e. all files have diff stats or "..." next to them in the file matrix?  Can you provide other links to repro?

**Comment by pkaminski** [comment] 2015-05-16 08:17
Also, what did you mean by "resolved diffs"?  Did you mean resolved discussions?  Because if so, yeah, links to resolved discussions don't properly expand them -- I'll fix that.

**Comment by mmlb** [comment] 2015-05-19 17:32
That link is working now. I didn't look for the diffstat/... but did wait a while before saying that that link was not working, could have been slow *internets* /shrug.

yes to the resolved discussions, and fixing that would be great!

**Comment by pkaminski** [comment] 2015-05-19 18:31
OK, cool.  Slow opening of linked discussions is tracked in #29, and links to resolved discussions are already fixed.  I'm going to close this issue for now but please reopen if you get another occurrence.

**Closed by pkaminski** 2015-05-19 18:31 UTC

**Comment by mmlb** [comment] 2015-05-19 18:49
:+1:
