### ISSUE TITLE
Terraform and HCL syntax highlighting

### ISSUE THREAD

**Issue by misha-tectonic** [Reviewable/Reviewable#669] opened 2019-08-22 08:56 UTC
Please add Terraform (.tf) and HCL (.hcl) syntax highlighting.

There is a highlight.js "plugin" for that: https://github.com/highlightjs/highlightjs-terraform

**Comment by pkaminski** [comment] 2019-08-22 11:55
Dupe of #668.

**Closed by pkaminski** 2019-08-22 11:55 UTC
Labels: duplicate
