### ISSUE TITLE
undefined is not an object (evaluating 'e.message')

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#410] opened 2016-10-19 21:31 UTC
I just hit this again. Definitely using Safari 10, not Safari Technology Preview 10.1. It occurred when I was in a review, I narrowed the bounds of one file, then immediately after put them back to how they used to be.

**Comment by kballard** [comment] 2016-10-19 21:49
And again. This time I finished writing a comment, marked the file as reviewed, and started scrolling upwards. Right after the top of the file came into view (probably about 2 seconds after marking the file as reviewed), the crash popped up.

**Comment by kballard** [comment] 2016-10-19 21:50
Augh, the comment I had finished writing apparently didn't save! After reloading, only the first part of the comment is there, the rest of it is gone. So the error must have happened while trying to save the comment.

**Comment by pkaminski** [comment] 2016-10-19 23:02
I'm convinced this is a Safari bug.  I deployed an attempt at a workaround that will (hopefully) detect the condition before it causes a crash and retry the function call.  But this assumes that 1) the condition is detectable and 2) that the bug isn't "sticky", because if it is then this will just cause an infinite loop and blow the stack.  I guess we'll see...

**Comment by kballard** [comment] 2016-10-19 23:03
Is there any way for me to catch this error and try to debug it when it happens?

**Comment by pkaminski** [comment] 2016-10-20 00:21
Not really with the minified code, no.  But it's literally "var has a well-defined object assigned on line N, then on line N+M trying to access a member claims the var is undefined even though it hasn't been reassigned in between".  If you speak JavaScript I can even post the relevant snippet here, it's just ~50 lines.

The workaround attempt will at least let me know if the variable truly becomes undefined, or if the bug is specific to accessing that member.

**Comment by kballard** [comment] 2016-10-20 18:05
I do understand JavaScript, so it would be interesting to see the snippet.

**Comment by pkaminski** [comment] 2016-10-20 20:03
Here's the relevant code (including the workaround).  The two accesses to `diff.message` are what's sporadically failing under Safari.  Perhaps you'll spot something I missed.

```js
  Differ.prototype.diffFile = function(file, leftFileRev, rightFileRev, force) {
    var diff = {
      leftFileRev: leftFileRev, rightFileRev: rightFileRev, review: this.review, file: file,
      filename: file.path, working: true, decorate: true, force: force === 'hard'
    };

    if (rightFileRev) {
      if (leftFileRev) {
        diff.leftSha = leftFileRev.fileSha;
        diff.leftType = leftFileRev.type || 'blob';
        if (leftFileRev.baseFileSha !== rightFileRev.baseFileSha) {
          diff.leftBaseSha = leftFileRev.baseFileSha;
          diff.rightBaseSha = rightFileRev.baseFileSha;
        }
      } else {
        // If no rename info is set yet, punt and we'll get called back when it comes in.
        if (rightFileRev.action === 'added' && !rightFileRev.$renamed) return;
        diff.leftSha = rightFileRev.baseFileSha;
        diff.leftType = rightFileRev.type || 'blob';
      }
      diff.rightSha = rightFileRev.fileSha;
      diff.rightType = rightFileRev.type || 'blob';
    } else {
      diff.leftSha = undefined;
      diff.rightSha = undefined;
      diff.leftBaseSha = undefined;
      diff.rightBaseSha = undefined;
      diff.message = {code: 'nofile', level: 'info'};
    }

    var shasMatch = _.isMatch(
      file.$diff, _.pick(diff, 'leftSha', 'rightSha', 'leftBaseSha', 'rightBaseSha'));
    if (!diff) {
      // There's absolutely no way diff should be missing here, but looks like Safari drops it every
      // so often.  This is an attempt at working around the bug by calling diffFile again.  It's
      // not clear if doing so will trigger the same bug again (and cause infinite recursion) or if
      // it'll recover, but it's worth a try.
      Raven.captureMessage('diff object is missing', {extra: {diff}});
      return this.diffFile(file, leftFileRev, rightFileRev, force);
    }
    if (file.$diff && shasMatch && !(
          !file.$diff.working && file.$diff.message &&
          (force === 'hard' || force === 'soft' && file.$diff.message.origin !== 'diff_worker' &&
            !_.isEqual(diff.message, file.$diff.message))
        )) {
      _.extend(file.$diff, {leftFileRev: leftFileRev, rightFileRev: rightFileRev});
      return;
    }

    if (shasMatch && file.$diff && file.$diff.message && (file.$diff.blocks || file.$diff.images)) {
      diff = _.clone(file.$diff);
      delete diff.message;
    }
    file.$diff = diff;
    if (diff.message || diff.blocks || diff.images) {
      file.$diff.working = false;
      file.$viewDiff = diff;
      return;
    }
    // ...
```

**Comment by kballard** [comment] 2016-10-20 20:43
Do you know specifically which line is causing this, or do you know that it's just happening in this general area? The only thing I see that looks like it should be able to cause `diff` to become `undefined` is `diff = _.clone(file.$diff);` (and that's assuming `_.clone` is capable of returning `undefined`), but of course if that was the cause then I'd expect the error to say "evaluating 'delete e.message'" instead of just "evaluating 'e.message'".

All that said, for `diff` to mysteriously become `undefined` at the point where you're checking for it would be a remarkably bizarre bug.

**Comment by pkaminski** [comment] 2016-10-20 20:54
The two expressions that are failing are the `diff.message` accesses -- checked via source map from the exception and confirmed by trawling through the minified code by hand.  The `clone` can't be undefined since `file.$diff` is truthy just above, and in any case one of the failing `diff.message` accesses precedes it.  So yeah, it's remarkably bizarre.  I'm just waiting to see if it repros again after I inserted the workaround.  It would be ironic -- but not unimaginable -- if the workaround in and of itself caused the bug to stop reproducing.

**Comment by kballard** [comment] 2016-10-21 01:39
If it does happen again, but your workaround is successful (i.e the recursive call is ok), is there any way for me to actually know that it happened? I assume that `Raven.captureMessage` call just sends data to you.

**Comment by pkaminski** [comment] 2016-10-21 01:55
Yeah, the captured message will show up in Sentry and I'll get an email the first time it's triggered.  Nothing so far, though.

**Comment by pkaminski** [comment] 2016-10-21 21:49
So the workaround didn't work, in the sense that execution went through the check and still failed in the subsequent `if`.  I'm going to tweak the `try`/`catch` to actually access `diff.message` and see if that works...

**Comment by kballard** [comment] 2016-10-24 18:31
I just opened up my pinned tab for the Reviews page and was presented with the crash again, with a slightly different message:

> TypeError: undefined is not an object (evaluating 'f.message')

**Comment by pkaminski** [comment] 2016-10-24 19:39
That one didn't get captured for some reason, but it's likely an inconsequential variable renaming change in the minified output.

**Comment by kballard** [comment] 2016-10-26 18:49
Now I just got `TypeError: undefined is not an object (evaluating 'b.leftSha')` when clicking "Show Unreviewed Diffs".

**Comment by pkaminski** [comment] 2016-10-26 20:49
Same bug, just a few lines and one stack frame down.  Clearly trying to catch the issue just pushes it around.  I'm about ready to give up -- my last ditch attempt is to stick a try/catch around the whole function and test any exception for `undefined` on Safari only, then try again.  There's a risk of false positives suppressing real errors but I'm out of ideas (other than recommending against using Safari -- it's no longer a Tier A browser).

**Comment by kballard** [comment] 2016-10-27 00:22
I went ahead and filed a [bug report with Apple](https://openradar.appspot.com/28970979) about this.

**Comment by pkaminski** [comment] 2016-11-01 07:52
I haven't seen this exception recur in the last week, so I'm going to tentatively call it "fixed".  My guess is that sticking the try/catch around the whole method defeated whatever buggy optimization Safari was applying.

**Closed by pkaminski** 2016-11-01 07:52 UTC
Labels: bug, osx

**Comment by pkaminski** [comment] 2016-11-02 19:25
I just had @safariqatest trying to load the demo review in Safari 10.1 -- perhaps it's Apple following up on your bug report?  As luck would have it, they got a different crash instead (`TypeError: c.setHost is not a function. (In 'c.setHost(b)', 'c.setHost' is undefined)`) deep inside `angular-animate.js`.  Eyeballing the code it looks like another symptom of the same underlying bug.

**Comment by pkaminski** [comment] 2016-11-04 05:47
Looks like the bug is still present in its original location and my workaround does get around it.  I successfully caught an exception and `diff` was indeed undefined; the recursive call then succeeded (or at least didn't blow the stack -- I have 3 exceptions captured, don't know if they're for different files or for recursive calls).  Anyway, I'm now somewhat confident that you won't see this specific issue again.

**Comment by kballard** [comment] 2016-11-04 05:49
Glad to hear it! Such a bizarre bug though. I hope the Webkit folks can figure it out.
