### ISSUE TITLE
review missing a critical diff

### ISSUE THREAD

**Issue by metajack** [Reviewable/Reviewable#342] opened 2016-06-09 14:22 UTC
I just reviewed https://reviewable.io/reviews/servo/servo/11530 and it was a disaster.

The worst thing was that at some point during the development, a function was added to window.rs. That function was later moved to testbinding.rs. Nowhere in the review did I see code removed from window.rs. I knew it needed to be there, so I had to use github afterwards to verify.

**Comment by pkaminski** [comment] 2016-06-10 20:31
My apologies for the bad experience!  So what happened here is that once the function was removed from `window.rs`, the file was reset back to its base version and hence no longer considered part of the review.  Normally, the file would be concealed in the UI at this point (like `Window.webidl`) but because there were unresolved discussions on the file it got pinned visible.

Furthermore, the first revision after a file reverts to base (r5 in this case) is kept anyway, precisely so that you can see the final diff.  But because of the rebase revision-matching heuristics, you were probably led to compare r5 with r3 (empty diff), and couldn't compare r6 with r4 (final negative diff) because r6 was dropped for `window.rs` due to being same as base.

This is all working as intended but is admittedly not ideal.  I think the right thing to do would be to fill in more "final revisions" if rebase revision-matching heuristics are in effect.  (Another option would be to modify the automatic diff picker to "max out" at the last available revision, but I think that would be harder to get right, since sometimes you actually don't want to offer a diff such as for r5-r7 and r6-r8 for `window.rs`.)

**Comment by nox** [comment] 2016-06-17 01:09
Seems like https://reviewable.io/reviews/servo/servo/11754 is broken too.

**Comment by pkaminski** [comment] 2016-06-17 02:48
Could you be more specific?  Which file(s) and broken in what way?  While the review is set to "review each commit separately", I'm guessing this was picked late in the game because all the commits are aggregated into a single revision.  So whatever the problem is, it's probably different from the one above.

**Comment by cgiroux86** [comment] 2021-04-02 11:45
The preliminary fix for this is now live.  More updates coming soon.

**Closed by cgiroux86** 2021-04-02 11:45 UTC
Labels: bug
