### ISSUE TITLE
PR with 800+ binary files makes Reviewable sooooo slooooow

### ISSUE THREAD

**Issue by elmot** [Reviewable/Reviewable#543] opened 2018-04-13 15:27 UTC
Here it is
https://beta.reviewable.io/reviews/vaadin/framework/10801
Marking any file as reviewed takes tens of seconds, time to time offline screen is shown,
pressing 'n' also takes a lot of time.

**Comment by pkaminski** [comment] 2018-04-14 02:37
Do you have the file matrix open, by any chance?  If so, this is a known limitation of the current Angular-based UI implementation, sorry.  It's unrelated to the binary-ness of files and you can work around it by temporarily closing the file matrix.

If you already have the file matrix closed then I'm unable to reproduce the issue.  Could you try reloading the page with `?debug=digest` appended to the URL and reporting the digest timings from the lower-right corner after trying a few actions?  Thanks.

**Comment by pkaminski** [comment] 2018-04-17 19:07
Thanks.  I'm going to close this as won't fix for now, since the "fix" will actually need to be a rewrite of the UI, which is coming anyway.

**Closed by pkaminski** 2018-04-17 19:07 UTC
Labels: wontfix
