### ISSUE TITLE
Review Per Commit Context

### ISSUE THREAD

**Issue by ericbmerritt** [Reviewable/Reviewable#284] opened 2016-04-08 20:15 UTC
Right now there is no relationship displayed between the revisions and the commits when you do a review on a per commit basis. This makes it very hard to understand changes on a per commit basis. 

The proposed solution is to display all (current? current and past?) commits in the Changes box, indicate which revisions correspond to each commit (using the rebased-commit matching heuristic), and show which commit(s) is/are being reviewed right now.

This is strongly related to #186 and #228.

For bonus points, take advantage of the `Change-Id` commit message tag that can be automatically inserted by a Gerrit commit hook to match up commits.

**Comment by pkaminski** [comment] 2016-04-11 03:40
Moving Gitter transcript to comment so that issue description can hold a summary:

ericbmerritt
10:49
@pkaminski on the review per commit stuff. You guys are showing comments on completely unrelated commits in a diff. You can get to the right commit by clicking on the upper right of the comment, but showing the comment in a diff that it has nothing to do with is really, really confusing
ericbmerritt
11:06
the review individual commits problem is getting bad enough that reviewable.io may not be usable to us
sorry ,review each commit seperately
pkaminski
12:14
@ericbmerritt We show all comments in every diff by design. This way, you don't need to go hunting around a (possibly very high) number of commits to find outstanding comments. The corner label does show which revision the comment was made on, and the color indicates the quality of the mapping -- if it's red, the mapping is poor and you may want to click on it to see it in the original context.
ericbmerritt
12:15
So when I am reviewing a commit, the only comments that are relevant are the comments for that commit. I am reviewing commit by commit.
pkaminski
12:17
That said, comment visibility management is something that's overdue for some improvements. There are other related issues like Reviewable/Reviewable#136, Reviewable/Reviewable#94, and revealing all resolved discussions. I haven't yet crystallized a new feature design to address all this, though...
ericbmerritt
12:17
if you absolutely must show irrelevent comments that have nothing to do with the diff I am looking at, then don't put them in the diff. put a list of unresolved comments at the top or somethig
pkaminski
12:17
Are you talking from the perspective of the reviewer?
ericbmerritt
12:17
or from the prospective of the author. The same rule applies.
if the focus is on a commit, then the only thing that is relevant is that commit. Otherwise I would review the entire thing together.
reviewable has been awesome up to this point. the fact that reviews commit by commit are so problematic when everything else was so awesome was a shock
pkaminski
12:19
What should happen for follow-up commits? Should comments migrate to the "matching" commit?
ericbmerritt
12:21
I don't think so. That would be super hard I suspect. For us, we almost always just update the commit that needs fixing. we use interactive rebasing extensively. For folks that add new commits I am not actually sure to tell you the truth. Thats not a model I have ever used. Though I suspect its common
pkaminski
12:22
Even rebasing creates new revisions in Reviewable, since revisions are immutable. Would you want comments to migrate across "matching" revisions? (With the huge caveat that it's impossible to reliably match rebased commits -- the best I can do is a heuristic based on commit messages.)
pkaminski
12:27
Also, in your experience, do the "misplaced" comments consistently have a red corner label? i.e., if I had an option to hide the red-location comments, would that be sufficient?
ericbmerritt
12:29
They do. When you click on them it takes you to the correct place. However, its very hard to know where you are since there is no context. Nothing really shows you where you are in relation to the current review.
Hmm, in the best case the commit would migrate to the new matching commit.
now defining 'matching' given the problem is hard. I could think of a few heuristics but they wouldn't work all the time
pkaminski
12:31
Let me put the question another way: did you spot any comments that weren't red-located, but you still didn't want them to show up?
ericbmerritt
12:31
hmm, I am not sure. Let me go back and look
ericbmerritt
12:36
Ah, I begin to see whats happening. The comment is in the left hand side of the diff. and its no longer relevant because the author cleaned things up. So the comment needs to be closed.
I think it was confusing to me because I had no idea what context I was in, What commit I was reviewing.
I think :pensive:
for example, in the current review there are 4 commits.
when I got to the review in reviewable, I have no idea which commit I am reviewing. I think its the first commit. If I click the changes drop down. I can at least see the commit I am in but I don't know how that commit sits in relation to the others.
I suspect that is the actual source of confusion.
zgraggen
12:39
I still haven't figured out how to know which commit I'm currently reviewing after selecting review each comimt seperately
ericbmerritt
12:39
At the bottom of the changes drop down, you can see the name of the commit
you are in
@pkaminski @zgraggen and I working on a review and having the problems I described. I called him over here to help with the explainations
pkaminski
12:40
Can you expand on "how that commit sits in relation to the others"?
ericbmerritt
12:41
in the current PR, there are 4 commits. Lets call the A, B, C, and D. D is the HEAD of the review. The chain from most recent to least recent is D -> C -> B -> A
if I am currently reviewing the oldest (A), Then I know I have three more commits to review.
when I move to B, I am on the second of 4, when I move to C, the third of 4 etc
its helpful to both see the name and where I am in the complete review
pkaminski
12:44
Do you basically want to see the header of the file matrix?
ericbmerritt
12:44
I am not sure what you mean by the header of the file matrix
pkaminski
12:45
blob
zgraggen
12:46
What would help is to have some indicator for the different commits like you have for the different revisions. Which commit am I currently looking at how many more commits are there
ericbmerritt
12:47
@zgraggen has the right of it. It would be nice to see the current commit that we are on along with the file matrix and maybe better, the list of commits under review along with an indicator of which commit is currently being reviewed
and clickable so I can move between them
zgraggen
12:49
yes. if I'm not mistaken you currently map commits to revisions r1-rx. however there is no way for me to tell that r3 is the 2nd commit.
ericbmerritt
12:50
you know, I don't think the file matrix is per commit.
zgraggen
12:50
yeah, a file matrix per commit would also be helpfull that way the diff between the revisions would actually make sense
pkaminski
12:53
If you're in "review each commit" mode, then the relationship between commits and revisions is one-to-one and onto, barring exceptional circumstances. So yes, you'll have exactly one revision for each commit.
Not sure what you mean by "file matrix per commit".
ericbmerritt
12:54
@pkaminski I am not sure I understand that. In a current view we have 8 revisions and 4 commits the revisions are labeled r1-r8. How do those relate to commits?
pkaminski
12:55
I can probably turn the current-commit line in the Changes dropdown into a list of all the commits with current indicator pretty easily, when in review-each-commit mode. I need to consider corner cases, though, since you can switch modes at any time and might end up with multi-commit revisions anyway.
The revisions represent all commits that were ever reviewed, even if rebased away. But the relationship is still 1-1.
zgraggen
12:55
So if we have commit A,B,C,D as mentioned before. this maps to R1,R2,R3,R4. now if we made a change to A all commit hash changes. While we still have 4 commits A-D we now have 8 revisions R1-R8
would it be nice if we could select commit A and see R1,R5 (or something along these lines)
ericbmerritt
12:56
I think the big question is how revisions relate to the current commits.
basically what guido just said :smile:
though I think the problem there is relating the revision to the commit
zgraggen
12:58
and by Guido he means me... if that wasn't clear from the context :smile:
pkaminski
12:58
OK, I see. So, a list of the current commits and which revisions correspond to each one, including any heuristically matched rebased revisions.
zgraggen
12:58
well Gerrit solved this problem with a commit-id... while this would be fine for us... that could be a burden for other customers?
ericbmerritt
12:59
yea, that would work, but requires work on the customers part. which may be problematic. As long as it was optional it would probably work and could probably roll into the hueristics
zgraggen
13:03
@pkaminski yes that would be great. Assuming you can get the heuristics right.
pkaminski
13:06
I think the commit-id is secondary -- if the current heuristics prove insufficient, we can add an extra layer later. Do you have a pointer to the Gerrit docs on commit-id, for future reference?
Also trying to figure out how your request may relate to Reviewable/Reviewable#186 and Reviewable/Reviewable#228.
If the commit list worked the way you describe, would that address your concerns with misplaced comments, or would that still be an issue?
ericbmerritt
13:08
https://git.eclipse.org/r/Documentation/user-changeid.html
I think that would. At the very least it would make it easier to understand where tho comments came from and why
I thnk these rquests are all related
pkaminski
13:12
I'm swamped with closing a big contract right now and will need some headspace to synthesize all these requests and figure out the right design. Can I impose on you to open an issue for the commit list so we can track and save the discussion?
ericbmerritt
13:12
of course
pkaminski
13:12
Also, if you want, open an issue for paying attention to the Change-Id line when matching commits. That one sounds really easy to implement, since it's just matching on a portion of the commit message instead of the whole thing, and the existing Gerrit commit hook does all the actual work.

**Comment by jordanlewis** [comment] 2017-11-15 17:29
I would be very interested in seeing something like this get implemented.

My request is to add a text field in between the top-level comments section and the diffs section that contains the text of the commit message of the current revision, if the diff selected represents a commit. Perhaps if the diff selected represents more than one commit, this field could include all of the commit messages. Here is a terrible mockup of my suggestion:

![image](https://user-images.githubusercontent.com/43821/32850553-7d1dff70-ca00-11e7-92a9-952f57a02daf.png)

**Closed** 2020-06-25 04:16 UTC
Labels: enhancement
