### ISSUE TITLE
Commit status pending on GitHub merge snapshot

### ISSUE THREAD

**Issue by marczych** [Reviewable/Reviewable#294] opened 2016-04-22 01:01 UTC
For example:

![image](https://cloud.githubusercontent.com/assets/1094445/14728543/a68abe04-07ea-11e6-9b72-a0d8a5f7b167.png)

That pull had 5 green checks including Reviewable. I then merged the pull (either through GitHub's or Reviewable's UI) and the snapshot that GitHub stores has the Reviewable status as pending. The status on the last commit is green eventually but I'm not sure if it gets switched to pending as the pull is getting merged.

**Comment by pkaminski** [comment] 2016-04-22 09:38
I wasn't able to reproduce this, but based on the theory that it's a race condition between Reviewable's update of the status when the PR changes and GitHub's snapshotting of the checks, I added a 5 second delay on Reviewable's side if the PR is merged or closed.  Can you see if that helps?  Thanks.

**Comment by marczych** [comment] 2016-04-22 16:57
I opened up about a dozen closed pulls and roughly 75% of them had the one pending check. The one pull that has been merged since your fix did _not_ have this problem but it might be a little too early to tell. I'll check back later today when more pulls are merged and let you know.

**Comment by marczych** [comment] 2016-04-22 17:40
I just saw a pull that was merged a few minutes ago and _did_ have the pending Reviewable status check. I'll continue to keep an eye on it but the 5 second delay doesn't appear to have fixed it.

**Comment by pkaminski** [comment] 2016-04-24 00:14
Huh, mysterious.  I added extra logging and tried another approach instead:  don't post a temporary status if the current status is successful and the PR isn't open.  Let's see if this works -- if it doesn't, it means the status change is taking place before the PR gets merged.

**Comment by marczych** [comment] 2016-04-25 17:52
Both of the pulls on this repo that were merged in the last 24 hours exhibited this bad behavior. Here's more information that might help:

The pull was merged at __2016-04-25T17:28:07Z__ based on the `<relative-time ...` element in the HTML and the commit date (__Mon Apr 25 10:28:07 2016 -0700__). Here are the most recent 
commit statuses for the last commit on the branch:

```
{
    "context": "code-review/reviewable",
    "created_at": "2016-04-25T17:28:10Z",
    "creator": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1094445?v=3",
        "events_url": "https://api.github.com/users/marczych/events{/privacy}",
        "followers_url": "https://api.github.com/users/marczych/followers",
        "following_url": "https://api.github.com/users/marczych/following{/other_user}",
        "gists_url": "https://api.github.com/users/marczych/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/marczych",
        "id": 1094445,
        "login": "marczych",
        "organizations_url": "https://api.github.com/users/marczych/orgs",
        "received_events_url": "https://api.github.com/users/marczych/received_events",
        "repos_url": "https://api.github.com/users/marczych/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/marczych/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/marczych/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/marczych"
    },
    "description": "Review complete: all files reviewed, all discussions resolved",
    "id": 538214885,
    "state": "success",
    "target_url": "REDACTED",
    "updated_at": "2016-04-25T17:28:10Z",
    "url": "REDACTED"
},
{
    "context": "code-review/reviewable",
    "created_at": "2016-04-25T17:28:10Z",
    "creator": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1094445?v=3",
        "events_url": "https://api.github.com/users/marczych/events{/privacy}",
        "followers_url": "https://api.github.com/users/marczych/followers",
        "following_url": "https://api.github.com/users/marczych/following{/other_user}",
        "gists_url": "https://api.github.com/users/marczych/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/marczych",
        "id": 1094445,
        "login": "marczych",
        "organizations_url": "https://api.github.com/users/marczych/orgs",
        "received_events_url": "https://api.github.com/users/marczych/received_events",
        "repos_url": "https://api.github.com/users/marczych/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/marczych/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/marczych/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/marczych"
    },
    "description": "Checking review status...",
    "id": 538214881,
    "state": "pending",
    "target_url": "REDACTED",
    "updated_at": "2016-04-25T17:28:10Z",
    "url": "REDACTED"
},
{
    "context": "code-review/reviewable",
    "created_at": "2016-04-25T17:27:58Z",
    "creator": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1094445?v=3",
        "events_url": "https://api.github.com/users/marczych/events{/privacy}",
        "followers_url": "https://api.github.com/users/marczych/followers",
        "following_url": "https://api.github.com/users/marczych/following{/other_user}",
        "gists_url": "https://api.github.com/users/marczych/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/marczych",
        "id": 1094445,
        "login": "marczych",
        "organizations_url": "https://api.github.com/users/marczych/orgs",
        "received_events_url": "https://api.github.com/users/marczych/received_events",
        "repos_url": "https://api.github.com/users/marczych/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/marczych/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/marczych/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/marczych"
    },
    "description": "Review complete: all files reviewed, all discussions resolved",
    "id": 538214555,
    "state": "success",
    "target_url": "REDACTED",
    "updated_at": "2016-04-25T17:27:58Z",
    "url": "REDACTED"
},
{
    "context": "code-review/reviewable",
    "created_at": "2016-04-25T17:27:58Z",
    "creator": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1094445?v=3",
        "events_url": "https://api.github.com/users/marczych/events{/privacy}",
        "followers_url": "https://api.github.com/users/marczych/followers",
        "following_url": "https://api.github.com/users/marczych/following{/other_user}",
        "gists_url": "https://api.github.com/users/marczych/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/marczych",
        "id": 1094445,
        "login": "marczych",
        "organizations_url": "https://api.github.com/users/marczych/orgs",
        "received_events_url": "https://api.github.com/users/marczych/received_events",
        "repos_url": "https://api.github.com/users/marczych/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/marczych/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/marczych/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/marczych"
    },
    "description": "Checking review status...",
    "id": 538214552,
    "state": "pending",
    "target_url": "REDACTED",
    "updated_at": "2016-04-25T17:27:58Z",
    "url": "REDACTED"
},
```

So it looks like the status went from `Pending` to `Success` in rapid succession about 10 seconds before the pull was merged. The same thing happened about 3 seconds __after__ the pull was merged as well. I don't think that this explains it at all...

**Comment by pkaminski** [comment] 2016-04-25 20:04
Could you send the repo name and PR number for the referenced pull to support@reviewable.io?  I'll need it to correlate the data with my logs, and likely to open a case with GitHub support.  Thanks!

**Comment by pkaminski** [comment] 2016-04-26 10:41
OK, I figured it out.  GitHub sends the branch deletion event before the PR merge event, and the update to Reviewable's datastore in turn causes a status check recomputation (because the source branch is part of the info provided to the completion rule) before the review is marked as merged.  I'll change the code soon -- I'm tangled in another complex change at the moment -- to also skip the temporary status if either the source or target branches are missing, which should take care of the issue.

**Comment by marczych** [comment] 2016-04-26 17:06
Oh interesting. Good sleuthing!

> I'll change the code soon -- I'm tangled in another complex change at the moment

No worries. This doesn't affect my workflow at all so there's no rush.

**Comment by pkaminski** [comment] 2016-04-27 10:25
Fix deployed.

**Comment by marczych** [comment] 2016-04-27 18:29
2 of the 3 pulls that have been merged in the last few hours still exhibit this bug. =(

**Comment by pkaminski** [comment] 2016-04-27 20:36
Gah, perhaps there's something else that triggers a re-evaluation just before the merge.  I've improved the instrumentation further; could you please send over the coordinates of the next PR where you observe the issue?  Thanks.

**Comment by pkaminski** [comment] 2016-04-28 03:55
Thanks for sending me the latest case.  I can't really make sense of this one:  the PR was merged at 2016-04-27T23:24:33Z, but the last status change (to pending and back to success) was at 2016-04-27T23:24:14Z, a good 19 seconds earlier so it's not likely to be a race condition.

I wonder if GitHub "snapshots" the statuses by timestamp with 1 second precision and ends up picking the wrong status if it was set and reset in the same second, but the correct one if they happen to straddle a second mark?  I'll get in touch with GitHub support, but would be interested if you could send me a reference to a PR or two that *don't* exhibit this problem to test my hypothesis.  Thanks!

**Comment by marczych** [comment] 2016-04-28 17:21
Having written queries that suffered from similar timing bugs myself, that sounds like a good explanation to me. Pull numbers 2800, 2799, 2794, and 2793 on the same repository do _not_ exhibit this bug so hopefully you can glean some useful information from them.

**Comment by pkaminski** [comment] 2016-04-28 20:08
The PRs above are consistent with my hypothesis and GitHub supports has conceded that there may be a bug on their side.  Their engineers are investigating -- I'll give them a few days, and if no solution is forthcoming I'll add an artificial delay in Reviewable to reduce the chances of this happening.  Thanks for helping me figure this out!

**Comment by pkaminski** [comment] 2016-05-02 16:23
GitHub says they've fixed it from their end.  Please let me know if you spot the issue again!

**Closed by pkaminski** 2016-05-02 16:23 UTC
Labels: bug

**Comment by marczych** [comment] 2016-05-02 19:19
Yep, everything looks good now - even pulls that used to be incorrect! Thanks for all the help and escalating this issue to GitHub!
