### ISSUE TITLE
"Following" disposition is treated as blocking, but does not appear as blocking to the reviewer

### ISSUE THREAD

**Issue by brendanwalters** [Reviewable/Reviewable#896] opened 2022-02-08 01:06 UTC
Commenting in a line-comment chain with disposition "following" (marked with '...') is defined by the status tooltip as "neutral on resolving" and doesn't appear in anyone's "to reply" or "unresolved" lists . . . but is interpreted as "change requested" in the overall status ring / on github and blocks merge.

This disposition should probably be non-blocking as the tooltip states, but if that is not feasible, the tooltip and "unresolved" lists should be corrected to explain it and make it findable. Currently, the reviewer in question must individually open and check all resolved discussions to find and switch all "following" to "satisfied" disposition, which is painful in a large PR.

**Comment by pkaminski** [comment] 2022-02-08 05:35
Hmm, something doesn't jibe here...  Can you point to an example (public or private) of a discussion in this broken state?  If not, can you recall what was the disposition of all the participants in such a discussion?

One thing to keep in mind is that while a Following disposition won't prevent resolution, it also won't assist it:  there must be at least one Satisfied participant in the discussion no matter what.  For example, a two participant discussion with dispositions Discussing and Following will not be resolved by design.

**Comment by pkaminski** [comment] 2022-03-28 03:22
Ping -- need more details.

**Comment by pkaminski** [comment] 2022-04-15 00:34
Closing due to lack of details, but happy to reopen on follow-up.

**Closed by pkaminski** 2022-04-15 00:34 UTC
Labels: invalid
