### ISSUE TITLE
CTRL+V doesn’t paste, moves focus, and cause letter V to do the same

### ISSUE THREAD

**Issue by SimonSapin** [Reviewable/Reviewable#235] opened 2016-01-16 09:06 UTC
In Firefox 43.0.1, on a review page like https://reviewable.io/reviews/servo/servo/9333

1. Click on a comment box to give it focus. The cursor blinks as expected.
2. Type some letters. Text is inserted in the comment box as expected.
3. Type CTRL+V to "paste". What’s expected is that whatever is in the "clipboard" is inserted in the comment box. What happens instead is that the comment box loses focus. (The blinking cursor disappears, and typing further does not insert text anywhere.)
4. Click on the comment box to give it focus again.
5. Now, this comment box is in a "broken" state where not only CTRL+V doesn’t paste (see 3.) but even typing the V key (without any modifier) makes the box lose focus instead inserting the letter V.

This "broken state" is local. After this, I can click on another comment box and insert the letter V (until I try to paste into that one.) This is specific to V, any other letter is inserted as expected.

**Comment by pkaminski** [comment] 2016-01-16 09:24
Which operating system?

**Comment by SimonSapin** [comment] 2016-01-16 10:29
Archlinux x86_64, running GNOME 3 with X11.

**Comment by pkaminski** [comment] 2016-01-16 10:37
Thanks, reproduced on Linux.  This is caused by the workaround needed on Firefox to support pasting images into comments.  I'll either find a way to fix it, or disable the feature under Linux.

**Comment by pkaminski** [comment] 2016-02-04 11:12
Per the discussion in layerssss/paste.js#22, after some work the problem is now reproducible only in @SimonSapin's old profile, and not in fresh profiles or on other machines.  Unless we can figure out how to repro it more widely I intend to close this issue as fixed / not reproducible soon.

**Comment by SimonSapin** [comment] 2016-02-04 15:02
Fair enough. The worst part (not being able to type the letter V) is now fixed, and I can paste with middle-click instead of CTRL+V. Feel free to close.

**Comment by pkaminski** [comment] 2016-02-06 08:18
Thanks, closing.

**Closed by pkaminski** 2016-02-06 08:18 UTC
Labels: bug
