### ISSUE TITLE
Wrong number of unreviewed files in My Reviews

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#794] opened 2020-11-12 18:18 UTC
This review is shown to me with “1” (not “1+”) as the number of unreviewed files in My Reviews list. https://reviewable.io/reviews/ridge/tectonic/7767

When I open the review, I see that I have at least 17 files to review.

When the review page is loaded with `?debug=model`:

```
> truss.store.reviews["-MKoXBvcgtx9yC3YBMEh"].files.num
{…}
> JSON.stringify(truss.store.reviews["-MKoXBvcgtx9yC3YBMEh"].files.num)
"{"reviewable":22,"unreviewed":22,"toReview":22,"currentToReview":17,"reviewedByAtLeast":[0],"moreToReviewThanCurrent":true,"description":"22 files to review.","currentDescription":"17 files to review in current diffs.","estimate":false,"visible":22,"invisible":0,"hidden":0,"presented":17,"leftEstimate":"22"}"
```

**Comment by pkaminski** [comment] 2020-11-12 19:32
Can you obtain this debug info from the Reviews list page, without having loaded the individual review page first?  Those are the numbers we really need.  Thanks.

**Comment by feldgendler** [comment] 2020-11-13 18:36
Strange, I thought I had posted this, and then my comment disappeared. Or am I imagining things?

Anyway, the same expression evaluated on My Reviews page:

```
{"reviewable":22,"unreviewed":1,"toReview":1,"currentToReview":0,"reviewedByAtLeast":[21],"moreToReviewThanCurrent":true,"description":"1 file to review.","currentDescription":"1 unreviewed file at latest revision.","estimate":false,"visible":22,"invisible":0,"hidden":0,"presented":0,"leftEstimate":"1"}
```

**Comment by pkaminski** [comment] 2020-11-13 19:38
Thanks -- GitHub moves in mysterious ways, but I didn't see a previous post.  :)  In any case, this is getting pretty interesting...  It looks like you override each and every review with `reviewed: false`, and almost all of those are getting ignored on the dashboard for some reason.  I'll keep digging and see if I can repro, but may need to ask you for more data as well.

**Comment by feldgendler** [comment] 2020-11-13 20:24
Want to see our custom script?

**Comment by pkaminski** [comment] 2020-11-13 21:02
Nah, the data layer insulates how it was produced from the model layer.  If your script isn't _meant_ to mark all the files as unreviewed then that's a separate issue but there's still a bug in the counters computation.

**Comment by feldgendler** [comment] 2020-11-13 21:16
Our script does affect the per-file review marks. But of course the numbers shouldn't be different on the My Reviews page. In our case, the numbers on the individual review page are correct, those on My Reviews are wrong.

**Comment by pkaminski** [comment] 2020-11-15 07:44
I tracked it down -- the root cause was a bad assumption about precedence between the `||` and `+` operators deep in the code, and far away from where unreviewed file counts are computed.  Sigh.  Fixed now -- thanks so much for staying on this and getting me enough information to put together a repro!

**Closed by pkaminski** 2020-11-15 07:44 UTC
Labels: bug

**Comment by feldgendler** [comment] 2020-11-16 14:03
I confirm that my PRs are now listed correctly. Thank you for getting to the bottom of it!
