### ISSUE TITLE
Fixed header for each file only shows "..."

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#174] opened 2015-09-27 15:29 UTC
It used to display the file name, reviewed status, selected revision, etc. It's a lot less useful now.

**Comment by pkaminski** [comment] 2015-09-27 16:18
This sounds like a bug. Could you please point to a sample PR and provide a
screenshot, since this may be dependent on filename and window size? Thanks.

**Comment by jdm** [comment] 2015-09-27 23:32
https://reviewable.io/reviews/servo/servo/7450 shows this for me.
<img width="1352" alt="screen shot 2015-09-27 at 7 32 01 pm" src="https://cloud.githubusercontent.com/assets/27658/10125757/75f2ec56-654e-11e5-8ef2-887e6068222c.png">

**Comment by pkaminski** [comment] 2015-09-28 01:03
Looks like a Firefox bug with `text-overflow: ellipsis`.  CSS sucks.  I'll try to find a workaround...

**Comment by jdm** [comment] 2015-09-28 01:17
Any chance you could file it on https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Layout too? :)

**Comment by pkaminski** [comment] 2015-09-28 07:07
So the issue is that I'm nesting an `inline-block` inside an `inline` element inside the `div` that has `text-overflow: ellipsis` set (see [Plunker repro](http://plnkr.co/edit/2ZxBgn5Jv3Z1l9sarBxD?p=preview)).  When Chrome and Firefox encounter an `inline-block` directly inside the `div`, they both behave the same: they clip the element and ignore the ellipsis directive.  But when the `inline-block` is further nested inside an `inline` element, Chrome continues to treat it the same but Firefox replaces the entire `inline-block` with an ellipsis.  I tried figuring out what the CSS spec says should happen before filing a bug but gave up.  Do you happen to know?

In any case, it's clear I shouldn't nest `inline-block` elements inside `text-overflow: ellipsis`, so I committed a fix and will deploy it later tonight.

**Closed** 2015-09-28 08:55 UTC
Labels: bug
