### ISSUE TITLE
Error after returning to page

### ISSUE THREAD

**Issue by nikicat** [Reviewable/Reviewable#891] opened 2021-12-29 11:51 UTC
Hello, quite often I get this error after switching to Reviewable page after a while.

`Reference.set failed: First argument contains undefined in property 'users.github:329262.state.-MrNFFt6HNuerVcWD5ik.drafts.-Ms0d7RD4yZ6LP5LA5MX.codeblocks.-Ms50M1Y0I0zzPbvbEjC.line'`

If I reload the page it works fine.

**Comment by pkaminski** [comment] 2022-01-03 00:14
Hey @nikicat, apologies for the delay -- holidays and all that. Thanks for bringing this to our attention!  It's definitely a bug but I'm having trouble reproducing it.  I have a hypothesis about the internal state that might lead to these symptoms but getting there would appear to require breaking an invariant and I can't figure out how that's happening.

Would you be able to to report any recent actions when you next run into this issue?  Specifically anything around selecting text, navigating between files, changing diff bounds, creating drafts, etc.  Also, so far it looks like this is only breaking in Firefox -- can yo confirm whether you're in fact using that browser?  Thanks!

**Comment by pkaminski** [comment] 2022-01-04 21:58
I took a guess as to what the issue might be and added a guard to protect against it.  Hopefully this is fixed now -- please let me know if you still see it.  Thanks!

**Closed by pkaminski** 2022-01-04 21:58 UTC
Labels: bug

**Comment by nikicat** [comment] 2022-01-09 12:50
Thank you, @pkaminski, you are right - the issue reproduces only in Firefox. I hope that your fix is working, I will check next week.
