### ISSUE TITLE
Firebase INTERNAL ASSERT FAILED after losing connection

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#409] opened 2016-10-17 23:32 UTC
Right now every time I try and publish my review I lose connection to Firebase. And after waiting a moment while staring at the error view, it switches to showing a crash instead.

> Error: Firebase (2.4.2) INTERNAL ASSERT FAILED: sendRequest call when we're not connected not allowed.

(btw, it appears to not be possible to select this error message, which is kind of annoying)

**Comment by pkaminski** [comment] 2016-10-18 00:26
Sorry about this -- but it's also very interesting.  I had sporadic reports of the assertion failure before but could never find a repro, so the Firebase team declined to prosecute the bug.  It's awesome that you can reproduce it on demand!  (Less awesome for you, I'm sure.)  Could you please:  reload the page, run `Firebase.enableLogging(true)` in the console, attempt to publish, wait until everything settles down, and send me a copy of the console output at support@reviewable.io?  Thanks!

BTW, not sending duplicate GitHub messages is a feature I specifically added to deal somewhat-gracefully with crashes in what should but cannot be an atomic process.  Glad to hear it's working!

Also sorry about disabling selection of the error message -- it'll be fixed in the next release.  I disable selection on everything by default because it interacts badly with dragging diff ranges, then re-enable it on a case-by-case basis.  Obviously I sometimes miss things.  :(

**Comment by kballard** [comment] 2016-10-18 00:34
I'm also getting this frequently when I go to my pinned tab for the Reviews page. I'll try to reproduce with the review right now.

**Comment by kballard** [comment] 2016-10-18 00:36
I sent the log. It was a whopping 654Kb!

**Comment by kballard** [comment] 2016-10-18 01:08
It occurs to me that you might want to know what browser I'm using. Right now I'm using the latest Safari Technology Preview. If it's still happening tomorrow I can try other browsers (but of course if that works I'll lose my reproducible test case).

**Comment by pkaminski** [comment] 2016-10-18 01:13
Great, thanks!  I opened an issue with Firebase so hopefully we'll get a definitive answer soon.

In the meantime, looking through the log my guess is that the Firebase server is dropping the connection due to the large write the app is trying to issue.  It's well within the documented limits, but perhaps nobody told the server about those...  Anyway, would you say this batch of comments is unusually numerous / large?  We can probably work around the issue by temporarily trashing some comments, publishing, then restoring those comments and publishing again.  Still, if you can wait at least until tomorrow, I'd appreciate keeping the repro running in case Firebase support wants to capture more data.

It's also possible that the issue is browser-specific, as it's not clear which side dropped the connection from the log.  I'll poke around a bit, see what I can find about `Failed to send WebSocket frame.`.

And incidentally, it's probably a good thing that Firebase crashes with a bogus assertion failure, otherwise it would probably just keep reopening the connection and trying to send the write forever...

**Comment by pkaminski** [comment] 2016-10-18 04:46
Incidentally, I searched through my exception archives, and while I don't track disconnects (due to an excess of false positives) all but one of the reported "INTERNAL ASSERT FAILED: sendRequest call when we're not connected not allowed" track back to you.  So apparently you're a magnet for this bug for some reason.  (They also all occurred in Safari 9 or 10, but given the above I don't attach much significance to the fact.)

BTW, do you remember seeing a "undefined is not an object (evaluating 'e.message')" crash at some point?  A couple of these track back to you and they're only occurring in Safari 10.  After staring at the code for a long time I'm convinced that this must be a bug in the JIT, since the relevant object is guaranteed to be defined throughout the affected function...  If you see it again I'd be interested in knowing if there was anything unusual that precipitated the error or if it's just random.

**Comment by kballard** [comment] 2016-10-18 17:28
This particular review has 48 drafts and 5 files marked as reviewed. I know I've submitted reviews with at least 50 drafts in the past. If you have a record of this happening on Safari 9 as well, then that wasn't using Safari Technology Preview, so perhaps my usage of that is not relevant.

I do recall seeing "undefined is not an object (evaluating 'e.message')" at least once, though I don't remember the circumstances. I'll let you know if I see it again.

I just tried submitting the review again in the hopes that it was a transient issue on Firebase's side, but it's still crashing. When it does crash, it initially says "Reason: no connection to Firebase, 2 pending writes" (this "2 pending writes" I know I've seen on previous errors too, so it seems to be reliably 2). I don't know if this is at all interesting.

**Comment by kballard** [comment] 2016-10-18 19:27
I had to submit this review now, so I tried other browsers, and what do you know, Safari 10.0 (that ships on macOS Sierra) was able to submit it. So it seems that this problem was only affecting Safari Technology Preview (Safari 10.1), for whatever reason.

**Comment by kballard** [comment] 2016-10-18 19:28
Either that, or the issue requires me to have https://reviewable.io/reviews#- open in another tab (in Safari Technology Preview this is a pinned tab so it's always open, in Safari 10 I had unpinned it so the only thing open in that browser was the PR). But I don't know why that would actually matter, so it probably doesn't.

**Comment by pkaminski** [comment] 2016-10-18 22:58
OK, thanks Kevin, and sorry for all the trouble.  I believe you captured sufficient data for Firebase to analyze and at this point it seems likely that the bug is a regression in Safari 10.1 anyway.  (Multiple tabs are completely independent as far as Firebase is concerned, so unless Safari does something weird with web sockets in that case the number of tabs shouldn't matter.)

I'll keep this bug open at least until the Firebase folks decide what they want to do about it.

**Comment by kballard** [comment] 2016-10-18 23:05
I still regularly go back to my pinned Reviews page and see that it crashed with this error, so it's still reproducible, just not on-demand. And presumably the reviews tab isn't sending huge payloads to Firebase, so there must be something else going on.

**Comment by kballard** [comment] 2016-10-18 23:06
Ok, thanks for looking into this. At this point I guess I'll switch back to Safari 10 as my default browser and wait for a newer version of Safari Technology Preview that hopefully fixes this.

**Comment by pkaminski** [comment] 2016-10-26 20:59
Firebase support hasn't succeeded in reproducing the error and put the issue on ice pending further reports.  Looks like this won't get addressed unless it persists once the new Safari version has shipped.

**Comment by jspiro** [comment] 2017-02-12 10:04
I got this too.
> `Error: Firebase (2.4.2) INTERNAL ASSERT FAILED: sendRequest call when we're not connected not allowed.`

Safari macOS, latest beta. I have 99 comments in a ginormous review of 256 files. My review and comments did get posted to Github. Tried twice. Second publish resulted in an empty comment on github. All comments were posted to github in the first post, but the comments were still drafts in reviewable.

I tried in Chrome and it succeeded. Publishing took about 20 seconds. Comments are no longer drafts. Another empty comment posted to github.

https://reviewable.io/reviews/DotDashPay/odin/241

**Comment by pkaminski** [comment] 2017-02-14 02:43
There was a small burst of this error recently, centered around Feb 9, affecting two users (including @jspiro) on Safari 10.1 and 10.2.  I thought it might have been correlated with a recent [increased latencies issue](https://status.firebase.google.com/incident/Realtime%20Database/17008) in Firebase, but that was on Feb 11.  It also doesn't happen only when publishing so I'm not sure it's related to large writes either.

All this to say, there's still not enough info to resurrect the bug with Firebase support, and it's rare enough that I'm not hopeful it can ever be addressed.  Sorry.  😞

**Comment by jspiro** [comment] 2017-02-16 07:34
Got it again. Seems related to big PRs with lots of comments (~100) and/or Safari websockets. Doesn't happen in Chrome.
<img width="1137" alt="screenshot 2017-02-15 at 11 31 11 pm" src="https://cloud.githubusercontent.com/assets/232896/23011687/31340d98-f3d7-11e6-8301-36f6754dcb4d.png">

**Comment by JCsplash** [comment] 2017-04-18 00:48
We are experiencing the exact same issue with the same errors as you @jspiro . What we realized is that once users upgraded from 10.0 to (10.1, 10.2 or 10.3), the Firebase Update Method could only handle very small amounts of data. If you passed in 100 paths for example to the Firebase Update Method, which was no problem before in the earlier OS version, Firebase would stall for an incredibly long time, giving the error "Failed to Send Websocket Frame". 

We are desperately waiting for Firebase to fix this. Perhaps they can go in to the Firebase Update Method internals and decrease the "chunk size" to accommodate for this issue? Can someone from Firebase help?

**Comment by pkaminski** [comment] 2017-04-18 02:04
I'm pretty sure this is a regression in Safari's websocket implementation.  Unfortunately, the Firebase 2.x SDK line is out of support so Google won't be making any fixes for it.  I'm planning to move Reviewable to the new 3.x series but will need to complete the rewrite of the new data model first (which includes a Firebase isolation layer), and also update a bunch of dependencies and the server at the same time...  The 3.x SDK should either have a workaround for the issue or let me open a bug with Firebase, but I won't be able to make the transition until sometime this summer.

**Comment by JCsplash** [comment] 2017-04-18 06:59
Im using Firebase 3.x SDK and already am in contact with Firebase support about this issue. I'm not here to complain about Reviewable; I'm just trying to find a workaround for the issue and haven't found one yet. There is no way that we are the only ones having this issue in the latest OS version (although most people don't update their smaller versions, which is good!)

**Comment by pkaminski** [comment] 2017-04-18 07:50
Ah, I see -- I misunderstood!  I hope you have better luck than me in having them take a look at the issue.  If I'm extra lucky, they'll get Safari to fix it so I won't have to rush the upgrade to 3.x...  Thanks for chiming in here!

**Comment by JCsplash** [comment] 2017-04-18 08:30
Right hopefully safari gets to it. And just a side note, we upgraded to 3.x. a few months ago in January, primarily because of authentication issues with 2.x and benefits with 3.x (auto-refresh tokens). It wasn't too much of a hassle but definitely some work. However, I don't think it will solve the websocket issue if your on 3.x with the latest safari version as I am. 

What I might have to do as a work around is find a way to downgrade my iOS version/safari version from 10.3.1 back to 10.0.2. Good luck with everything!

**Comment by elliotchance** [comment] 2017-05-03 23:34
I was getting this *a lot*. According to @pkaminski I was the most kicked off person, by far:

![Uploading pasted_image_at_2017_04_28_12_22_pm_720.png…]()

I was not getting the same issue on Chrome. Upgrading to macOS Sierra came with the new Safari (Version 10.0 (12602.1.50.0.10)) and I haven't received the issue since.

I realise that it's not possible for everyone to upgrade their system, but I did work for me.

**Comment by kballard** [comment] 2017-05-04 06:46
I just hit this in Safari 10.1 on macOS 10.12.4. This is the first time I've seen it in a while, but it proves that it's not something that's fixed merely by updating to the latest macOS (though I can believe that it might be greatly reduced).

**Comment by kballard** [comment] 2017-05-09 22:57
I've gotten this a few times since then.

Interestingly, just now I got an error alert showing up *over another error alert*. The new alert just says no connection, but the underlying alert appears to be this same assertion failure.

![screen shot 2017-05-09 at 3 45 21 pm](https://cloud.githubusercontent.com/assets/714/25876150/368e061a-34d0-11e7-8a0e-61666b583945.png)

**Comment by pkaminski** [comment] 2017-05-10 00:13
The overlaid dialogs are due to a missing dependency in the derived data computation code.  I'll fix this instance shortly, but in the longer term the replatforming onto Vue will get rid of this whole category bugs.

**Comment by pkaminski** [comment] 2018-06-03 07:21
I haven't seen this error in ages, so presumably most everybody has upgraded to a version of Safari that's less buggy.  Closing, will reopen if we spot it again.

**Closed by pkaminski** 2018-06-03 07:21 UTC
Labels: blocked, bug, osx
