### ISSUE TITLE
Text selection highlight missing

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#92] opened 2015-05-04 18:12 UTC
Using Firefox nightly on OS X, I don't see any text highlight appear when editing issue text and text is selected.

**Comment by pkaminski** [comment] 2015-05-04 20:03
Do you mean that text selected in a comment input field doesn't show a highlight?  If so, we can't reproduce this.  We tried Firefox 37.0.2 and 40.0a1 (2015-05-04) on OS X 10.10.3, and Firefox 37.0.2 on Windows 7.  Can you provide any more details on what you're seeing happen, including perhaps a screenshot?  Thanks.

**Comment by jdm** [comment] 2015-05-04 20:55
I can reproduce this when I create a new comment on a review, rather than reply to an existing one. Any attempt to select text in the textarea does not show a highlight, but is operated upon as expected if I copy, paste, replace, etc.

**Comment by pkaminski** [comment] 2015-05-04 21:31
Still unable to repro on a brand-new comment, using all the versions mentioned above.  Do you see the same behavior in Firefox 37?  If not, it may be a regression in the nightly that's somehow specific to your environment...

**Comment by pkaminski** [comment] 2015-05-10 18:24
I'm going to close this for now since we can't reproduce it and you only reported it on the Firefox nightly.  Please reopen if you get more details on how to reproduce or you observe it happening in the current Firefox version.  Thanks.

**Closed by pkaminski** 2015-05-10 18:24 UTC

**Comment by pkaminski** [comment] 2015-05-16 07:46
This may actually be a manifestation of #96, though that one affects Chrome but only with keyboard-driven selection.

**Comment by jdm** [comment] 2015-05-16 10:10
I only ever used keyboard selection when reproducing this, so that's entirely possible!
