### ISSUE TITLE
Title in floating top bar doesn't show correct filename

### ISSUE THREAD

**Issue by mdevs5531** [Reviewable/Reviewable#87] opened 2015-04-26 19:00 UTC
Scrolling around for a while in a largish review (30+ files) found the top bar was not showing the correct filename.

The top bar filename would change as I scrolled up or down to a new file, but it was off by an index of 6 in the list, (assume files 0 -> 30), when I looked at file 4, it would show file 10's title.  The titles fixed to each file are still correct however, so there is a moment when the title snaps from scrolling to fixed when it changes to the wrong name.

The carrot in the dropdown file list shows the correct file.

Same offset persists even after scrolling all the way to the top of the page, as soon as file 0's title scrolls into view it starts showing file 6's title.

The top bar filename stays blank when I scroll past the n-6th file.

Toggling the 'seen' state through the top bar toggles the state of the filename shown in the top bar, not the file I am looking at.

No errors visible in console.  Chrome on OS X.

**Comment by pkaminski** [comment] 2015-04-26 19:02
Were there obsolete files in the review perchance?  Or anything else unusual about the list of files?  Is it reproducible consistently for that PR?

**Comment by mdevs5531** [comment] 2015-04-26 19:24
Reloading the page resolved the issue.  Nothing I can tell would be strange about the file list.

**Comment by pkaminski** [comment] 2015-04-26 22:04
I didn't manage to track down the root cause for this, but I changed the filename display to be key-based instead of index-based and stopped using an offset trick, so at worst the bar will end up empty rather than showing the wrong filename.  There's a slight performance penalty but hopefully nothing noticeable.  Closing unless it gets spotted again.

**Closed by pkaminski** 2015-04-26 22:04 UTC
Labels: bug
