### ISSUE TITLE
Review individual commits?

### ISSUE THREAD

**Issue by larsbergstrom** [Reviewable/Reviewable#77] opened 2015-04-16 13:54 UTC
Today, Reviewable squashes all commits together in the UI for review. On Servo, we often have larger PRs broken into individual commits to separate out unrelated changes for easier reviewing (e.g., results of an API refactor separate from adding new functionality). It would be useful to be nice to be able to review those commits individually, which is something we're used to doing from our current review tool (Critic, http://critic.hoppipolla.co.uk/).

CC @saneyuki

**Comment by pkaminski** [comment] 2015-04-16 21:38
Relatively few people have good commit discipline, which is why Reviewable defaults to collapsing them.  However, note that once a revision is snapshotted (by adding a comment, or by having anyone but the author look at it), other commits won't get glommed onto it.  So as long as you're pushing out and reviewing one commit at a time you'll get one revision per commit.

If this is undesirable (you want to work on a series of commits at once, but review them individually), would you be willing to add some kind of marker (like "FOR REVIEW") into the message of every commit you'd like to be treated separately?  If so, I could easily have Reviewable look for those markers, and break up the commit stream at those points.  (Subject to a safety limitation of no more than 10 revisions per push, which should be plenty but could also be raised a bit if necessary.)  What do you think?

**Comment by larsbergstrom** [comment] 2015-04-17 14:58
Hrm, that's completely the opposite of Servo, where we force everyone to have good commit discipline, including asking people to break up PRs into multiple commits for multiple changes. The only time that we have extra commits are when people generate fixup! or squash! commits (via `git commit --fixup` or `--squash`) to keep items addressing requested changes separate during a review, but with the expectation that they will be autosquashed before merging.

Is it maybe a default that we could toggle per-repo?

**Comment by Manishearth** [comment] 2015-04-17 20:52
FWIW the `--fixup` workflow isn't necessary for Servo anymore* so we probably want one revision per commit in all cases.


*It was a remnant of using a review system that didn't understand `commit --amend`

**Comment by pkaminski** [comment] 2015-04-17 21:27
This is fairly easy to implement so let's give it a try as a manual one-off customization first, and if it proves effective and popular I'll consider adding a self-serve UI for the setting.  Which repos would you like to switch over to one-revision-per-commit mode?  And what's the maximum number of commits you expect to push between review cycles?  (The default max is 10, and it's needed to prevent DoS due to huge branches.  If the number of commits exceeds this then they'll be force-collapsed down to a single revision.)

**Comment by Manishearth** [comment] 2015-04-17 21:31
Right now we're using Reviewable for http://github.com/servo/servo/ . We may use it for the other repos under the same org in the future, but for now enabling it on Servo's repo should be enough.

I can't recall any situations where we've had more than 10 commits aside from in the initial PR (before additional pushes), and even those cases are rare.

Thoughts, @larsbergstrom ?


Thanks for doing this! :)

**Comment by pkaminski** [comment] 2015-04-17 22:15
This is now live for `servo/servo`, but not retroactive.  I'll leave this issue open to get feedback on how well it's working for you guys.  Tweaking the max number of commits per push doesn't require code changes, so just let me know if it needs a bump.  (The max applies to all pushes, including the initial one.)

**Comment by pkaminski** [comment] 2015-04-24 18:26
Has this been working OK for you guys?  @Manishearth @larsbergstrom

**Comment by larsbergstrom** [comment] 2015-04-24 18:55
@pkaminski We're planning to chat early next week (Monday, 5PM Pacific) at our team meeting about how Reviewable is going and I'll definitely ask about this feature, too!

**Comment by jdm** [comment] 2015-04-24 19:03
I'm not sure that we've reviewed any new PRs that were opened with multiple commits yet.

**Comment by Manishearth** [comment] 2015-04-25 14:10
One thing I noticed was that there is no way to only pick the diff of one or more revisions. Or at least, I haven't figured outhow to do this.

For example, if I click on "r1" and drag to "r2", for files which were not modified in r1-r2, the selection is _expanded_, so changes are still shown for these files, outside of the commit made. This makes it harder to review commit by commit.

**Comment by jdm** [comment] 2015-04-25 14:19
Yes, using https://reviewable.io/reviews/servo/servo/5839 as an example, I have not yet figured out how I can review an individual commit in isolation.

**Comment by pkaminski** [comment] 2015-04-25 17:35
That's a good point, but what's the expected behavior if you select a revision range where the file wasn't in the PR at one of the bounds?  (Note that I can't simply take the file out of the view altogether, since any discussions in the file still need to be displayed.)

**Comment by Manishearth** [comment] 2015-04-25 18:05
Perhaps have a toggle to hide such files? There are two stages, reviewing and addressing comments. One seldom needs to see comments all over the place whilst reviewing.

**Comment by jdm** [comment] 2015-04-25 20:15
Add a transparent grey overlay that precludes leaving comments? Make the whole file view collapsed with an option to expand it? *shrug*

**Comment by pkaminski** [comment] 2015-04-26 07:53
I tweaked the bulk bounds selection algorithm to allow for files not present in the PR at the targeted revs to enter a "no diff selected" state.  This should allow you to do a commit-by-commit review -- I tested it quickly on the review linked above.  Bounds selection is pretty tricky code though, so it's possible that the change broke some other case; please be on the lookout for weird behavior.  Thanks!

**Comment by Manishearth** [comment] 2015-04-26 07:54
This is nice, thanks!

**Comment by jdm** [comment] 2015-04-26 13:07
I haven't figured out how to make use of your new changes yet - when I click individual r1/r2/etc. headers, it still only moves the the leftmost bound. What am I missing?

**Comment by Manishearth** [comment] 2015-04-26 13:22
Click and drag

**Comment by mmlb** [comment] 2015-05-14 16:00
+1 to this, I was just thinking about this last night and would love this option in my commits.

**Comment by pkaminski** [comment] 2015-05-14 19:32
@mmlb At the moment, this option can only be set for an entire repo.  Is that sufficient for you, or do you need to control it per-review?  If per-repo is enough, I can set it for you manually so you can try it out.

**Comment by mmlb** [comment] 2015-05-14 19:46
hmmm let me present to team members, ideally per-review would be great while testing it out.

**Comment by pkaminski** [comment] 2015-05-14 19:50
Per-review gets tricky, since once a revision is captured it's immutable.  So you'd need to remember to enable per-commit semantics for a review before the first capture, or I'd need to implement some kind of rule engine to decide which review gets which treatment.

For the record, can you say why you'd like one-revision-per-commit semantics?

**Comment by mmlb** [comment] 2015-05-14 19:52
It's pretty much the same reasoning as OP. I like the rebase/logical commits workflow and really prefer to see the evolution of a PR so that my understanding of the changes can follow. Seeing the final state can be overwhelming.

**Comment by mmlb** [comment] 2015-05-15 14:53
@pkaminski No, repo wide switch is not wanted right now. I would be very interested per-review/configurable-somehow.

**Comment by pkaminski** [comment] 2015-05-15 16:57
Two things I can offer fairly easily:  a per-PR flag, in the form of a
well-known label (e.g., +(review each commit)), or a per-commit flag in the
commit description (e.g., [for review]).  Those would be aimed more at the
author than the reviewer, though, and wouldn't retroactively break up any
captured revisions.  What do you think?

On Fri, May 15, 2015 at 7:53 AM, Manuel Mendez <notifications@github.com>
wrote:

> @pkaminski <https://github.com/pkaminski> No, repo wide switch is not
> wanted right now. I would be very interested
> per-review/configurable-somehow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/77#issuecomment-102420327>
> .
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by jdm** [comment] 2015-05-15 17:13
The label sounds like a more useful solution to me.

**Comment by Manishearth** [comment] 2015-05-15 17:15
Me too. I'm not overly fond of magical invocations that need to be passed through commit messages; since they stick around in the commit history (and can be forgotten when pushing)

**Comment by pkaminski** [comment] 2015-05-15 22:57
OK, if Reviewable finds a "review each commit" label on the PR (case-insensitive, but otherwise must match precisely), it will do its best to assign a separate revision to each commit (while the label is in place).  The usual limitations apply: you can't create more than 10 unsnapshotted revisions at a time, and any previously snapshotted revisions won't be affected by the label.  (A revision is unsnapshotted if it shows up in italics in the file matrix; having anybody but the author visit a review will typically snapshot all current revisions.)

Please let me know how this feature works out for you.

**Comment by Manishearth** [comment] 2015-05-16 05:35
Is the default per-commit thing still enabled for Servo?

**Comment by pkaminski** [comment] 2015-05-16 05:36
Yes, that's still turned on repo-wide for servo/servo, so the label will have no (extra) effect there.

**Comment by Manishearth** [comment] 2015-05-16 05:37
Okay, thanks (I think we want to keep that behavior)

**Comment by mmlb** [comment] 2015-05-18 14:10
great, thanks will try this out.

**Comment by larsbergstrom** [comment] 2015-05-19 00:00
Hrm, is the limit still 10? I noticed that on https://reviewable.io/reviews/servo/servo/6125 the 14 commits have been collapsed into a single revision.

**Comment by pkaminski** [comment] 2015-05-19 00:02
Yes, the limit is still at 10 unsnapshotted revisions by default.  Would you like it raised for servo/servo?  I think up to 20 would still be reasonably safe.

**Comment by larsbergstrom** [comment] 2015-05-19 00:03
@pkaminski If you could, that would be fantastic! I think > 20 would be at a point where I would feel comfortable asking somebody to break it into multiple PRs :-)

**Comment by pkaminski** [comment] 2015-05-19 00:06
NP, it's set at 20 now.  I'm afraid PR 6125 is out of luck, though, since the revision was already snapshotted -- unless you want me to wipe out the whole review so that it can resync from scratch.  Any data put in via Reviewable (comments, marks) would be deleted.

**Comment by larsbergstrom** [comment] 2015-05-19 00:12
@pkaminski That would be great! If it's a burden, I can also ask the author to close it and re-open a new PR.

**Comment by pkaminski** [comment] 2015-05-19 00:25
NP, review reset.  Apologies for the delay in getting it synced again -- the server was thrashing for a bit there.  All better now.

**Comment by larsbergstrom** [comment] 2015-05-22 16:05
This is working really nicely for us! You're welcome to close the issue if you'd like. Thanks again!

**Comment by pkaminski** [comment] 2015-05-22 23:10
Thanks @larsbergstrom.  @mmlb, how's the "review each commit" label working out for you?

**Comment by mmlb** [comment] 2015-06-02 19:25
@pkaminski Can't say yet, we've tried it out on a couple of PRs but I don't think they were good matches to compare against reviewable default. They were huge and many renames.

**Comment by pkaminski** [comment] 2015-06-02 20:19
FWIW, renames should now be handled properly, which may help.  Please let me know once you've had a chance to give the feature a good try...

**Comment by pkaminski** [comment] 2015-06-20 23:36
@mmlb Any update on how well the "review each commit" label works for you?

**Comment by carols10cents** [comment] 2015-06-23 14:18
Hi! We're trying out Reviewable at my job, and we do try to encourage good commit practices and I prefer reviewing commit-by-commit. I tried adding a "review each commit" label to a pull request and then visiting the PR in Reviewable for the first time, and I don't see a difference. Do we need something special enabled on the Reviewable side?

**Comment by mmlb** [comment] 2015-06-23 14:59
@carols10cents there's not much difference on the first review except that you should see multiple revisions at the file-matrix at the top of the page. Reviewable still shows final state of PR. You have to hackishly select the files that changed at the review/commit and hide those that did not.

@pkaminski I got through a per-commit review about a week or 2 ago and there were some usability annoyances, should I open up new issues or discuss here or gitter?

**Comment by pkaminski** [comment] 2015-06-23 19:11
@carols10cents You should see one revision (rNN) for each commit in the PR.  If you don't, it's possible that you had more than 10 commits in the PR, exceeding Reviewable's default "max revisions per push" limit (enforced so the server doesn't blow up).  I can raise that for your repos.

@mmlb Good point about the default diff bounds, I'll make those work differently in review-each-commit mode.  I'm also still thinking about #104.  As for other annoyances, please follow up here or open up new issues as you feel appropriate.  Thanks!

**Comment by mmlb** [comment] 2015-06-23 19:28
@pkaminski diff bounds and #104 are 2/4 of my pain points.

3- quicker/easier access to the commit message when reviewing a commit
3a The commit list in https://reviewable.io/reviews/mistifyio/mistify-agent/48 were not in any kind of order I could discern which made 3 more of a pain :/

4- I found that marking each file as reviewed on each commit made sense for me (not sure if this is how you normally intend for "reviewed" to work but it works nice for normal reviews too), but once I was ready to move onto the next commit/review the baseline was still n-2 reviews ago (baseline for previous commit) so I had to manually select n and n-1 commits for the diff. Automatically updating the baseline to last reviewed revision would be nice.

**Comment by pkaminski** [comment] 2015-06-26 06:15
3a was a bug in dealing with commits reordered via an interactive rebase; fixed now, though not retroactively.

I'm considering making "review each commit" into a major mode that changes some of Reviewable's semantics to better accommodate the workflow.  @mmlb, @larsbergstrom et al, would it be fair to say that a review in "review each commit" mode is not complete until every non-noop revision of every file has been marked as reviewed?  The normal logic is that the latest revision of every file needs to be marked.

**Comment by Manishearth** [comment] 2015-06-26 09:59
Well, since Reviewable shows diffs I think marking a range of diffs as reviewed should mark the corresponding commits as reviewed.

But in our workflow we're not too particular about having individual commits reviewed if the final version of the file is reviewed.

**Comment by mmlb** [comment] 2015-06-26 13:04
I like the review each file in each commit flow, I do it in regular reviews also, but it may get tiresome and so I do not think it should be mandatory.

**Comment by pkaminski** [comment] 2015-06-26 21:10
Hmm, OK.  My concern is that not all diffs may get reviewed:  assume a review with 4 revisions (commits) of a file with changes at each revision.  In a "review each commit" flow, you'll always review diffs of adjacent pairs: base-r1, r1-r2, and so on.  Imagine that for some reason you start with the review of r3-r4 and mark the file as reviewed.  At that point, the review is considered complete, even though you haven't actually reviewed the changes in r1..r3.

Another way to prevent this scenario is to show a warning when attempting to mark a revision as reviewed if the diff range doesn't include the base or another revision previously marked as reviewed.  But depending on your exact workflow that could get annoying too: imagine you're reviewing base-r4, then quickly switch to r3-r4 to check something before marking r4 as reviewed.  Reviewable would complain and you'd have to override the warning or switch back to base-r4 before marking.

Thoughts?

**Comment by carols10cents** [comment] 2015-06-26 23:52
I'd personally rather mark each *commit* as having been reviewed rather than each *file*.

**Comment by pkaminski** [comment] 2015-06-27 00:04
> I'd personally rather mark each commit as having been reviewed rather than each file, and a review isn't complete until all its commits have been reviewed.

Marking commits as reviewed is a superset of the file-oriented technique; instead of marking each file as you go, you'd hit the "mark all reviewed" button in the top-left corner of the file matrix when you're done with the whole revision / commit.  (Whether that button should be more accessible is a separate discussion.)

But the "every file at every commit needs to be marked as reviewed" semantics are what I proposed above and it got shot down as too inflexible.

**Comment by pkaminski** [comment] 2015-07-14 18:59
I believe that the latest release addresses all the points brought up by @mmlb and @carols10cents: there's now an explicit "review each commit" mode that you can switch to per-review or per-repo, the UI picks diff bounds smartly and walks you through selecting the next commit's diffs when the previous one is reviewed, it shows you the summary of the commit(s) in the current diffs, and lets you easily mark the entire revision (commit) as reviewed.  The UI also warns you if you're about to mark reviewed changes that aren't shown in the current set of diffs, though you'll never see those if you follow the easy-path workflow, only if you mess with the diff bounds yourself.

As a consequence of these improvements, I'll be removing support for the "review each commit" label very soon -- please use the new UI instead.  Any repos that I previously switched wholesale to review each commit mode will retain the setting, though.

I'm going to close this issue now but please open new ones for follow-ups!

**Closed by pkaminski** 2015-07-14 18:59 UTC
Labels: enhancement

**Comment by mmlb** [comment] 2015-07-15 16:00
:+1: sounds good
