### ISSUE TITLE
Reviewed state fluttering upon completion condition save

### ISSUE THREAD

**Issue by dhbradshaw** [Reviewable/Reviewable#745] opened 2020-06-15 19:38 UTC
Taking this from a gitter post by @marczych

> I'm making some changes to our custom completion condition and I'm seeing some strange behavior. I'm essentially looping over the files with _.each(review.files) and optionally setting _(file.revisions).reject('obsolete').last().reviewed = true and file.group = "Code review not necessary";. The debug output in the editor looks great but the reviewed state when viewing the review after saving appears to go from unreviewed, to reviewed, and back to unreviewed in the span of 0.5-5 seconds (based on the color of the eye changing between red and green).

Enterprise version v2200.3821

**Comment by marczych** [comment] 2020-06-17 17:32
I ended up deploying these changes to production rather than my forked test repo where it appears to be working as intended. I still see the fluttering behavior on my test repo but I think there might be something else strange going on with that because all of the "Basic options" above the completion condition are empty and don't persist if I try to save them. Any suggestions for how to reset my forked repo or figure out what's happening there?

**Comment by pkaminski** [comment] 2020-06-17 19:10
We've had another recent issue with forked repos on GHE (https://github.com/Reviewable/Reviewable/issues/735), but at this point I don't see any evidence that they're related.

Are you saying that the completion code is persisted correctly for the forked repo, but the other settings aren't?  Those are stored in two separate areas in the database, but are otherwise fetched in exactly the same way.  Also, are you saying that the basic options aren't even getting set to their default values, just literally staying blank?  Do you remember if this used to work fine, and if so roughly when it might've broken?  Does it repro if you fork another similar repo?

**Comment by marczych** [comment] 2020-06-17 20:32
I went to take a screenshot of the empty options but of course they were all set now! I'm pretty sure that they were all unset (even the radio buttons) before but I can't confirm that now.

> Are you saying that the completion code is persisted correctly for the forked repo, but the other settings aren't?

Yes. I've noticed this for about a week and tried saving the settings a while back but they did not persist. I didn't really care about the settings so I ignored it. The completion code appeared to save as expected as far as I could tell.

> Also, are you saying that the basic options aren't even getting set to their default values, just literally staying blank?

Yes. Even the radio buttons didn't have any value selected.

> Do you remember if this used to work fine, and if so roughly when it might've broken?

I do not. I first noticed it about a week ago but I hadn't looked at these settings for a few years most likely. Other (existing) forked repos appear to have all of these settings set correctly.

-----

These are some mysterious issues but I'm not really blocked by any of them because it is working as expected in production.

**Comment by pkaminski** [comment] 2020-06-18 01:46
That's quite mysterious indeed.  Assuming that neither GHE nor Reviewable was updated overnight, either the error is transient or it was caused by some other configuration that got changed.  I don't suppose there's a chance that multiple Reviewable instances (e.g., prod and staging) were both running against the same repo by accident?

Since I don't have even the beginning of a hypothesis and the effect has disappeared, I'm going to close this as "freak occurrence" (aka invalid) for now.  Please ping back if you see anything like this again.

**Closed by pkaminski** 2020-06-18 01:46 UTC
Labels: bug, invalid
