### ISSUE TITLE
Status donut seems to not be visible sometimes

### ISSUE THREAD

**Issue by nate-thirdwave** [Reviewable/Reviewable#1093] opened 2023-07-19 15:22 UTC
Recently (in the last few days? approx starting Jul 18, 2023) the status donut seems to not display reliably, particularly when there are outstanding completion conditions still under evaluation.

![image](https://github.com/Reviewable/Reviewable/assets/96086763/8c18f801-a9ef-411d-8872-f0d6ef1e1ab5)

If all conditions are satisfied, the green donut seems to appear, or possibly if the conditions are satisfied while I'm on the page and getting updates? It's not clear what exactly causes the donut to suddenly appear.

**Comment by pkaminski** [comment] 2023-07-20 01:53
Sorry, this was a regression that we noticed just yesterday -- it was caused by race conditions in the animation subsystem and was performance-dependent, which made it harder to spot.  Should be fixed now.

**Closed by pkaminski** 2023-07-20 01:53 UTC
Labels: bug
