### ISSUE TITLE
Warn when leaving a tab with a Publish in-progress

### ISSUE THREAD

**Issue by fahhem** [Reviewable/Reviewable#1064] opened 2023-05-23 23:55 UTC
When a publish, merge, or other action is in-progress, we should add a warning when the tab is attempted to be closed, similar to when other apps have unsaved changes.

**Comment by pkaminski** [comment] 2023-05-24 03:49
We use the standard `beforeunload` hook to do that already, and it works fine in Chrome at least.  Closing as invalid, but we can reopen if it turns out to be a browser-specific issue.

**Comment by pkaminski** [comment] 2023-05-24 17:55
Turns out there was a regression, likely due to browsers changing the rules on how they allow `beforeunload` to be handled.  Will fix.

**Closed** 2023-05-24 18:02 UTC
Labels: bug
