### ISSUE TITLE
Reviews don't load up on fresh /reviews page load 

### ISSUE THREAD

**Issue by cbrwizard** [Reviewable/Reviewable#146] opened 2015-08-07 12:06 UTC
Hey, does anybody also have an issue that when you open https://reviewable.io/reviews page no reviews get displayed, but when you load any other page first (for example this one https://reviewable.io/repositories) and then click on Reviews in the menu - all reviews are displayed correctly?
Tested on Mac Chrome and Firefox , no errors in JS console but I think it is linked with event not firing in JS.

**Comment by pkaminski** [comment] 2015-08-07 18:24
Hey @cbrwizard, does this still happen?  I can't reproduce it, but there appears to have been a mini-outage of GitHub's search API this morning and other people had trouble loading the Reviews page too for a while.

**Comment by dbertram** [comment] 2015-08-10 12:50
I can repro this as well (Windows 10, Chrome stable channel latest).

No errors in the JS console, but navigating to /repositories and then back to /reviews (via the nav bar, not by entering the URL directly) seems to get the list of reviews to load properly.

**Comment by pkaminski** [comment] 2015-08-10 20:51
OK, let's get to the bottom of this:

- When "stuck", is the page completely blank?  If not, can you share a screenshot?
- Do you have the "also show pull requests you're not involved..." option turned on?  If so, does the page load correctly when it's turned off?
- Before loading the page, can you open the Network debugging panel and see if there are any requests "pending" when the page is stuck?

Thanks, and sorry for the extra work I'm asking you to do, but I still can't repro.

**Comment by dbertram** [comment] 2015-08-11 11:39
- not completely blank; has page chrome, just no reviews listed (no errors in console)
![image](https://cloud.githubusercontent.com/assets/864848/9196621/3246a4ca-3ffb-11e5-88bc-5a3e39619bd6.png)
- I don't have the "also show pull requests you're not involved..." option turned on
- attached is the entire page load...looks like maybe the websocket connection is wedged?
![image](https://cloud.githubusercontent.com/assets/864848/9196659/787722d0-3ffb-11e5-9cdf-86f7aca7f6eb.png)

FWIW, multiple hard refreshes (i.e., no browser cache) of /reviews doesn't seem to fix the issue. Even momentarily navigating to /repositories (i.e., I didn't wait for the list of repos to finish loading) and then navigating back to /reviews *does* seem to correct the problem.

These screenshots were taken on Windows 10 Pro running Chrome 44.0.2403.130 m with no proxies/firewalls/etc.

**Comment by pkaminski** [comment] 2015-08-12 08:53
Thanks for all the extra info!  It helped me track down the bug to a race condition in the session resumption code that only surfaced when the user's settings had a specific history of changes.  I believe it should be fixed now -- could you please give it another try and confirm?

**Comment by cbrwizard** [comment] 2015-08-12 11:17
Woah sorry for not responding before!
Yes it is now fixed for me both on Chrome and Firefox, thanks a lot! [:

**Comment by dbertram** [comment] 2015-08-12 12:30
Appears to be fixed for me too (Chrome 44). Thanks for the quick turnaround on this @pkaminski!

**Closed** 2015-08-12 19:55 UTC
Labels: bug
