### ISSUE TITLE
Next and Previous "personally unreviewed file" buttons have stopped working. 

### ISSUE THREAD

**Issue by benbelow** [Reviewable/Reviewable#826] opened 2021-03-24 14:39 UTC
Noticed on my reviews this morning that my custom shortcuts for next and previous personally unreviewed file have stopped working. 

`?` indicates they are still bound correctly, and other shortcuts are working as expected

**Comment by benbelow** [comment] 2021-03-24 14:42
I'm not sure what's changed, but this has started working again after I raised this. Seems to be that after marking my first file as reviewed, it worked out what was up.

Confirmed that this is still happening on another un-started review.

Also interesting is that all files have the following "reviewed status" icon on the page where this isn't working: 
![image](https://user-images.githubusercontent.com/8653532/112329434-1a19dc80-8caf-11eb-8271-5c2d6b31cf40.png)

on the now working one, they all show as red filled indicating unreviewed.

**Comment by pkaminski** [comment] 2021-03-29 14:39
Hey @benbelow, let's focus on the review status issue -- if we resolve that, the shortcut should follow.  (Also note that there's a plan afoot to replace the shortcuts with some better UI in #817.)

I'm not able to reproduce the red-rimmed review state you reported when I create a PR with user A and navigate to its review with user B.  Are you perchance trying to review your own PR?  If not, can you point me to a PR where you observe this misbehavior?  Thanks.

**Comment by benbelow** [comment] 2021-03-29 15:01
I'm afraid the reviews in question are both now closed :( 

I haven't seen this again since the two at the time - it's worth noting they were fairly large as reviews go. I'm not sure if anything else was different to do with how it was raised. 

I'll be on the lookout for this happening again and let you know if/when I see it!

**Comment by pkaminski** [comment] 2021-03-29 16:16
Thanks, and sorry for taking so long to take a look at this.  I'll close this for now but please follow up if it happens again.  Hopefully we'll have #817 implemented before then!

**Closed by pkaminski** 2021-03-29 16:16 UTC
Labels: invalid
