### ISSUE TITLE
"Reviewable" button doesn't appear in github after a new PR

### ISSUE THREAD

**Issue by DamienCassou** [Reviewable/Reviewable#398] opened 2016-09-13 15:18 UTC
We have created several Pull Requests on github today and the Reviewable button didn't appear in the PR pages.

**Comment by pkaminski** [comment] 2016-09-14 03:35
Hi Damien -- sorry for the late response, I was at the GitHub partners conf all day.  Can you let me know which repo this is and one or two of the affected PRs so I can investigate?  Thanks.

**Comment by DamienCassou** [comment] 2016-09-14 07:40
@pkaminski this is a private repo unfortunately.

**Comment by pkaminski** [comment] 2016-09-14 07:51
Can you please send the info to support@reviewable.io instead then? Thanks.

**Comment by DamienCassou** [comment] 2016-09-14 08:53
done

**Comment by pkaminski** [comment] 2016-09-14 21:31
Thanks.  Looks like one of the PRs got the review created by the time I got to it, but the other (test) one didn't.  I haven't found any trace of it in my logs, which is odd.  The simplest answer is that the event wasn't delivered for some reason and GitHub doesn't retry failures.  Next time this happens, can you check in the repo's settings, Webhooks section, Reviewable webhook, Recent Deliveries section if there are any red X's?  (There's not much point in checking now since the list is fairly short, so the events of interest will have scrolled off already.)

I also added more logging earlier in the event handling process so I should be better equipped to debug if it happens again.  Please let me know if it does -- if it's in the same repo, you can just mention the PR numbers here.  Thanks!

**Comment by pkaminski** [comment] 2016-09-20 05:13
Did you see this happening again by any chance?  If not, I'll close the issue for the time being since it could've just been a mis-sent webhook (and I've been asking GitHub to make them more reliable for a while).

**Comment by DamienCassou** [comment] 2016-09-20 07:58
I will reopen if I do.

**Comment by DamienCassou** [comment] 2016-09-20 13:45
Ok, I have the impression that all PRs have the problem: e.g., 1969.

**Comment by pkaminski** [comment] 2016-09-20 21:25
Indeed, looks like there are no reviews after 1951, and no GitHub events received in the last week.  Could you please check a few things for me, as GitHub doesn't let me do it myself:

1.  Is there a webhook set up for the repo targeting `https://reviewable-prod.appspot.com/github`?
2.  If so, are there any failed recent deliveries?
3.  Does the organization have third-party application restrictions turned on?  (Organization settings, third-party access)

You can also try disconnecting and reconnecting the repo at https://reviewable.io/repositories, which might kick up some error that will hint at the root cause.  (This is safe to try -- current reviews won't be affected.)

Thanks.

**Comment by DamienCassou** [comment] 2016-09-21 07:01
Piotr Kaminski <notifications@github.com> writes:
> 1.  Is there a webhook set up for the repo targeting `https://reviewable-prod.appspot.com/github`?

- payload url: https://reviewable-prod.appspot.com/github

- content type: application/json

- events: issues, pull requests, push, issue comment, pull request review
comment, status

- active: not checked (is that normal??). The comment says "We will
  deliver event details when this hook is triggered."

> 2.  If so, are there any failed recent deliveries?

- recent deliveries: none failed, but the last recent is 2016-08-09

> 3. Does the organization have third-party application restrictions
> turned on? (Organization settings, third-party access)

Policy: No restrictions

> You can also try disconnecting and reconnecting the repo at
> https://reviewable.io/repositories, which might kick up some error
> that will hint at the root cause. (This is safe to try -- current
> reviews won't be affected.)

done. When I did that, all deliveries went away and 2 new appeared. The
one today at 08:58:43 is ok. The one ata 08:58:39 fails:

    We couldn’t deliver this payload: Service Timeout 

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by pkaminski** [comment] 2016-09-21 08:17
"Active" being unchecked is definitely not normal!  That would probably explain why nothing was sent since 2016-08-09, but I wonder how the hook got deactivated.  I definitely never touch that field in any of the API calls I make, and it doesn't look like it got deactivated because of excessive delivery errors.

After reconnecting, is "Active" now checked?  If so, I expect things will start working again.

The occasional Service Timeout is not entirely unexpected, as long as it doesn't happen too often.  I was deploying a new version of the Reviewable servers right around that time so it may have contributed to the delay.  But perhaps keep an eye on the deliveries for the next few days to make sure they're mostly successful.

**Comment by DamienCassou** [comment] 2016-09-21 08:32
Piotr Kaminski <notifications@github.com> writes:

> "Active" being unchecked is definitely not normal!  That would probably explain why nothing was sent since 2016-08-09, but I wonder how the hook got deactivated.  I definitely never touch that field in any of the API calls I make, and it doesn't look like it got deactivated because of excessive delivery errors.
>
> After reconnecting, is "Active" now checked?  If so, I expect things will start working again.

"Active" is now checked. Strange.

> The occasional Service Timeout is not entirely unexpected, as long as
> it doesn't happen too often. I was deploying a new version of the
> Reviewable servers right around that time so it may have contributed
> to the delay. But perhaps keep an eye on the deliveries for the next
> few days to make sure they're mostly successful.

thanks

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by pkaminski** [comment] 2016-09-22 00:27
Looks like events are now flowing -- closing.

**Closed by pkaminski** 2016-09-22 00:27 UTC
