### ISSUE TITLE
Cmd-Shift-P shortcut sometimes fails

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#48] opened 2015-02-25 21:36 UTC
I'm sorry I can't be more precise about how to reproduce this, but while going through a review I've noticed that the Cmd-Shift-P shortcut (to toggle Write/Preview panels) sometimes fails to do anything.

I'll let you know if I can get more specific.

**Comment by danvk** [comment] 2015-02-25 21:47
Clicking away & then re-clicking on the "Write" box consistently makes the shortcut work again, so maybe it's something to do with Reviewable's notion of focus. Note: I am writing in the text box when I try to hit Cmd-Shift-P, so it does have focus.

**Comment by pkaminski** [comment] 2015-02-25 22:34
I suspect you're right.  I'm planning to add an external manifestation of comment focus soon (as URL hash), which will make this easier to debug.

**Comment by pkaminski** [comment] 2015-03-06 06:56
We now set the URL hash to the currently focused discussion -- the same as is used by the keyboard shortcut.  Next time you find the shortcut not firing, can you check whether 1) there is a hash in the URL and 2) whether clicking on the discussion changes the hash (i.e., the correct discussion wasn't focused)?  Thanks.

**Comment by danvk** [comment] 2015-03-06 16:51
Just ran into this again.

URL when Cmd-Shift-P not working: https://reviewable.io/reviews/hammerlab/pileup.js/20#-JjjzXlJMTXDJGNXMjUJ

Blurring the text box & re-focusing it did not change the URL.

**Comment by pkaminski** [comment] 2015-03-07 11:33
I reproduced this on my machine, but couldn't figure out the root cause.  I rewrote the focus-tracking code such that I *believe* this should no longer be a problem, so I'll close this issue.  I'll keep an eye out for recurrence, though, and have added a new debug hook that will make it easier to figure out what's going on if it does come back.  Please reopen this issue as well if you run into the bug again...

**Closed by pkaminski** 2015-03-07 11:33 UTC
Labels: bug
