### ISSUE TITLE
Authentication failures in firefox following direct review links

### ISSUE THREAD

**Issue by mkj-pendo** [Reviewable/Reviewable#513] opened 2018-01-10 16:40 UTC
I can go directly to reviewable and authenticate and list my reviews, and I can follow the links in the main page to my reviews. Reloading reviews generally gives me a blank page and forces me to go back to the main reviewable page and back into the individual review. Following a link to reviewable sent from a colleague never, or almost never, works correctly.

My colleagues using firefox are also seeing this behavior. My colleagues using chrome are not. I have tried removing all reviewable and github cookies and running the auth flow again, and it did not resolve the problem.

**Comment by pkaminski** [comment] 2018-01-12 08:06
I tried but couldn't reproduce this issue in Firefox 58.0b10 (64 bit on Windows 10).   What FF version are you running, and on which platform?  Can you confirm that this happens even with all extensions disabled?  Is there anything in the JS console when a page fails to load?  Or any failed requests in the Network panel?  Thanks.

**Comment by mkj-pendo** [comment] 2018-01-12 15:02
I'm using Firefox 57 on Fedora (Linux); @sonyccd is using Firefox 58.0b14 on mac. Nothing in the JS console for me. 1 404 `https://api.github.com/repos/pendo-io/[repository-redacted]/branches/[theBranch]/protection?access_token=[redacted]&per_page=100&_nocache=578414` followed immediately by a 200 to access the master branch of the same repository using the same access token but different nonce.

Haven't had a chance to test without extension yet...

**Comment by sonyccd** [comment] 2018-01-12 15:02
Name | Firefox
-- | --
58.0b14
20180103230655
Show Update History
beta
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
Darwin 17.3.0
about:plugins
about:buildconfig
about:memory
about:performance
about:serviceworkers
1/1 (Enabled by default)
4/4
content = true (enabled by default), chrome = false (disabled by default)
Found
Found
false
about:profiles

**Comment by pkaminski** [comment] 2018-01-12 21:47
I tried on FF 58.0b15 on OS X 10.12.5 and was still unable to reproduce.  I tried reloading a review page, opening a new tab and pasting in a review URL, and opening a review link saved to the desktop -- all consistently work fine.

It's weird that you report those two requests being issued (the 404 is expected) since it indicates that you're signed in and Reviewable is up and running in the browser.  Could you check what's in the Elements tree when you're in that state, and whether something is forcing the page body's display off for some reason?

Is there any pattern to when a page loads successfully or not?  Perhaps timing, other Reviewable pages open, etc.  Should probably also try without extensions -- especially any kind of blockers -- just in case.

Finally, could you try to see if you have the same problem on beta.reviewable.io?  That version is still somewhat buggy and still uses Angular, but has major changes to the bootstrap and sign-in code so I'm wondering if it'll behave the same or not.  Thanks.

**Comment by sonyccd** [comment] 2018-01-12 22:11
What I am seeing that the top of the DOM has a style=display: none; that is not going away. If I remove it the page appears to not have loaded all the content and does not display correctly.

**Comment by pkaminski** [comment] 2018-01-12 22:40
Is that style from a stylesheet / class, or is it set directly?  Is it on the `html` element or the `body`?  Is there a `display: none` also set on the `#static-home` `div`?  (Sorry for the debugging by proxy, but as I can't repro it's the best I can do...  😞)

There's a small inline script that runs synchronously and is supposed to hide the contents of the (static) home page if you're not, in fact, loading the home page.  It does this by looking for the last `script` on the page and hiding its parent.  If for some reason this finds a different `script` element whose parent is the `body` then it would explain why you can only consistently load the home page...

It's not yet clear why that might be happening, though, unless FF doesn't run the script synchronously while parsing the page.  I also don't understand why the page doesn't display correctly if the style is removed, since any error in bootstrap should be reported to the console and/or my exception collector. 
 If this hypothesis is correct then https://beta.reviewable.io should have the same buggy behavior, since I didn't change this bit.

I wonder if there's a recent regression in FF's [speculative DOM construction](https://hacks.mozilla.org/2017/09/building-the-dom-faster-speculative-parsing-async-defer-and-preload/) code.

**Comment by pkaminski** [comment] 2018-01-18 08:33
Hey guys, any more data on the issue?  Or did the problem go away on its own by any chance?  Thanks.

**Comment by mkj-pendo** [comment] 2018-02-23 16:47
It didn't go away on its own; just didn't get to trying it without extensions loaded so didn't have new data.

**Comment by pkaminski** [comment] 2018-03-08 08:50
Closing pending further information.

**Closed by pkaminski** 2018-03-08 08:50 UTC
Labels: blocked
