### ISSUE TITLE
Icons don't have titles or titles to help guide the user

### ISSUE THREAD

**Issue by AutomatedTester** [Reviewable/Reviewable#132] opened 2015-07-21 13:19 UTC
The icons are not obvious to me so I hovered over them to see what the alt/title was and there is none. I suspect that a full a11y audit might be required

![fullscreen_7_21_15__2_16_pm](https://cloud.githubusercontent.com/assets/128518/8801518/483aa482-2fb3-11e5-924f-f3dbd51226ae.jpg)

**Comment by pkaminski** [comment] 2015-07-21 20:27
Yes, this is a major issue captured in #53 and I'm working on it now.  As mentioned in #53, I'm not a fan of `title` attributes so I'm putting in place a custom system instead.  I agree that all icons should have `alt` attributes -- I'll do that at the same time.  Closing this issue as duplicate of #53.

**Closed by pkaminski** 2015-07-21 20:27 UTC
Labels: duplicate
