### ISSUE TITLE
Crazy scrolling while trying to type comment

### ISSUE THREAD

**Issue by AndyIsaacson** [Reviewable/Reviewable#148] opened 2015-08-17 17:42 UTC
I was trying to leave a new comment on a busy code review, and while I was typing, the page kept scrolling up or down and then snapping back.  Incredibly distracting!  I'm not quite sure what the circumstances were around it.

I'm on Chrome 44.0.2403.130 on Mac

**Comment by pkaminski** [comment] 2015-08-17 19:48
Hey Andy, sorry about that. Can you give me a link to the review? Also, do
you know if all the files had finished diffing before you started typing
your comment, and did the scrolling subside after 20-30 seconds? Thanks,
that'll help me figure it out.

**Comment by AndyIsaacson** [comment] 2015-08-17 21:23
Hey Piotr,

Link is here: https://reviewable.io/reviews/udacity/udacity/6199 

Not sure about the diffing, but it was definitely quite a while after opening the review (maybe 20-30s?)  The scrolling didn't subside as far as I could tell.  In fact, when I clicked into a different line to add a new comment, it started anew there.

Good luck!

**Comment by pkaminski** [comment] 2015-08-17 21:31
Hey Andy, a few more questions as I try to narrow things down:

- Was the review in single-file mode at the time?  (It should automatically go into single-file mode if there's more than 25 files, but it's possible to override it.)
- Do you know if other people were sending/publishing comments at the same time?  (Is that what you meant by "busy review"?)
- Are you able to reproduce this, by any chance?  If so, only on this review or on other reviews too?

Thanks again.

**Comment by AndyIsaacson** [comment] 2015-08-17 22:26
I don't think it was single-file mode.  It's totally possible that other people were publishing comments at the same time, though I don't know for sure (could you check the timestamps on those?  I published not long after starting writing).  

I just tried again with the same review, and I didn't experience the issue.  I could see the scroll bar jumping around a good bit, but the viewport remained in place.

**Comment by pkaminski** [comment] 2015-08-21 23:05
Hey @AndyIsaacson, was the page scrolling up-and-down, or was it the side-to-side transition when you switch diff bounds?  I just fixed a bug that caused such a transition on essentially every keystroke typed into a draft, under very specific circumstances (which would explain the lack of repro).  Does that sound like it fits?

**Comment by AndyIsaacson** [comment] 2015-08-21 23:21
Hey Piotr,

It was definitely up and down, and if I recall, wasn't strictly up or down.
Sorry for the frustrating bug... Wish I had more for you to go on for a
repro.

Cheers,
--Andy

**Comment by pkaminski** [comment] 2015-08-22 20:42
Hmm, actually, because it was only jumping while you were typing I *think* it's another manifestation of the same bug I just fixed.  I bet further up the page some other diffs were cycling, causing the layout to jump.  Since I have no other suspect, I'm going to close this bug for now but please reopen if it happens again!

**Closed by pkaminski** 2015-08-22 20:42 UTC
Labels: bug
