### ISSUE TITLE
404 when opening reviews

### ISSUE THREAD

**Issue by tschneidereit** [Reviewable/Reviewable#184] opened 2015-10-16 09:53 UTC
Reviewable returns a 404 for all reviews. Example I tried: https://reviewable.io/reviews/servo/servo/8039. The reviews dashboard works, otoh.

**Comment by aztlan2k** [comment] 2015-10-16 16:06
yep.  same for me.  I can get to the review by going to the home page... which redirects to the dashboard where i can load a review.  If i hit refresh though, i get 404.  very strange.

![image](https://cloud.githubusercontent.com/assets/4225823/10546813/f4134170-73f5-11e5-82c5-bced77e08200.png)

**Comment by pkaminski** [comment] 2015-10-16 17:48
Sorry, on it.

**Comment by pkaminski** [comment] 2015-10-16 18:03
This is fixed now -- my profuse apologies.  I'm going to go shout at Firebase for a bit then come back here with a post-mortem once I know what happened.

**Closed by pkaminski** 2015-10-16 18:03 UTC

**Comment by aztlan2k** [comment] 2015-10-16 19:13
thanx @pkaminski

**Comment by pkaminski** [comment] 2015-10-18 04:17
Herewith the promised post-mortem:

Reviewable is [hosted on Firebase](https://www.firebase.com/hosting.html) and declares a rewrite rule that serves all URLs from the same root `index.html` file:
```json
  "rewrites": [
    {
      "source": "**",
      "destination": "/index.html"
    }
  ],
```

On Thursday night I switched the continuous deployment build script to the newly released [firebase-tools](https://www.npmjs.com/package/firebase-tools) 2.0.1 and deployed the site.  Everything seemed to go well and the deployment reported success.  I thought that I had checked a review page and the dashboard after the deployment, but in retrospect I probably got a "something is better than nothing" cached copy from the CDN (even though it had expired).

On Friday morning, I started receiving reports that pages other than the home page were serving 404's.  The site was still usable if you came in through the home page since, once loaded, all routing is done internally via `pushState`.  I quickly reverted to the 1.x version of firebase-tools and redeployed the site, which fixed the problem.

The root cause is a bug if firebase-tools 2.0.1 that causes it to ignore the `rewrites` section of the config file when a completely unrelated command line flag is used.  The Firebase team will be fixing this bug (and hopefully adding a test!) and releasing a new version soon, at which time I'll (very carefully) try to upgrade again.

A secondary issue is that my automated monitoring failed to detect the problem and alert me.  I had only set up an HTTP probe on the root URL, which of course was serving fine.  I have now added a second probe on the demo review page so I'll be paged within 10 minutes if something similar happens in the future.  Unfortunately, other pages (dashboard, repositories) require a user to be signed in, and due to the way Reviewable's authorization is implemented I don't see how to fake that from the monitoring system.

I'd also like to set up a "trusted user critical alerting system", where a dozen or so regular users (ideally distributed across timezones) will get access to a special email address that will also trigger my pager, day or night.  If you've read this far you probably qualify -- let me know at piotr@reviewable.io if you're interested in helping out.  Thanks!

@pbouillet @alinn @dallasgutauckis @wli
