### ISSUE TITLE
Signing doesn't work with Edge

### ISSUE THREAD

**Issue by lanthaler** [Reviewable/Reviewable#581] opened 2018-08-16 20:46 UTC
Signing in with Edge doesn't work. The OAuth dance happens but the status on Reviewable isn't updated.
 Tested with

Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

**Comment by pkaminski** [comment] 2018-08-17 06:35
There turned out to be two regressions, one likely caused by a change in Edge's treatment of cookies and one due to bitrot in the redirect auth code path.  Both fixed now and Edge should be working again -- sorry!

**Closed by pkaminski** 2018-08-17 06:35 UTC
Labels: bug

**Comment by lanthaler** [comment] 2018-08-20 18:27
Thanks, it's working again
