### ISSUE TITLE
Option to disable commit message review

### ISSUE THREAD

**Issue by msagarpatel** [Reviewable/Reviewable#862] opened 2021-08-26 00:17 UTC
Is there a way to disable the new commit-message-review feature? We squash commits, and write our own squash commit messages, so individual commit messages aren't relevant to us.

I wouldn't mind an extra click during review, but since our project requires linear history, we must merge master before squashing. Now, that merge commit needs to be approved as well, and we have to request review again just for the merge commit.

**Comment by msagarpatel** [comment] 2021-09-01 15:35
Hi Piotr,

> In general, if a merge commit touches any files involved in the review, it'll require a re-review.

This makes sense, and I've seen this in action as well.

> If it doesn't, the new commit should get added to the last revision and existing review marks will remain valid. I assume you're talking about the latter scenario? Did this use to work before but now always creates a new revision?

Yes, the existing files remained valid. But, I could have sworn the merge commit was added to the list of commits in Reviewable, and we were blocked from merging until the merge commit's message was reviewed even though none of the reviewed files were touched by the merge commit. I can't find an example right now, but if you can give me another week, and I'll be on the look out for an example, and let you know ASAP.

Thanks!

**Comment by pkaminski** [comment] 2021-09-02 04:10
Thanks -- I reproduced the issue and I'm working on a fix.  I don't *think* it was caused by the commit message review feature, but it doesn't really matter: it's definitely broken.

**Comment by msagarpatel** [comment] 2021-09-02 18:36
I think I have an example: oscarlab/betrfs-private#441. None of the files in the merge commit touched any of the files the PR changes. The PR was reviewed in it's entirety before the merge commit, but the merge commit added a commit message, and now merging is blocked until the commits messages are reviewed.

Please let me know after you're done looking at that PR so I can request a re-review. Take your time, and thanks!

**Comment by pkaminski** [comment] 2021-09-02 18:38
Thanks Sagar -- I have a local repro and will hopefully have a fix by EOD.  You can go ahead and get your PR merged.

**Comment by msagarpatel** [comment] 2021-09-02 18:40
Thank you, Piotr!

**Comment by pkaminski** [comment] 2021-09-05 17:16
FYI, we have a fix in hand but we're taking a bit of extra time to test it for side-effects.  Just trying to make sure it's not one step forward, two steps back!

**Comment by pkaminski** [comment] 2021-09-08 02:37
All right, we deployed the fix.  🤞  Please let us know if it works for you, but note that it's not retroactive.

**Closed by pkaminski** 2021-09-08 02:37 UTC
Labels: bug

**Comment by msagarpatel** [comment] 2021-09-08 04:11
Awesome! Thanks, Piotr! I'll be on the look out, and report back after we've merged a few PRs where this bug previously occurred.

**Comment by msagarpatel** [comment] 2021-09-24 06:01
Hi, Piotr. I am happy to report that the bug appears to be fixed. Thank you for swift response, and quick fix!
