### ISSUE TITLE
Second reviewer is required to react to another reviewer's comment

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#692] opened 2019-10-01 11:47 UTC
Possibly related to #689, although the scenario is different here.

R1: posts a comment with disposition: _discussing_.
Author: hasn't reacted yet
R2 (already involved in the review): sees the discussion as requiring attention. R2's disposition is _following_. The _Resolve_ button is shown. There is no _Mark as read_ ribbon. R2 cannot get rid of the attention-requiring status of the discussion without posting anything on it or clicking _Resolve_.

**Expected result**: there is some kind of action that R2 can take to acknowledge the discussion and clear its attention-requiring status without getting involved.

**Comment by pkaminski** [comment] 2019-10-01 20:24
Something doesn't add up in your scenario:

> R1: posts a comment with disposition: discussing.

Do you mean starts a new discussion where they are the sole participant after publishing?

> Author: hasn't reacted yet
> R2 (already involved in the review): sees the discussion as requiring attention. R2's disposition is following.

A reviewer's default disposition in a new discussion will be "uninvolved".  If you're seeing "following" then it means they already interacted with the discussion in some way.  If you're _not_ seeing the "new comments (mark as read)" ribbon then it's likely that they already acknowledged the comment somehow.

Well, either that or there's some kind of epic disposition bug.  Are you able to reproduce this scenario from scratch?

**Comment by pkaminski** [comment] 2019-10-01 20:24
(For the record, I tried to reproduce using your instructions and couldn't.)

**Comment by feldgendler** [comment] 2019-10-02 09:31
I am R2 in a particular review, and I see myself as _following_ in every discussion between R1 and the author. I swear I didn't touch those discussions.

I do have the button to _Acknowledge_ in most of them though.

**Comment by pkaminski** [comment] 2019-10-02 16:25
That's very surprising.  Could you please point me at a specific discussion or two?  Thanks.

**Comment by feldgendler** [comment] 2019-10-02 18:55
https://reviewable.io/reviews/tectonic-network/tectonic/2296#-Lq2ne2GDo7sdumsegeD
https://reviewable.io/reviews/tectonic-network/tectonic/2296#-Lq60pKv5aa5mvxNbRxA

**Comment by pkaminski** [comment] 2019-10-03 05:12
Thanks -- I was in meetings all day so didn't get to check out the data until now so the discussions may no longer be in their intended states.

For the first one, I show you as "following".  I audited the code for all the spots that might force a "following" disposition and failed to find any possible culprits (unless you're the author of the PR, which you're not in this case).  At this point I can't see any way this could've been set without some action on your part.

For the second discussion, you're set to "discussing", which is a bit weird since you don't have a comment posted.  Again, the only way I could imagine this happening is if you explicitly changed your disposition from the dropdown.

In both cases the disposition change timestamp is odd:  it doesn't correspond (or even fall particularly close) to any comment in the discussion.  I think this indicates that Reviewable didn't set the disposition in response to some event (i.e., on the server), so presumably whatever happened did so in the client.

Do you perchance have shortcut keys assigned to set dispositions?

**Comment by feldgendler** [comment] 2019-10-03 08:45
I don't have the _discussing_ disposition on either of the links above.

Let's concentrate on the first one. There, I'm _following_ (I see the ellipsis icon). I have definitely not set myself to _following_ manually. I've never in my life set this particular disposition manually.

As you can see, I haven't posted anything in that discussion. I might have clicked _Mark as read_ on it at some point in the past, but I think I saw myself as _following_  it already the first time that I ever saw this discussion. 

We are using the default keybindings.

**Comment by pkaminski** [comment] 2019-10-05 04:10
Perhaps you linked to the wrong discussion, but I'm definitely showing you as _discussing_ on `-Lq60pKv5aa5mvxNbRxA` (the other two participants are now both _satisfied_).

Clicking on _Mark as read_ will set your disposition to _following_, as will hitting `y` if the default button is labeled _Acknowledge_.  It's very likely that one of these two things happened but I don't track events at such fine granularity so there's no way to confirm or deny this hypothesis.  All I can tell you is when the disposition change was effectuated (October 1st, 2019 1:07 AM for the first discussion, and October 1st, 2019 4:34 AM for the second, both times PDT).

If you spot this issue again and I'm having a less busy week and can react quickly, perhaps I can get you the timestamp in time for you to correlate with your own recent memory of actions taken.

**Comment by pkaminski** [comment] 2020-10-25 21:02
Closing due to lack of activity over the last year.  Will reopen if you can gather more data.

**Closed by pkaminski** 2020-10-25 21:02 UTC
Labels: blocked
