### ISSUE TITLE
Show inline github comments inline

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#14] opened 2014-11-29 17:26 UTC
For example, on [this review][1], kberg left a comment on a particular line using the github UI. I'd like to see it on the same line in reviewable.

I realize github stores line notes in a somewhat odd format. But I've [implemented][2] the mapping before, so I know it's possible! And this would greatly facilitate moving back and forth between github and reviewable.

[1]: https://reviewable.io/reviews/danvk/dygraphs/501
[2]: https://github.com/danvk/better-pull-requests/blob/master/github_comments.py#L28

**Comment by pkaminski** [comment] 2015-04-01 20:09
I picked this up again and, after some back-and-forth with GitHub support, came to the conclusion that it's not possible to reliably map GitHub inline comments into Reviewable.  The core of the issue is that the data for an inline comment doesn't provide the sha of the base commit, so it's not possible to figure out what blobs the diff was between.  The PR's base diff cannot be used instead as it may have changed since the comment was made -- especially in the common case where Reviewable is backfilling a review that's been in progress for some time.

Marking as wontfix unless/until GitHub improves its API.

**Comment by pkaminski** [comment] 2015-04-19 07:45
I now do best-effort mapping of line comments from GitHub: if the comment is on a base or positive delta line, and if Reviewable has captured the target commit as a revision and can find the right file.  Line comments that fail to be mapped correctly are added to the top-level discussion as before, but now with a warning that points to this issue.

**Closed by pkaminski** 2015-04-19 07:45 UTC
Labels: enhancement, wontfix

**Comment by danvk** [comment] 2015-07-24 16:14
I just used this feature for the first time this week—I have to say, it's fantastic. It's really nice to be able to switch over to Reviewable once a review that you expected to be simple becomes large.

Thanks for implementing it! You might want to remove the "wontfix" label :)

**Comment by pkaminski** [comment] 2015-07-24 19:25
Glad to hear it worked for you @danvk, but in actuality a lot of stars have to align just right for GitHub line comments to be ported successfully.  So a more accurate label would be "fixed as much as possible, but it ain't perfect and not gonna get better" -- I'll settle for "wontfix".  :smiley:

**Comment by tomprince** [comment] 2015-09-29 03:10
> I now do best-effort mapping of line comments from GitHub: if the comment is on a base or positive delta line, and if Reviewable has captured the target commit as a revision and can find the right file.

I'm not sure how connecting repositories work, but it would be nice if comments made after a repository is connected were always mapped correctly (perhaps by forcing a revision). I haven't managed to convince all my team to switch to reviewable yet and it would be nice to be able to take over a review where there have been several rounds of review in github and finish them off in reviewable, where I can examine the changes that have come from the various review comments.

**Comment by pkaminski** [comment] 2015-09-29 03:26
Hey @tomprince, as it turns out Reviewable already does everything in its power to make comments mappable:  a GitHub comment makes the previous commit a "desired revision point", and will nearly always cause a revision to be created for that commit.  (The exception being if this would result in the creation of too many revisions at once, with the limit set at 10 by default.)  So pretty much the only comments that won't be mapped correctly once a repo has been connected are the ones on negative delta lines, and there GitHub simply doesn't provide sufficient information to reliably deduce the correct target (!).

If you see any mis-mapped comments outside of those constraints, please open an issue since you're probably seeing a bug.  Thanks!

**Comment by iphydf** [comment] 2016-12-13 03:16
Perhaps this can be revisited now that github has threaded review comments as well.

**Comment by pkaminski** [comment] 2016-12-13 03:17
Definitely, but there's no API available yet.  I'm tracking this in #418.
