### ISSUE TITLE
"unresolved and waiting for my action counter" is counting "resolved" messages

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#327] opened 2016-06-02 15:24 UTC
The issue had one unresolved comment awaiting acknowledgement from Alex. Alex resolved it, and the issue became mergeable. Note that, even then, Alex's counter said "1" and wanted him to acknowledge the top-level discussion. When he did so, his own counter went to "0".

But then Karl noticed that his counter was red and said "1" even though the thread that it brought him to says "Resolved" and the statuses seem to imply the same.

![image](https://cloud.githubusercontent.com/assets/187063/15750376/3cf9d3c2-28b4-11e6-9849-5c4ef95e4339.png)

![image](https://cloud.githubusercontent.com/assets/187063/15750382/428c5d5a-28b4-11e6-954c-28bfa7054687.png)

**Comment by pkaminski** [comment] 2016-06-06 04:37
Hmm, I can't quite correlated the screenshots with your scenario.  Does it help to note that a resolved discussion can be unreplied?  (For example, if a reviewer sets their disposition to "satisfied" in the reply or replies with an OK while "discussing", the discussion will be resolved but we still want the reviewee to be notified of the new comment.)  Basically, and discussion that has a "new comments" ribbon will be counted as unreplied.  Does that account for the behavior you observed?

**Comment by erikwright** [comment] 2016-06-06 17:00
There is a PR author (Erik) and two reviewers, Alex and Karl. Why does Karl need to reply to Alex's comments in a discussion that never mentioned Alex and in which he has "following" status (i.e. he has never ack'd or manually set his disposition).

Maybe he doesn't "need" to do it in order to resolve the discussion, but there is a big red counter of "unreplied" things and the expectation is that if it's red it means I need to act on it.

**Comment by pkaminski** [comment] 2016-06-07 19:39
If Karl has "following" disposition on the discussion, then he interacted with it somehow (likely by hitting Acknowledge at some point).  One he's "following" then the system assumes he's interested in further comments on the discussion and bumps the unreplied counter.  If he hadn't interacted with the discussion then his disposition would be "uninvolved", and the discussion would only show up as unreplied if posted by the PR author and nobody else had replied yet.

At least that's the theory, again let me know if it doesn't line up with your experience.

**Comment by pkaminski** [comment] 2016-06-24 21:09
Closing as works as intended pending further clarification.

**Closed by pkaminski** 2016-06-24 21:09 UTC
Labels: invalid
