### ISSUE TITLE
Failure to load reviews page

### ISSUE THREAD

**Issue by zware** [Reviewable/Reviewable#889] opened 2021-12-09 17:02 UTC
Running Firefox 94, the reviews page stopped loading for me a couple of days ago.  When set to either "All repositories" or just the one organization I'm interested in, it sits spinning on "Running 10 queries" interminably.  I did just discover that if I uncheck the "Also show pull requests you're not involved with..." option, the page will fully load after a page refresh.  I like that setting and would like it back, though :)

I'm not sure what further information you may need from me, but I'm happy to provide on request.

There is no impact on individual review pages, so this is more of an annoyance than something preventing me from using Reviewable.

**Comment by pkaminski** [comment] 2021-12-09 20:29
I recently optimized how "also show PRs you're not involved with" is implemented so this may well be a regression.  What's your configuration of starred / watched / connected options for the toggle?  Does flipping any of the switches make it work again by any chance?  Thanks.

**Comment by zware** [comment] 2021-12-09 20:46
My usual settings appear to be `watched: true`, `starred: false`, `connected: true` (watched is solid, starred is hollow, connected is to the right).

Here's a runthrough of how it seems to work for me, usual config first:

- w: t, s: f, c: t - fail
- w: t, s: t, c: t - fail
- w: f, s: t, c: t - fail
- w: f, s: f, c: t - success
- w: f, s: f, c: f - success
- w: t, s: f, c: f - success
- w: t, s: t, c: f - success
- w: f, s: t, c: f - success

**Comment by pkaminski** [comment] 2021-12-09 21:06
Thank you!  Looks like the broken configuration is `c && (w || s)` -- I should be able to hunt down the bug now.

**Comment by pkaminski** [comment] 2021-12-10 05:24
So I couldn't repro this but I have a suspicion that it's due to a watched/starred repo that you have push permissions on but that doesn't show up in `/user/repos` for you for some reason.  I've adjusted some internal mechanisms to take this possibility into account.  Can you give it another try and see if the issue is fixed?  Thanks!

**Comment by zware** [comment] 2021-12-10 15:08
~~I haven't ruled out that I'm having connection issues at the moment, but currently my usual settings cause the `Offline` popup with a reason of `waiting for permission checks`.  It's happened twice in separate tabs without auto-recovering.~~  Third time seems to have been the charm; my usual settings loaded this time.  I haven't checked the other failure cases yet; will try later today.

Thanks for the quick (probable) fix :)

**Comment by pkaminski** [comment] 2021-12-11 04:57
Getting stuck on permission checks is indeed a separate issue, #819, but it's hard to reproduce consistently and hence hard to debug.  I'm going to close this as fixed but please let me know if we need to reopen!

**Closed by pkaminski** 2021-12-11 04:57 UTC
Labels: bug
