### ISSUE TITLE
"sync requested reviewers" is requesting reviews from the wrong reviewers at the wrong time

### ISSUE THREAD

**Issue by gsuess** [Reviewable/Reviewable#782] opened 2020-10-27 18:37 UTC
The "sync requested reviewers" feature is not doing what I had in mind with #598.

I often find that accidentally request a review from myself by merely publishing a reply to follow up. Furthermore I also end up requesting reviews from everyone who every has participated in the PR reviews.

Reviews should be requested based on these two conditions:

1. The reviewers must have blocking discussions on the PR
2. The author must have explicitly addressed those blocking discussions with a comment (e.g. "Done"). 

If follows that from 2, that only the author would ever request reviews.

While 1. seems to be in place somewhat (not sure if the criteria is limited to blocking discussions or any discussion), 2. is not in place at all.

Without 2. the feature is causing the above mentioned problems.

**Comment by pkaminski** [comment] 2020-10-31 07:25
Requested reviewers are purposely tightly synced with Reviewable's pending reviewers list, to avoid having yet another list of users to manage.  The default logic behind who should be named a pending reviewer is pretty involved as it tries to conform to many workflows, but still sometimes misses the mark if your preferred workflow doesn't fit its assumptions.

The good news is that you can take full control of pending reviewers in your custom review completion condition.  For example, to literally implement the algorithm you proposed above, you'd do something like this (not tested!):

```js
const pendingReviewers = _(review.discussions)
  .map('participants')
  .flatten()
  .reject('resolved')
  .map(participant => _.pick(participant, 'username'))
  .uniq(false, 'username')
  .value();

return {pendingReviewers};
```

This would miss out on some features in the default algorithm but perhaps it will fit your workflow better.

**Comment by gsuess** [comment] 2020-11-03 20:31
I don't think that would solve the problem, because it misses out on this part:

> If follows that from 2, that only the author would ever request reviews.

In practice, it would still mean that: If I am the reviewer myself with a pending (unresolved) review and I submit another (unsolicited) review, then I will end up requesting another review from myself.

In that sense "resolved" is not the same as: 

> 2. The author must have explicitly addressed those blocking discussions with a comment (e.g. "Done").

It is a particular state of the discussion that is missing. If there was a field called "addressed" then one could script it that way.

Furthermore I understand that `pendingReviewers` are users that listed that needed to resolved the reviewable check. Which is what you refer to as "missing out on some features of the default algorithm". I would not want to miss out on those features or trade one feature for another. Instead "sync requested reviewers" should not be based on `pendingReviewers`, because it is not the same thing. I would suggested adding `requestedReviewers` to the output of the condition function.

**Comment by pkaminski** [comment] 2020-11-12 07:48
So it's a bit confusing, but `resolved` has two different meanings:  at the discussion level, it has its usual meaning of "does everyone agree we're done with this discussion", but at the _participant_ level it means "is this user not needed to move the discussion forward right now".  This latter is the converse of the "to reply" counter on the review page and, if you're a reviewer, should indicate pretty much what you're looking for: has the author responded to the discussion that you're blocking from resolving.

This does get trickier in multi-party discussions, admittedly.  If reviewers A and B are participating in a discussion, then a reply by A will request a review from B and vice-versa.  Is this the kind of case that's tripping you up?

I think to make progress on this issue we need you to list some concrete cases where the algorithm's decision to request a review from someone felt unwarranted.  Thanks!

**Comment by gsuess** [comment] 2020-11-25 15:16
I have emailed a few examples to your support email. Hopefully it helps. Maybe you can state the abstracted cases of those examples here.

**Closed** 2021-01-12 08:27 UTC

**Comment by pkaminski** [comment] 2021-01-13 03:37
So this took a fair bit of digging, but eventually I identified a "feedback loop" between GitHub's requested reviewers and Reviewable's pending reviewers caused by a combination of the default completion condition and the "sync reviewers" feature.  When publishing, Reviewable runs the completion condition on the extrapolated state of the review post-publication to figure out (among other things) which reviewers will be pending; the sync reviewers then uses _those_ pending reviewers as the basis for the requested reviewer deltas.  The default completion condition has a base case where it will consider all requested reviewers to be pending if there are files in the review that nobody has marked reviewed yet.  This caused the reviewer to be copied from requested reviewers to pending reviewers, and thence back to requested reviewers, with Reviewable helpfully doing so after the review was published to "work around" GitHub automatically un-requesting the reviewer.

The fix was to remove the current reviewer from the requested reviewers in the extrapolated review state being fed to the completion condition.  This addresses the bug I replicated but I can't guarantee it's the same one you observed -- there may well be more.  Please re-open this issue if you spot other edge cases!
