### ISSUE TITLE
Add alternative text/description for icons

### ISSUE THREAD

**Issue by yurydelendik** [Reviewable/Reviewable#105] opened 2015-05-28 17:23 UTC
Sometimes it's impossible to understand what icons mean. For accessibility and for better UI discover-ability tooltips/icons descriptions shall be present.

Some examples of confusions: signout icon may mean return to github PR page; also hard to understand what clickable "eye", "open parentheses" or "perpendicular lines" buttons do.

**Comment by pkaminski** [comment] 2015-05-28 23:13
Thanks for the feedback @yurydelendik.  This is a duplicate of #53, will continue to track there.  I'm not a big fan of tooltips but I'm working on a help system that will be even better, hopefully.  Coming soon.

**Closed by pkaminski** 2015-05-28 23:13 UTC
Labels: duplicate
