### ISSUE TITLE
Reviewable keeps hanging and can take several hours to publish review

### ISSUE THREAD

**Issue by NikCharlebois** [Reviewable/Reviewable#755] opened 2020-06-29 11:36 UTC
While working on the Microsoft365DSC project, which is under the Microsoft org under:

https://github.com/Microsoft/Microsoft365DSC

The tool keeps hanging while trying to do code reviews, and the Publish button hangs and very often takes 2+ hours before submitting the reviews, after multiple refreshes of the page an new attempts to publish. All users are affected, and I believe the issue is related to the size of the Microsoft org and the number of project it contains.

**Comment by pkaminski** [comment] 2020-06-30 00:18
Hey Nik, is it OK if I (or you) create a bogus PR in this repo for testing?  We can close it immediately after it's created so it doesn't distract anyone.  Thanks.

**Comment by NikCharlebois** [comment] 2020-06-30 00:25
Please go ahead and create one. Thanks

Nik Charlebois
________________________________

**Comment by pkaminski** [comment] 2020-06-30 04:43
Thanks.  The root cause of the slowdown is that the repo has ~18K potential assignees, and Reviewable tries to download the whole list up front.  (We use it to support autocompletion of `+@` directives, as GitHub lacks an API for this, and I was reusing it for pre-publication validity checks since it was assumed to be already loaded.)  This is clearly not reasonable in this case -- I'll find a different way.

**Comment by pkaminski** [comment] 2020-07-09 04:33
Apologies for the delay, my fix ran into some (other) performance issues with GitHub.  I reported those but also implemented a workaround.  You should now be able to publish within 10-15 seconds pretty much no matter what.  Please let me know if something's still broken!

**Closed by pkaminski** 2020-07-09 04:33 UTC
Labels: bug
