### ISSUE TITLE
error when loading reviewable in firefox 54.0.1

### ISSUE THREAD

**Issue by ginccc** [Reviewable/Reviewable#488] opened 2017-07-14 15:09 UTC
TypeError: Argument 1 of SVGGeometryElement.getPointAtLength is not a finite floating-point value.

chrome works as expected

**Comment by pkaminski** [comment] 2017-07-16 02:35
I was unable to reproduce this in Firefox 55.0b9 (32-bit) on Win10, so it may be a temporary regression in Firefox.  Nonetheless, I added a bit of code to detect the condition earlier and report an error more useful for debugging.  Can you give it another try in your Firefox to see if it still repros, so I can capture the new exception?  Thanks.

**Comment by ginccc** [comment] 2017-07-17 13:04
not sure about the version, but i cannot get it to run. now the error says: 
Error: Non-finite butterfly flight index: NaN

**Comment by pkaminski** [comment] 2017-07-17 17:39
Thanks, that helps narrow it down, though I still don't see how those few lines of code can produce a `NaN`.  I've added more instrumentation -- could you please trigger the error again?  Also, if you have a moment, could you try loading the page in incognito mode with no plug-ins?  Sorry for the debugging by proxy, but given that you're the only person to ever encounter this issue I don't have a lot of options...

**Comment by pkaminski** [comment] 2017-07-20 05:41
I'm going to close this for now, since nobody else with Firefox (any version, including 54.0.1) has seen this error.  My best guess based on the information collected thus far is that one of your extensions is messing with the Lodash (`_`) library, and `_.sortedIndex` isn't behaving like Reviewable expects it to.  Just a guess, though -- let me know if you'd like to help debug further.

**Closed by pkaminski** 2017-07-20 05:41 UTC

**Comment by ginccc** [comment] 2017-07-20 07:58
i did try to disable all the plugins. didn't help. nonetheless, uninstalling and reinstalling firefox did the trick. all plugins & configs are still the same, but now it works.. interesting what has had messed it up in the first place..
never mind. now it works. Thanks for the troubleshooting ;-)
