### ISSUE TITLE
Can't open any review from https://reviewable.io/. See error from console

### ISSUE THREAD

**Issue by LenaSilkina** [Reviewable/Reviewable#532] opened 2018-03-23 18:24 UTC
angular.js:14199 Error: Permission check for "git-name-of-my-repo" failed: Cannot read property 'pull' of undefined
     at k.updateAllowed (https://reviewable.io/js/c017c569.app.js:13:12197)
    at o.c [as onChange] (https://reviewable.io/js/d9d72a4d.libs.js:19:5528)
    at o.fireChanges (https://reviewable.io/js/d9d72a4d.libs.js:13:7932)
    at o.<anonymous> (https://reviewable.io/js/d9d72a4d.libs.js:13:7807)
    at https://reviewable.io/js/d9d72a4d.libs.js:3:8949
    at https://reviewable.io/js/d9d72a4d.libs.js:5:24645
    at f (https://reviewable.io/js/d9d72a4d.libs.js:3:26395)
    at https://reviewable.io/js/d9d72a4d.libs.js:3:27856
    at d (https://reviewable.io/js/d9d72a4d.libs.js:22:21648) undefined

**Comment by al-the-x** [comment] 2018-03-23 19:12
Dupe of #531 but better stack-trace.

**Comment by pkaminski** [comment] 2018-03-23 20:30
GitHub had a major regression in their API.  There was nothing I could do, and the app should've put up a GitHub warning sign on the page as soon as GitHub announced the issue on https://status.github.com/messages around 12:02 PDT.  Sorry in any case!

**Closed by pkaminski** 2018-03-23 20:30 UTC
