### ISSUE TITLE
Each update on a branch containing commits from several authors creates several "parallel" revisions

### ISSUE THREAD

**Issue by lassemaatta** [Reviewable/Reviewable#1137] opened 2024-02-04 13:40 UTC
I have a branch / PR with several commits (20+) from multiple authors. When I modify these commits (e.g. with rebase) and force push the branch, reviewable creates 5 revisions instead of one. 

When looking at the "Commits" contents in reviewable, I can see e.g. 

```
New commits in r26 on 2.2.2024 at 8.38, probably rebased from r21:
- 495abde: Some commit
- ...

New commits in r27 on 2.2.2024 at 8.44 by Some Other Person, probably rebased from r22:

- 9abfe95: Another commit
- ...

New commits in r28 on 2.2.2024 at 8.44, probably rebased from r23:
- 90b0a1a: More commits
-  ...

New commits in r29 on 2.2.2024 at 8.44 by Some Other Person, probably rebased from r24:

- d50b04f: Yet more commits
-  ...

New commits in r30 on 2.2.2024 at 8.45, probably rebased from r25:

- 8685009: More commits.
-  ...
```

I'm working on a branch containing some commits originally authored by my colleague (`Some Other Person`). Might this explain why reviewable creates multiple revisions (e.g. r26-r30 in the above example)?

This makes it quite confusing to read the changes, as this creates unnecessary revisions and also gives a very inaccurate view about the changes between revisions.

For example, when looking at an individual file it might say: 

> "File renamed from test/lupapalvelu/invoices/general_api_xml_converter_test.clj to test/lupapalvelu/invoices/integration/general/xml_test.clj at r9, then to test/lupapalvelu/invoices/general_api_xml_converter_test.clj at r10, then to test/lupapalvelu/invoices/integration/general/xml_test.clj at r14, then to test/lupapalvelu/invoices/general_api_xml_converter_test.clj at r15, then to test/lupapalvelu/invoices/integration/general/xml_test.clj at r19, then to test/lupapalvelu/invoices/general_api_xml_converter_test.clj at r21, then to test/lupapalvelu/invoices/integration/general/xml_test.clj at r25, then to test/lupapalvelu/invoices/general_api_xml_converter_test.clj at r26, and finally to test/lupapalvelu/invoices/integration/general/xml_test.clj at r30. "

^^ This indicates to the reader that the file has been renamed several times. But actually the file has been renamed once, but due to the multiple revisions reviewable gets confused.

Any tips on how to fix this? (or how to avoid this in the future?)

**Comment by lassemaatta** [comment] 2024-02-04 13:43
I guess this is related to https://github.com/Reviewable/Reviewable/issues/592

**Comment by pkaminski** [comment] 2024-02-05 04:53
Not just related — it's the same.  :)  But wouldn't you know, the original rationale for this revision splitting "feature" disappeared when we moved revision descriptions into the virtual commits file a while back.  And as it happens I'm doing work in that area of the code at the moment so I should be able to get this fixed in a few days.  (Unfortunately it won't be retroactive — sorry.)

As for the rename history mess, it's indeed caused by the ugly revision partitioning and will be fixed at the same time.  We're also planning to move to diff-bounds-dependent rename notices so there'll never be more than one pair of filenames in the list, but that'll be a bit later.

I'm going to close this issue as a duplicate in favor of the [original](https://github.com/Reviewable/Reviewable/issues/592), but thanks for attracting my attention to the problem, and please follow along there for an announcement of the fix.

**Closed by pkaminski** 2024-02-05 04:53 UTC
Labels: duplicate
