### ISSUE TITLE
"This change is Reviewable" commented as wrong user

### ISSUE THREAD

**Issue by seanf** [Reviewable/Reviewable#522] opened 2018-02-22 07:46 UTC
I'm trying to take advantage of https://github.com/Reviewable/Reviewable/issues/397.

I have selected the option "In PR comment by" and one of our organization's bot users (I had to make the membership public before Reviwable would let me). I can see that the option is being persisted, but the comments are being made under my username (as the user who linked Reviewable originally), not as the bot user I chose.

**Comment by pkaminski** [comment] 2018-02-22 08:27
Very odd.  Can you please let me know the repo and the number of a PR that was created after you changed the setting?   Thanks.

As for the public membership constraint, it's an admittedly somewhat awkward attempt to validate that the selected user has a fair chance of being able to create comments in the repo.  I don't know, given that there's a fallback email notification to the repo's connector if comment creation fails anyway perhaps we'd be better off without the check.

**Comment by seanf** [comment] 2018-02-22 10:55
@pkaminski Here's one: https://github.com/zanata/zanata-platform/pull/730#issuecomment-367585001

I think the public membership requirement makes sense in a way, since that user will be making a *lot* of comments on the repo in question, but it took me a while to realise what the requirement really was, since it didn't say anything about "public" (IIRC).

**Comment by pkaminski** [comment] 2018-02-22 11:39
Thanks!  The issue is that `zanata-jenkins` hasn't signed into Reviewable and authorized the relevant OAuth scopes, so Reviewable can't post as that user.  Two bugs contributed to letting you get into this state:  1) saving the settings is supposed to check for this precondition (and it kinda did, but failed to notify you and abort the save) -- this is now fixed on beta.reviewable.io; and 2) the server defaults to the repo's connecting account if it can't authorize the designated one -- this is a debatable fallback and I think I'll remove it soon, letting it send the connecting account an error message instead.

As for checking for membership, I forgot that another important function of this check is to prevent random users from being designated as comment posters and potentially joining them to a bunch of unwanted PRs.  I kept the check, but made the error message clearer.

**Closed by pkaminski** 2018-02-22 11:39 UTC
Labels: bug

**Comment by seanf** [comment] 2018-02-23 00:51
@pkaminski How do I authorise the right OAuth scopes?

I'm using another account now - **zubot** - and attempted to set up the authorisations, but I've only ended up with these: read:org, user:email - but I'm not sure if they will do.

**Comment by pkaminski** [comment] 2018-02-23 02:25
You'll need `public_repo` or (`repo` for private repos).  Easiest way to make sure all the necessary scopes are granted is to send a random comment under the bot's account.  :)

**Comment by seanf** [comment] 2018-02-23 03:47
@pkaminski Got it. I had to make the bot an organization owner too, but it's working now. Thanks!
