### ISSUE TITLE
Unreviewed files red flair is inconsistent

### ISSUE THREAD

**Issue by ggould-tri** [Reviewable/Reviewable#993] opened 2023-01-30 18:51 UTC
I'm seeing inconsistency in the unreviewed-files red flair icon in the "My Reviews" board.

(1) Initially, my "My Reviews" board shows three unreviewed files for PR 18664
![Screenshot from 2023-01-30 13-47-32](https://user-images.githubusercontent.com/17596413/215567918-b29c16ff-9263-451f-b1f5-96063595f1a1.png)
(2) When I enter the review, there are no unreviewed files.
![Screenshot from 2023-01-30 13-47-57](https://user-images.githubusercontent.com/17596413/215567922-9ecaf1af-6f9d-44a0-966e-e23e8a011835.png)
(3) When I return to "My Reviews", it correctly(?) shows no unreviewed files.
![Screenshot from 2023-01-30 13-48-16](https://user-images.githubusercontent.com/17596413/215567924-7129db69-fa33-499e-803d-8fa5a8942dfe.png)
(4) When I reload, it goes back to showing three unreviewed.
![Screenshot from 2023-01-30 13-48-26](https://user-images.githubusercontent.com/17596413/215567925-de539941-a2a7-4a80-a0f0-88a6fba10310.png)
Repeats without limit.

**Comment by fahhem** [comment] 2023-01-30 20:11
Hello, when you load the reviews dashboard, do you see the wrong number quickly? If you leave the tab open, does it go to 0 eventually? Also, do you see something like this at the top?

![image](https://user-images.githubusercontent.com/306100/215584661-6c6c7a0b-ab10-4203-9a0a-ceb7beab0e00.png)

**Comment by ggould-tri** [comment] 2023-01-30 20:19
The dashboard shows the wrong number immediately.  And the last-updated is current:
![image](https://user-images.githubusercontent.com/17596413/215585788-5abcf938-d790-426f-bd55-7e5871cfd58b.png)

Notably right now there are actually two real unreviewed changes (the PR has updated since I opened this issue) and it's showing 5 on the dashboard, so the dashboard seems to be wrong by a constant three unreviewed changes.

**Comment by fahhem** [comment] 2023-01-30 21:02
Thank you for the information. We recently made some changes to make the dashboard render faster on initial load, but it's possible there's some stale data being used as a result. We'll look into this and get back to you when we've root caused it.

**Comment by pkaminski** [comment] 2023-01-30 22:13
I'm afraid this is a duplicate of issue #656 that you opened way back in 2019.  I'm sorry to say we haven't made any progress on the problem since then.

We did recently make some minor bug fixes to the estimation algorithm, and it's possible those actually made some cases worse.  The three renamed files at the bottom of the file matrix with changes after the rename correlate suspiciously with the red 3 count.  However, looking at `constraint_relaxing_ik.h` as a sample, it appears to have review marks on both halves of the rename at `r3` so I'm not sure what could be going wrong here.  I don't think it's worth debugging the estimation algorithm, though, as even in the best conditions it'll always be approximate; instead, we need to find a way forward to showing exact counts.

BTW, the reason the count is correct after visiting the review is that doing so loads some extra data structures that we avoid loading on the dashboard to conserve bandwidth.  This lets us obtain an accurate count that then persists when you go back to the dashboard.

**Closed by pkaminski** 2023-01-30 22:13 UTC
Labels: duplicate
