### ISSUE TITLE
Erroneous "Merge and Delete"

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [Reviewable/Reviewable#554] opened 2018-05-23 19:46 UTC
First, apologies for not having good, reproducible steps.

Since the new beta, I've had multiple instances of a completed review offer the "Merge and delete " (or whatever the *true* label is). In the past, mostly I saw the non deleting type (Merge and Close?) The distinction has always been whether I actually had permissions to delete the source branch of the PR. It seems to have lost the ability to distinguish when I *can* and *can't* delete.

To play along, I've tried merging and deleting and typically get a red-flagged error banner that says something along the lines of:

```
Branch merged but unable to delete it: GitHub error 404 on DELETE https://api.github.com/repos/EricCousineau-TRI/drake/git/refs/heads/issue/8858: Not Found
```

If you need a more concrete example, let me know and I can flag a PR the next time I reach this state (but prior to attempting the merge).

**Comment by pkaminski** [comment] 2018-05-23 23:01
Thanks for reporting this Sean.  While the beta didn't intentionally make any changes here it's entirely possible something got messed up during the refactoring.  I poked around the code but couldn't find a clear root cause, though I did find some potential race condition issues that I cleaned up a bit.  Please let me know if you see this happen again, and if it does check if it happens consistently when you reload the page (to check the race condition hypothesis).  Thanks!

This might also be related to @dhalperi's issues with Reviewable losing track of preferred merge flavor.

**Comment by SeanCurtis-TRI** [comment] 2018-05-25 14:48
I'll keep an active eye out. If I don't see it come up again relatively soon, I'll mark this as closed.

**Comment by pkaminski** [comment] 2018-06-11 02:14
Looks like two weeks passed with no repros, so I'm going to assume this is fixed.  Closing.

**Closed by pkaminski** 2018-06-11 02:14 UTC
Labels: bug
