### ISSUE TITLE
Reviewable reverts keystrokes

### ISSUE THREAD

**Issue by zetok** [Reviewable/Reviewable#433] opened 2016-12-04 14:28 UTC
For some reason reviewable reverts keystrokes on one review: https://reviewable.io/reviews/qtox/qtox/3913

Even `backspace` is reverted…

Happens when typing.

Only this PR(?) seems to be affected.

Very annoying.

Screencap: [webm.zip](https://github.com/Reviewable/Reviewable/files/629580/webm.zip)

**Comment by sudden6** [comment] 2016-12-04 15:58
also happened to me today on the same PR, typing very slow was a workaround.

**Comment by pkaminski** [comment] 2016-12-04 19:57
Thanks, reproduced and working on fix.  In the meantime I rolled back the site so things should be OK for now.

**Comment by pkaminski** [comment] 2016-12-05 04:44
I believe this is now fixed -- please shout if you see any further symptoms.  The root cause was a change from sync to async writes in low-level infrastructure that induced a subtle race condition when saving drafts.

**Closed by pkaminski** 2016-12-05 04:44 UTC
Labels: bug
