### ISSUE TITLE
@mentions in the main review thread do not get marked as mention

### ISSUE THREAD

**Issue by yoichiro-wpna** [Reviewable/Reviewable#977] opened 2022-11-09 04:19 UTC
Looks like the issue reported by https://github.com/Reviewable/Reviewable/issues/636 and https://github.com/Reviewable/Reviewable/issues/791 is back.

The symptom is exactly what Jeremy Nimmer reported [here](https://github.com/Reviewable/Reviewable/issues/791#issuecomment-788263374).

We are using Reviewable Enterprise v3107.4890.

**Comment by pkaminski** [comment] 2022-11-09 06:13
You're using a version of Reviewable that's over a year old!  It's entirely possible that there was a regression at some point -- it looks like the bug was [re-fixed in v3477.5231](https://github.com/Reviewable/Reviewable/blob/master/enterprise/changelog.md#release-34775231-min-33405125-ghe-219-or-30-2022-04-17) (which itself is half a year old).  Please encourage your admin to upgrade to something closer to the latest version and we can take a look if the issue still repros.  Thanks.

**Closed by pkaminski** 2022-11-09 06:13 UTC
Labels: invalid
