### ISSUE TITLE
scrolling eye/filename in sticky bar

### ISSUE THREAD

**Issue by mmlb** [Reviewable/Reviewable#74] opened 2015-04-08 22:37 UTC
While reviewing a PR with 38 files changed and scrolling down, the "eye" icon and filename on the sticky bar slowly creeps up to the point where bottom of previous file's icon/name is seen with top of current file's. Scrolling with mouse wheel. Sending screenshots via email.

Chrome Linux Version 41.0.2272.118 (64-bit)

**Comment by pkaminski** [comment] 2015-04-08 23:08
Did you capture the screenshots at actual size, i.e. showing the same pixels as on your screen?  If so, are you running the page zoomed in, or have otherwise somehow changed your pixel metrics?  Everything looks too big by ~16%, and is throwing off the (hardcoded) offsets used to line stuff up.

**Comment by mmlb** [comment] 2015-04-09 11:19
Hmmm, yup seems like it was zoomed in without me noticing. Setting back to 100% lines everything back up.

**Comment by pkaminski** [comment] 2015-04-09 13:43
I still can't reproduce this issue, even after zooming in.  In Chrome (and other browsers too, I think), zooming just changes the size of a pixel, so all the hardcoded offsets (should) still work.  Otherwise zooming in would break nearly every site.

Can you reproduce the issue?  Perhaps it's different on Linux.

**Comment by mmlb** [comment] 2015-04-13 15:10
@pkaminski I can recreate when zoomed in @ about 125%.

**Comment by pkaminski** [comment] 2015-04-13 22:08
This appears to be a bug with the zoom feature in Chrome on Linux and OS X.  There's no obvious fix, as Chrome still reports the height of each filename row as 30px, same as the hardcoded offset multiplier I'm using, so even if it were dynamic there's no better value to set it to.  Given that there are multiple user-accessible workarounds (don't zoom, use a different browser, use a different OS) I'm going to close this as `won't fix`.  Sorry.

**Closed by pkaminski** 2015-04-13 22:08 UTC
Labels: bug, osx, wontfix

**Comment by mmlb** [comment] 2015-04-14 02:35
np, the zoom was there by accident so not a big deal for me.
