### ISSUE TITLE
Microsoft Edge issues

### ISSUE THREAD

**Issue by andschwa** [Reviewable/Reviewable#267] opened 2016-03-23 20:36 UTC
I am testing Reviewable in Edge because it's the default browser at my company. I'd like my team to switch to the "Strict Scrutiny" paid Reviewable plan, but they don't want to switch browsers, and so require that it work well in Windows 10's default browser.

I encountered ~3 issues:
## GitHub authentication

The initial GitHub authentication window, being a pop-up was blocked. However, clicking "allow once" then caused Reviewable to fail; it seemed like it lost track of the window.

Clicking "allow always", then refreshing, then authenticating worked, but this tripped up at least two co-workers testing in Edge.
## Performance

A moderately sized review, which performed fine in Chrome, had performance issues in Edge. Things were slow to render and respond (the butterflies visibly staggered across the page). I'm not sure how much can be done about this if it's an issue with Edge itself, but profiling it would be handy.
## Draft saves interrupt cursor position

It seemed to be the case that when typing in form, an automatic draft save would trigger, and then the cursor would jump to the end of the text. Thus if you're modifying the middle of the draft, your cursor would move all over.

**Comment by andschwa** [comment] 2016-03-23 21:21
I've heard reports from another co-worker that it is also slow IE.

**Comment by pkaminski** [comment] 2016-03-23 21:35
Auth issues:  reproduced, will fix likely by switching to use a redirect in Edge instead of a popup.  I didn't notice this before because apparently Edge's popup blocker doesn't apply to `localhost`.  :(

Cursor position: unable to reproduce, can you provide more details or a video?  I did notice that pasting inside comments is completely broken in Edge, I'll fix that.

Performance: probably reproduced -- things get janky in all but the smallest reviews.  It looks like something is triggering full-page restyles which accounts for most of the slowdown, though the JS performance isn't great either.  I can't promise I'll be able to fix it but I can at least figure out what's causing the restyles, and at worst report it to the Edge team.  As for IE, a fix for Edge may help there too, but its legacy JS engine is honestly not up to running Reviewable so I won't be putting time into debugging it -- sorry.

**Comment by andschwa** [comment] 2016-03-23 21:40
Thanks @pkaminski!

I'll see if I can reproduce the cursor position; it was a "seems" for a reason, it seemed to be intermittent; but the cursor definitely jumped a couple times.

No worries about IE; there's not much developers can do about that program.

**Comment by pkaminski** [comment] 2016-03-24 06:37
OK, login and paste issues are resolved.  I also played around some more and looked into the relevant code, but wasn't able to reproduce the cursor position issue.

As for performance, I've hit a dead-end.  If I'm reading them right, the profiles indicate that almost any DOM or style change causes a full-page restyling.  Unfortunately, there's no details on *why* that might be, and the lack of integrated JS traces makes it hard to relate the changes to my code.  I'm guessing there's something peculiar about my page's DOM or CSS structure since I can't imagine that Edge performs this poorly on every page but I have no idea what it might be.  If you can put me in touch with somebody on the Edge team who might be interested in investigating this I'd be happy to work with them, but at this point I see no way to make progress on the issue by myself until the developer tools improve further.

**Comment by pkaminski** [comment] 2016-04-11 10:00
Hey @andschwa, how's it going?  Is your team liking Reviewable, or are the Edge issues blocking you?  Did you manage to reproduce the jumping cursor position problem by any chance?

**Comment by andschwa** [comment] 2016-04-15 22:13
@pkaminski In a meeting about it right now! Haha.

**Comment by pkaminski** [comment] 2016-04-15 22:16
Ping me on https://gitter.im/Reviewable/Reviewable if you need any
real-time answers.  :)


On Fri, Apr 15, 2016 at 3:13 PM, Andy Schwartzmeyer <
notifications@github.com> wrote:

> @pkaminski <https://github.com/pkaminski> In a meeting about it right
> now! Haha.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Reviewable/Reviewable/issues/267#issuecomment-210666076>
>



-- 
Piotr Kaminski, Founder, reviewable.io

**Comment by andschwa** [comment] 2016-04-27 19:20
@paulcallen can get you in touch with an Edge developer :smile:

**Comment by pkaminski** [comment] 2016-04-28 20:24
Thanks!  @paulcallen, it would be great if you can get an Edge developer onto this thread -- Reviewable appears to be causing full relayouts/repaints for almost every event, but the debugging tools haven't helped me figure out why so far.

**Comment by andschwa** [comment] 2016-04-28 22:46
@pkaminski I found an internal DL and have forwarded the issue along, hopefully an Edge developer will come help out!

**Comment by dstorey** [comment] 2016-06-30 04:31
Ping @toddreifsteck for perf issues in Edge.

**Comment by toddreifsteck** [comment] 2016-06-30 04:51
Ok... now I'm aware!

I'm heading out of town for the July 4th weekend but would love to assist when I'm back. I'm a complete novice for Reviewable. Can someone point me to a quick "how to" for "getting started" and reproducing the perf issues? When I have those in hand, I'll help out by profiling and giving some advice based upon what I see.

**Comment by pkaminski** [comment] 2016-07-05 00:52
Hey @toddreifsteck, thanks for offering to jump in and hope you had a good weekend!  To repro, simply visit https://reviewable.io/reviews/Reviewable/demo/1 and observe the overall poor performance.  For a somewhat more controlled experiment, you can sign in, create a new comment (e.g., by clicking in the "Reply..." box near the end of the top-level discussion), and start typing.  This produces a performance chart like the following on my machine:
![image](https://cloud.githubusercontent.com/assets/1646896/16571388/e720aee2-420f-11e6-962d-8bf872ffd0b4.png)
The culprits appear to be regular global style recomputations but I can't figure out what might be causing them.  Any ideas would be appreciated.

**Comment by toddreifsteck** [comment] 2016-11-10 19:37
This was lost in my email. I've opened https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/9751935/ ensure the issue is tracked in our bug database.

**Comment by toddreifsteck** [comment] 2016-12-30 19:19
Just went to diagnose this and found that https://reviewable.io/reviews/Reviewable/demo/1 is now smooth (and does not crash) on an internal build of Microsoft Edge for the Creator's Update. I then tested on Anniversary Update build 14393.693 and also see smooth behavior.

Most users of Microsoft Edge have already updated from the November Update, 10586, to the Anniversary Update, 14393. 

Is there still a known performance issue on these newer builds that needs to be investigated?

**Comment by toddreifsteck** [comment] 2016-12-30 19:20
Adding @nolawson to pull him in as well. He tends to be a better bulldog than I am.... :-)

**Comment by toddreifsteck** [comment] 2016-12-30 19:20
@nolanlawson

**Comment by pkaminski** [comment] 2017-01-03 07:52
I concur, I can no longer reproduce the performance issue on v38.14393.0.0.  Self-resolving bugs are the best bugs!  :D  Closing.

**Closed by pkaminski** 2017-01-03 07:52 UTC
Labels: bug
