### ISSUE TITLE
Opening up Reviewable is super slow

### ISSUE THREAD

**Issue by manishrjain** [Reviewable/Reviewable#813] opened 2021-02-03 19:22 UTC
When I open reviewable, it is very slow. Takes around 20s to open up. Even having another reviewable open doesn't help.

Btw, we're open to helping you guys run your backend service via Dgraph Cloud, if that'd help speed things up (at a discounted rate, considering we really need reviewable to work fast).

**Comment by pkaminski** [comment] 2021-02-04 04:01
Can you try loading your dashboard with `?debug=latency` appended to the URL and report the object logged in the console?  This should give us a better idea of where the time is going.  Thanks.

As for Dgraph Cloud, I'm afraid it's not a good fit.  Reviewable is tightly coupled to Firebase RTDB and retargeting onto a different database (or wrapper) would be tantamount to a rewrite.  Besides, I'm pretty sure that Reviewable's database is not at issue here -- but let's see the data.

**Comment by manishrjain** [comment] 2021-02-04 15:45
First run:
```
boot: 172
extLatency: 1099
init: 4
load: 567
numReviews: 258
page: "Dashboard"
show: 356
signedIn: false
```

Second run:
```
boot: 172
extLatency: 18598
init: 3
list: 17751
load: 672
numReviews: 258
page: "Dashboard"
show: 0
```

Third run:
```
boot: 187
extLatency: 16502
init: 4
list: 16151
load: 160
numReviews: 258
page: "Dashboard"
show: 0
```

**Comment by pkaminski** [comment] 2021-02-04 16:34
Yep, this shows that the vast majority of the time is spent on loading and displaying the list of PRs.  (The first run's result is likely a broken measurement, perhaps due to the automatic forwarding from the home page to the dashboard.)

Unfortunately, it's unlikely there's much that can be done to speed up these queries since GitHub's query language isn't very expressive.  There's a natural tension here between latency and completeness, and Reviewable errs firmly on the side of completeness in the expectation that you'll just keep this tab open.  I also don't want to show partial results as they come in since changing the list under your pointer would be terrible UX.

You can load the page with `?debug=dashboard` to see the individual queries being run to fill the list.  If you have "also show PRs you're not involved with..." toggled on, turning it off should speed things up a bit.  I can also check if batching requests together via GraphQL aliasing helps at all, but ultimately we're at the mercy of GitHub's servers here AFAIK.

**Comment by manishrjain** [comment] 2021-02-05 01:55
GitHub has the GraphQL based queries, which should be able to pick up and show all the PRs. Is there something in their APIs, which doesn't let you do that?

**Comment by pkaminski** [comment] 2021-02-05 08:22
We're already using GraphQL (modulo one team-related REST call that is/was missing from the GraphQL schema, IIRC), but our queries are searches rather than just graph traversals.  And there's a lot of them because GitHub has some arbitrary length restrictions on the query string.  Currently, we're sending out one request per query, so if it's some per-request overhead that's killing us then batching up the queries into fewer requests ought to help.  I'll try that out soon (will need to restructure the code a bit), but if it doesn't help then it's just the search queries being slow on GitHub's infrastructure...

**Comment by pkaminski** [comment] 2021-02-06 15:37
I have some preliminary results and they're not promising: I reduced the number of GraphQL requests on my dev environment from 14 to 5, but the overall latency has remained unchanged.  I'll probably polish up and release this tweak anyway (since fewer requests is generally a good thing) but I'm afraid at this point it's pretty clear that the issue is that GitHub's search is just plain slow.

My only other idea at this point is to cache some data about the user so that we can emit the expensive searches a bit earlier.  Might shave off a second or two, we'll see.

**Comment by manishrjain** [comment] 2021-02-09 04:28
Yeah, some sort of a cache here would be helpful.

**Comment by pkaminski** [comment] 2021-02-09 09:46
I implemented caching of search input data (user's full team list, or pre-filtered repo list), which in my experiments shaves ~1 second (and no more than 2 seconds) off the loading time.  I don't expect it'll help much more than that in production -- I'll try releasing the new code later this week.

I don't want to cache the list of PRs itself since users will expect to see a fresh list when they (re)load the page.  I'll have to see what other opportunities to parallelize stuff I can spot...  We're also working towards getting rid of Angular, which should help script load and init time at least a bit, but that's not going to be complete until later this year.

**Comment by manishrjain** [comment] 2021-02-09 14:06
I think we could build an endpoint which in the background gets PRs from GitHub, so when reviewable hits it, it can serve fresh results quickly.

Would it be possible to (locally) configure reviewable to use that endpoint instead of GitHub? If that works well for us, we could consider extending that service to other open source projects.

**Comment by pkaminski** [comment] 2021-02-09 14:31
Getting results in the background is something Reviewable could do equally well, I suspect.  But we can't get raw results because the set is way too big (potentially all PRs on GitHub!) and we don't want to replicate GitHub's search logic, and if we cache search results then we're back to the issue of freshness.

Perhaps I don't understand what you're proposing, though?  Take a look at the GitHub requests that Reviewable emits when loading the dashboard -- I don't see any practical way to create a timely-updating cache of those results.  AFAIK GitHub doesn't offer search result streaming or webhooks for result set updates.

**Comment by manishrjain** [comment] 2021-02-09 21:32
I think we (Dgraph Labs) can create a GitHub-like backend for Dgraph repos, which would give you a similar interface with results. And we'll do the work of ensuring the results are fresh.

What we'd need from Reviewable is a way to tell it to use our endpoint, instead of GitHub's, if that's possible.

If this system works, we could consider extending it to your other open source users -- but that's a call that you can make later.

**Comment by pkaminski** [comment] 2021-02-10 04:31
I see.  As much as I appreciate the offer, I'm not too keen on adding a dependency for a key feature that not everyone would be able to take advantage of.  Let's consider it an option of last resort -- we'd need to figure out up front how to make it generally available, including to on-premises enterprise customers -- if I'm going to commit to it from our side.

I'm curious how you'd approach keeping the results fresh, though?  Perhaps this is something I could do directly on Reviewable's servers instead.

Another idea from @anthonykawa is to enable organization-specific dashboards, in the hope that the search queries will run faster when constrained to an organization.  We don't know yet what the impact on performance would be, if any, but would that fit your use case at least in principle?  Reviewable already allows for repo-specific dashboards (`/reviews/<owner>/<repo>`) and extending this to org-level dashboards shouldn't be too hard.

**Comment by pkaminski** [comment] 2021-02-15 12:28
So while working on this I noticed that the latency measurement system got broken at some point, and was assigning too much time to the `list` phase.  It's fixed now -- could you please take a couple more latency samples to reconfirm that running the queries is still the majority contributor?  Thanks.

**Comment by pkaminski** [comment] 2021-02-25 07:37
We launched the ability to constrain the dashboard to a specific organization and it does seem to improve latency a bit more.  I can't think of further improvements right now and the latency seems to be "good enough" (for me, at least), so I'm going to close the issue.  Please don't hesitate to reopen if your situation has not improved or if you have other ideas, though!

**Closed by pkaminski** 2021-02-25 07:37 UTC
Labels: enhancement
