### ISSUE TITLE
File-level comments

### ISSUE THREAD

**Issue by danvk** [Reviewable/Reviewable#26] opened 2014-12-15 23:05 UTC
Some comments relate to the entire file, rather than a single line.

This isn't a notion in GitHub, but it's an incredibly useful one that's present in Gerrit, for instance.

**Comment by savvopoulos** [comment] 2015-07-26 08:32
+1 to enabling a 1-line comment on binary files, I wanted to say "please remove a.out from this PR" and there was no elegant way to do this.

**Comment by pkaminski** [comment] 2015-07-26 08:34
@savvopoulos, could you please create a new issue for allowing comments on binary files?  It's related to this one, but different enough that I'd like to track it separately.  Thanks!

**Comment by ichekrygin** [comment] 2017-08-05 23:46
@pkaminski: here is another use case when you want to place a comment at the file level: someone added an **empty**  I see it, I want to ask a question or comment on it - but I cannot!

**Comment by pkaminski** [comment] 2017-08-14 21:58
@ichekrygin Actually, a empty file will be displayed in the diff with an _Empty file_ placeholder line that you can click on to add comments, so I think this use case is taken care of.

**Comment by ichekrygin** [comment] 2017-08-14 22:46
@pkaminski perhaps I am missing it - where should I click?
![image](https://user-images.githubusercontent.com/324803/29295158-bd946a22-8107-11e7-872a-893396344f67.png)

**Comment by pkaminski** [comment] 2017-08-14 22:55
Your screenshot is of the GitHub UI, not Reviewable.  In Reviewable it looks like this:
![image](https://user-images.githubusercontent.com/1646896/29295354-e8ccc328-8108-11e7-8083-fdb28f2d3c39.png)

**Comment by ichekrygin** [comment] 2017-08-14 22:57
ARGH... my bad. Thank you.

**Comment by martin-displayr** [comment] 2018-12-13 03:41
I don't like the workaround. You then have to say in your comment "ah this isn't for line 1 it's for the whole file AND .... "

E.g. why have PR top level comments if you can stick them in line 1 of the first file?

**Comment by hazelnusse** [comment] 2018-12-17 16:18
A situation I encounter fairly frequently is asking people to move or rename a file under review. This is a natural use case for file level comments.

**Comment by aholmes** [comment] 2021-04-05 20:33
Another case this doesn't work is when the first line might reference another file or with any text that is ambiguous.

file foo.bar
`import bar.baz`
> Rename this file to bar.foo.

Now I have to explain that the comment applies to "foo.bar" not "bar.baz."

Anyway, we've all agreed that file-level comments are useful so working around this limitation is bogus. It's clear there are cases where workaround comments are ambiguous or not possible. If the point of PRs is code quality, avoiding ambiguity in the PR tooling is necessary to achieve this.

**Comment by jverce** [comment] 2021-05-08 00:55
The workaround is just a workaround IMO.
Being able to make comments at the file level allows us to comment on stuff like:
- Please reformat this file
- This file should be located in a different path
- This is a binary file and should not be included in the PR

Yes, we can choose an arbitrary line, and make a comment there with the header **- This comment is for the whole file, not for this specific line -**, but I'd prefer the platform to do that for me in a standard and consistent way.

**Comment by cfongCPG** [comment] 2021-11-23 01:47
Additionally, in GitLFS there is no way to comment on a line of a file as a workaround to comment of the file. If there are several file changes to Git LFS files I need to explain all of their changes in the PR description. This can quickly turn a PR into a wall of text.

**Comment by pkaminski** [comment] 2021-11-23 02:12
Oh?  I thought GitLFS put small text stub files into the repo (that point to the real file), and that you could make comments on those.  It doesn't work that way?

As for the workaround, remember that you can stop multiple top-level threads so you don't need to put all your comments into the main discussion.

**Comment by cfongCPG** [comment] 2021-11-23 02:16
Thanks for getting back!

![image](https://user-images.githubusercontent.com/94010674/142961956-c36d3138-a7b0-48f0-93d3-58049464f768.png)
I can't seem to comment on it :/

> Stop multiple top-level threads?
As in, make a separate comment for each file when creating my PR, that way each one can be threaded on separately?

**Comment by pkaminski** [comment] 2021-11-23 02:18
Your screenshot shows the GitHub UI, not Reviewable.  😄 

> As in, make a separate comment for each file when creating my PR, that way each one can be threaded on separately?

Yeah, pretty much, though you / your reviewers can just create a new thread whenever needed rather than doing it up front.

**Comment by cfongCPG** [comment] 2021-11-23 02:21
OH MY GOSH WHAT AM I DOING HERE I'M SO SORRY

**Comment by regislegrand** [comment] 2022-03-14 09:52
Hello, how would you add a comment on this ?
![image](https://user-images.githubusercontent.com/60347956/158148042-6d196b17-ae1d-4283-9bb4-3d7038e05949.png)

**Comment by pkaminski** [comment] 2022-03-14 20:40
Heh, that's another screenshot from GitHub, can't help you there -- use Reviewable!

**Comment by blakeNaccarato** [comment] 2022-12-29 01:31
**If you've landed here (like I did) wanting this in GitHub's code review UI, you're in the wrong place. This is for a tool called Reviewable, unrelated to GitHub's UI. Go add your vote to one of these related discussions for the GitHub UI instead!**:

- https://github.com/community/community/discussions/13013
- https://github.com/community/community/discussions/13013
- https://github.com/community/community/discussions/28085

**Comment by earlAchromatic** [comment] 2023-03-16 23:33
@pkaminski Github just released this exact feature in beta. [Feedback](https://github.com/community/community/discussions/49954) looks pretty positive and I wonder if its worth reconsidering. Could we use the same pattern as top-level discussions but at the file level? This is the A+ user experience IMO.

Here are some alternative ideas if implementing this at the file level directly is not feasible:

The main disadvantage of using top discussions for this is that the discussions there are not coupled to the file in a nice way. We could link to files from these discussions. This can be done manually today but I'm not sure its the best experience. Manual links to the file open in single file mode.

We could improve this experience by adding a button in the file header dropdown (in progress) that automatically creates a linked top discussion, have a dedicated 'jump to file' button somewhere in the top level discussion UI (and vice versa) or maybe make use of an inline directive to make the link.

We could allow a single top level discussion dedicated to each file and link appropriately to file matrix and files for easy navigation, which is important if we aren't providing the discussion right at the file.

**Comment by pkaminski** [comment] 2023-03-16 23:38
I believe @snoack just confirmed that file-level comments with `line: 0` actually render fine so I think we could do the A+ version of this.  One concern was the lack of a spot in the UI for a button, but as you say the upcoming dropdown gives us a natural spot for this.  A remaining unknown is how well new-discussion drafts tolerate `line: 0` but that should at least be easy to check.

**Closed** 2023-06-22 04:00 UTC
Labels: enhancement, parity
