### ISSUE TITLE
Add ability for reviewer to make minor edits to PR

### ISSUE THREAD

**Issue by sherm1** [Reviewable/Reviewable#415] opened 2016-11-01 21:38 UTC
GitHub recently upgraded its reviewing tool. It is still nowhere near as nice as Reviewable, but it has one feature that is better: the ability for the reviewer to commit minor edits to the PR. It is awkward to use GitHub's feature while in the middle of a Reviewable review, but it is so useful that many of our reviewers have been stumbling over to GitHub to do it anyway. Please consider adding this feature to Reviewable where the workflow could be considerably improved.

The usual situation is that a reviewer spots typos or other comment errors, formatting errors, or minor code style guide violations during a review. It would be much more efficient for the reviewer simply to fix them rather to explain the problem to the submitter and re-review.

**Comment by pkaminski** [comment] 2016-11-01 22:04
Agreed it would be very helpful, but also a pretty tall order to implement.  It's not going to happen before the [replatforming](http://blog.reviewable.io/performance-improvement-plan) in any case.

**Comment by sherm1** [comment] 2016-11-01 22:58
I like your priorities!

**Comment by pkaminski** [comment] 2021-06-02 21:34
Closing as duplicate of #671, since that one has a more developed discussion.

**Closed by pkaminski** 2021-06-02 21:34 UTC
Labels: duplicate, enhancement
