### ISSUE TITLE
Reviewable fails to load (older) PR

### ISSUE THREAD

**Issue by johlju** [Reviewable/Reviewable#676] opened 2019-08-31 07:20 UTC
When trying to continue the review on the PR https://github.com/PowerShell/xWebAdministration/pull/339 using
https://reviewable.io/reviews/powershell/xwebadministration/339 (the link in the PR) in Chrome it starts to look okay, but after a while I get a standard error

![image](https://user-images.githubusercontent.com/7189721/64060663-7d758280-cbd0-11e9-812a-b2a999eba1a7.png)

Reloading result in the same problem.

@pkaminski maybe you can see what is going on?

**Comment by pkaminski** [comment] 2019-09-01 03:54
I'm unable to reproduce this in Chrome 76.0.3809.100 on Windows 10: the page loads, and remains stable for at least a few minutes.  As this is a browser-level error, could you please try with extensions disabled?  You could also try with `?debug=workers` to force tab-local web workers to be used.  I'm not really sure what else could be causing Chrome itself to crash...

**Comment by johlju** [comment] 2019-09-01 09:29
I'm using Chrome Version 76.0.3809.132 (Official Build) (64-bit). Tested using `?debug=workers` and did no difference unfortunately.

When I start Chrome in an Incognito window then it set's the file matrix to show all revisions, and then the files shows correctly.

![image](https://user-images.githubusercontent.com/7189721/64074424-37412180-ccab-11e9-9515-6fb173945721.png)

 As soon as a change to an revision where I last reviewed (the eye icon on the first file in the ) it starts loading the diff (the progress circle starts to swirl) and then it breaks again in a few seconds.

![image](https://user-images.githubusercontent.com/7189721/64074453-b33b6980-ccab-11e9-8f6d-ec9d3459798a.png)

**Comment by johlju** [comment] 2019-09-01 09:36
Loading this in Firefox I saw that not all files are loaded properly. First three shows the diff content, but the rest gets this error

![image](https://user-images.githubusercontent.com/7189721/64074507-7cb21e80-ccac-11e9-8790-3eea51eeff01.png)

When changing to the revision 2 for the README.md when in Firefox it shows this repeatedly when pressing "Wait"-button as the response to the question.

![image](https://user-images.githubusercontent.com/7189721/64074524-abc89000-ccac-11e9-8bf4-a11ede9a522e.png)

**Comment by johlju** [comment] 2019-09-01 09:46
In incognito mode in Chrome when getting the above error for the files I can press "Try again" and it loads the file correctly (as long as the file matrix is showing all revisions). But can't switch revision in the file matrix as said before.

**Comment by johlju** [comment] 2019-09-01 09:52
@pkaminski This is not a big issue since it is the first time I have seen this, and could be because this is an old PR (~1,5 year). I submitted this issue just in case this was an edge case issue that you might not otherwise easily detect. If you feel this is not an issue in Reviewable than I can just merge the PR since all I wanted to do was sign-off on the file to get the status check green on the PR. But if this could be an issue with Reviewable I can keep the PR open a few more days.

**Comment by pkaminski** [comment] 2019-09-02 03:54
Thanks -- I've reproduced by diffing r2..r4, digging now.  The "parser is unable to parse response" error is another thing I've been trying to track down recently so it's great to have a repro.  I think you can safely get the PR merged, though, as that shouldn't materially affect the state of the review.

**Comment by johlju** [comment] 2019-09-02 05:34
Great that you could reproduce it! Let’s keep the PR open a while. I need to merge it before next release at the latest, but that’s a few weeks away.

**Comment by davefu** [comment] 2019-09-02 13:37
Hi, I've encountered same issue today.
At the beginning I was able at least to review files one by one, because of big diff. So this happened just when I opened the problematic file. But once I reviewed few files and reloaded page, Reviewable wants to display all files at once and since that I cannot finish the review at all cause page is not responding. (BTW I haven't figured out how Reviewable decides if a PR should by displayed at once or per file, yet... 😄).
Unfortunately, it's private repo, so you probably cannot reproduce the issue.

I tried it in latest Firefox & Chrome and getting same symptoms as @johlju mentioned.
Adding screenshots from FF debugger console and Reviewable error message, that appears after several clicks on "Wait" button in FF "A web page is slowing down your browser..." dialog.

![Screenshot_2019-09-02_151835](https://user-images.githubusercontent.com/2168632/64118012-f9b9c280-cd96-11e9-9f0e-ef9c0a712421.png)

![Screenshot_2019-09-02_151914](https://user-images.githubusercontent.com/2168632/64118015-fd4d4980-cd96-11e9-9638-78d0a1381b2c.png)

**Comment by pkaminski** [comment] 2019-09-02 21:20
This should be fixed now.

Post mortem:

This was a regression introduced by the migration of the diff components to Vue that exposed an underlying bug in the old Angular implementation.

Specifically, when displaying a declaration header above a diff section starting in the middle of a syntax unit, and in two-column diff mode, and if one side had a declaration and the other didn't, Angular simply ignored the missing declaration and displayed a slightly broken UI, whereas Vue crashed due to a `null` dereference.

This exception was caught by Sentry and queued for sending off to the server.  However, because the component's rendering took place in a watcher, apparently Vue kept invoking the watcher in a loop as it kept crashing.  This both exhausted memory and prevented the error report from actually being sent to the server (which would have made root-causing trivial).

I've fixed the immediate error and I'm working to figure out how prevent this kind of infinite loop in the future as well.

**Closed by pkaminski** 2019-09-02 21:20 UTC
Labels: bug

**Comment by johlju** [comment] 2019-09-03 07:32
@pkaminski thank you for being able to fix it so quickly! Works perfectly.
