### ISSUE TITLE
Empty diffs require manual approval

### ISSUE THREAD

**Issue by feldgendler** [Reviewable/Reviewable#622] opened 2019-03-18 12:03 UTC
Our workflow involves rebasing feature branches periodically to keep up with the master, instead of merging master into the feature branches. Every time we rebase, the reviewer of the PR sees a lot of new “changes”, which are shown as empty diffs (no modified lines) but still need to be marked as reviewed one by one. We can't just click “Mark as reviewed” because some of them might contain nonempty changes (conflict resolution). This is especially awkward when the review is so big that only one file is shown at a time.

Zero-diff “changes” are noise. There's nothing useful that can be done with them.

Expected: “changes” with no changed lines (where the file wasn't renamed, either) aren't shown as changes by Reviewable

**Comment by pkaminski** [comment] 2019-03-19 06:30
Those empty diffs probably have base branch changes that are getting collapsed by default -- can you confirm?  If so, it's a conscious decision to show the diffs (even if they're empty by default) as the files have, in fact, changed.  There's a chance that the base changes are actually incompatible with the PR's changes (even though they're in different areas of the code).

That said, I understand that such diffs may warrant special treatment.  Would your ideal workflow be to ignore them altogether?  Or perhaps it would be sufficient to let you easily mark those empty diffs (and only those empty diffs) as reviewed?  It's not clear if a single solution can satisfy (most) everyone or if this needs to be configurable somehow.

**Comment by feldgendler** [comment] 2019-03-19 16:06
OK, I've dug a little deeper, and this is what I found.

How to reproduce:

1. Make a PR of two commits (r1, r2). In r1, change some files. In r2, add some files.
2. Mark everything as reviewed.
3. Commit something to master, and rebase the PR to the new master. This produces (r3, r4).
4. Get Reviewable to show the diff betwen r2 (last reviewed point) and r4.

For the files added in r2 (and r4), you'll see that there is a “difference”, but the diff is empty.

Expected result: that I somehow don't have to pay attention to every one of those files, making them green one by one. These files were already approved in r2, and they are _exactly the same_ in r4.

For us, this workflow is frequent. We often add lots of new files, and have to rebase the PR several times while it's in development.

**Comment by feldgendler** [comment] 2019-03-19 16:08
In general, whenever you show me an empty diff and ask me whether I approve it, what else can I possibly do except clicking “mark as reviewed”? Reviewable is literally asking me whether it's OK to change nothing in a file.

**Comment by feldgendler** [comment] 2019-03-19 16:52
Sorry, no, it doesn't only happen when adding files (but this is one of the ways to trigger it).

> That said, I understand that such diffs may warrant special treatment. Would your ideal workflow be to ignore them altogether?

Yes. A zero diff is not a change. The file is exactly the same before and after it. There isn't even a theoretical basis on which I might want to reject such a change. When I'm asked whether it's OK that zero lines have changed, I say yes, of course it's OK.

**Comment by pkaminski** [comment] 2019-03-19 16:56
> 1. Make a PR of two commits (r1, r2). In r1, change some files. In r2, add some files.
> 2. Mark everything as reviewed.
> 3. Commit something to master, and rebase the PR to the new master. This produces (r3, r4).
> 4. Get Reviewable to show the diff betwen r2 (last reviewed point) and r4.

In step 3, did you commit any of the files that are also changed (or added) in the PR?  I expect that you did, otherwise this may be a genuine bug.

> Reviewable is literally asking me whether it's OK to change nothing in a file.

If my guess above is correct, it's actually more subtle than that:  Reviewable is telling you that the file was merged/rebased, which caused changes to be made to it that are not near the changes made directly in the PR.  Looks for "N lines with base commit changes" in the "empty" diff's collapsed area.

**Comment by feldgendler** [comment] 2019-03-19 17:16
But we are talking about an added file. It hasn't existed on master. Whatever was done in master on step 3, it definitely did not involve the file that only exists in an unmerged PR.

**Comment by jwnimmer-tri** [comment] 2019-03-19 17:23
FYI @pkaminski In my own experience, if I have (1) "review each commit separately" set for a review, and (2) one of the PR commits adds files, and (3) I use a rebase-force-push (not merge) pushes to PR, then I seem to recall seeing phenomena like what @feldgendler describes -- where the, e.g., r2..r4 diffs think that r3 _removed_ the new files and then r4 _added_ them back, and it wants me to re-affirm the noop.  I don't use "review each commit separately" very often so don't have a repro at hand reently, but if it helps I can probably recreate or find an older one.

**Comment by pkaminski** [comment] 2019-03-19 17:40
Thanks @jwnimmer-tri, that's starting to make sense!  @feldgendler can you confirm that you're using the "review each commit separately" review style?  You also said that it doesn't only happen when adding (and presumably removing) files -- what are other ways to trigger the issue in your experience?

**Comment by feldgendler** [comment] 2019-03-19 18:02
Yes! I use “review each commit separately” all the time.

**Comment by feldgendler** [comment] 2019-03-19 18:04
I think it also happens for changed files. If you change a file in r2 (and r4), it will indeed look like the changes have been undone in r3 and then done again in r4. So even when comparing r2 to r4, where there should be absolutely no difference, empty diffs appear and need manual approval.

**Comment by jwnimmer-tri** [comment] 2019-03-19 20:06
FYI Even with "combine commits" it's possible this could still happen due to #592.

**Comment by pkaminski** [comment] 2019-03-20 03:29
I need to think about this some more, but I believe what's needed to fix the problem is to extend the "equivalent commit" revision collapsing algorithm.  Currently, when forming new revisions Reviewable will check whether the previous revision's file shas exactly match the proposed revision's file shas, and if so merge them even though their commit shas are different.  However, this only covers adjacent revision pairs.

Instead, the algorithm needs to collapse entire subsequences of revisions with an extrapolation of the same rule.  So if r1 and r2 exist, r3 and r4 are proposed, and r1.files == r3.files and r2.files == r4.files, then r3 and r4 are rejected and their commits glommed onto r1 and r2.  This gets a bit tricky since the subsequences could span old and new revisions, a subsequence can be collapsed only onto the (post-collapse) tail so the head revision remains correct, and the subsequence may not necessarily cover all the new revisions.  But overall it seems feasible.

I think this would address most common issues.  It wouldn't do anything about interactive rebases where, e.g., r1.files == r3.files, r2.files == r5.files, but r4 is new.  I don't think these more complex scenarios can be handled adequately given the purposely simple semantics of Reviewable's review marks: a review mark indicates this and all previous revisions were reviewed, rather than applying to the changes in a single revision pair.  But perhaps that's an OK 80/20 trade-off.

Thoughts?

**Comment by feldgendler** [comment] 2019-03-20 12:10
There are two most common cases that I think should be handled seamlessly:

1. The PR is rebased, and the entire chain of commits is reproduced faithfully off the new base, one by one.
2. The PR is rebased, and the entire chain of commits is squashed into a single commit off the new base.

Anything else, like interactive rebases, conflict-resolving rebases etc is fair game, but in those cases, the diffs probably won't be empty anyway.

**Comment by pkaminski** [comment] 2019-03-20 18:46
I don't think there's a way to address the squashing scenario unfortunately.  The file shas will be different, `git` doesn't leave any metadata behind to know that's what happened, and the server doesn't load source code by design so it can't run the diff.

**Comment by feldgendler** [comment] 2019-03-20 20:31
> The file shas will be different

Why? I'd think they'll be exactly the same.

**Comment by cgiroux86** [comment] 2021-03-15 15:23
The fix for this is now live and appears to be stable. Please give it a whirl and let us know if you experience anything abnormal.

**Closed by cgiroux86** 2021-03-15 15:23 UTC
Labels: bug
