### ISSUE TITLE
Dismissing someone from comments is getting reverted

### ISSUE THREAD

**Issue by kballard** [Reviewable/Reviewable#331] opened 2016-06-02 23:35 UTC
I'm working through a review right now, and I've dismissed a few people from some discussions (since they're no longer reviewing it) in order to resolve those discussions. Some of those discussions somehow reverted that change so the person is still marked as discussing. The first time this happened 2 seconds after I dismissed the person, the second it happened something like 30 seconds after. In both cases when it happened Reviewable automatically scrolled up to make the comment visible again. The second time it happened, it happened to 3 comments simultaneously. The first one actually had 2 people I dismissed, and the first dismissal seems to have stuck but the second didn't (it's the same person in all 3 comments that got reverted).

At the time this happened, there was no connection indicator in the lower right.

**Comment by kballard** [comment] 2016-06-02 23:36
And now when I click on the person on that first comment, the disposition overlay is actually hidden beneath the following comment:

![screen shot 2016-06-02 at 4 35 46 pm](https://cloud.githubusercontent.com/assets/714/15764503/1c6b0cc6-28e0-11e6-9203-fad6454eeaa1.png)

**Comment by pkaminski** [comment] 2016-06-03 01:05
What status did the reverted person go back to?  Were they by any chance posting any comments at the time, or acknowledging?  After being dismissed, a user can get back into the discussion by taking most any action on it.

As for the dropdown disappearing under the following comment, I'll fix it.  It's the never-ending game of `z-index` ordering...
![291945e1b9136dd27aa6ba9f00420fce](https://cloud.githubusercontent.com/assets/1646896/15765689/9fa2cc76-2905-11e6-8115-fe755ec47926.gif)

**Comment by kballard** [comment] 2016-06-03 03:38
They were not interacting with the review at all. Neither person who had previously interacted with it had looked at it in several days (which is why I was dismissing them).

Also, that GIF is amazing.

**Comment by pkaminski** [comment] 2016-06-04 00:24
I'm stuck on both issues.  I can't reproduce the `z-index` problem at all.  It looks like you've got two discussions attached to (or at least mapped to) the same line -- is there anything else special about the arrangement?  Can you reproduce the problem if you just create and send two comments on the same line?

As for the disappearing dismissals, the only mechanism I can think that would result in a "rollback" after a second or two is Firebase applying the changes locally, then reverting them when the server write fails.  However, if this write fails it should crash the client and send a report to Sentry, and I haven't seen anything along these lines.  I wonder if it might somehow be related to your issues with writes never completing and Reviewable forcing itself offline?  Anyway, I'll keep investigating, but if you gather any more clues please send them my way.

**Comment by kballard** [comment] 2016-06-06 22:37
I just filed 2 comments on the same line in a review today, and when revisiting the review, the z-ordering appears to be correct (the disposition dropdown appears over the subsequent comment).

**Comment by kballard** [comment] 2016-06-07 00:41
Similarly, I just looked at another review where a file was deleted, so all the comments on that file ended up squished together as if on one line, and the z-ordering still appeared to be correct.

**Comment by pkaminski** [comment] 2016-06-07 04:06
I'm starting to wonder if the issue is not structural (i.e., configuration of comments and the lines they're attached to) but rather one of timing.  The z-index is set dynamically when the menus drop down / wrap up so it's possible that some sequence of clicks will throw off the state.  However, despite some mad clicking on adjacent comments I haven't been able to cause it to misbehave so far.  The closest I can get is if a menu in the lower discussion is opened and I directly go to open a menu in the higher discussion, the latter menu will have the wrong z-ordering until the previous menu has finished collapsing.

(For the record, I'm not proud of the dynamic z-ordering system, but without it I actually had a conceptual z-ordering cycle in my design...)

BTW, did you observe any further dismissal bounces?

**Comment by kballard** [comment] 2016-06-07 04:35
I have not seen any further dismissal bounces. As for z-index, I wasn't doing any kind of crazy clicking when I saw it. I'll continue to keep an eye out, though, and see if I can't figure out anything else.

**Comment by pkaminski** [comment] 2016-07-17 09:57
Since we haven't seen a repro in >1 month I'm going to close this issue for now, but will definitely look into it if it recurs.

**Comment by ibrahima** [comment] 2017-07-11 08:45
I actually seem to always see dismissals get reverted every time a new revision is made, is that expected? I've just been dealing with it but I wasn't sure if that was related to this issue or not. It's a bit annoying when sometimes other people randomly comment on things that they're not actually officially reviewing, and then those threads never stay resolved :/

**Comment by pkaminski** [comment] 2017-07-11 16:01
Dismissals should only be overridden if the dismissed user somehow gets involved in the discussion again (replies, acknowledges, gets mentioned, etc.).  I just tried creating a discussion, dismissing the author, then pushing a new revision, and the author remained dismissed (and the discussion resolved), so there must be some other subtlety in your observed scenario.  Can you find a (hopefully pretty simple) example of this happening and provide details about the discussion, its participants, the target file and its revisions, etc?  Thanks!

**Comment by The-Compiler** [comment] 2017-12-06 09:29
I'm seeing a similar issue in https://reviewable.io/reviews/qutebrowser/qutebrowser/3040 - I dismiss the comments in `greasemonkey.py` from `@lahwaacz` and `@jgkamat`, the PR author (`@toofar`) pushes a new revision, and every time `@toofar` (the PR author) pushes a revision (or adds a comment? Not sure.) the dismissed discussions come back.

**Comment by pkaminski** [comment] 2017-12-06 22:12
Perhaps this is the break I needed to figure out the issue.  For the discussion that keep coming back, are the comments from the people you dismissed originating in Reviewable, or in GitHub/email?  (For the latter, there will be a small icon under their avatar in the comment.)  For example, is this one of the zombie discussions? https://reviewable.io/reviews/qutebrowser/qutebrowser/3040#-KvKMEE7YZAnCVwDv6o6-r7-310

**Comment by The-Compiler** [comment] 2017-12-06 22:22
Hmm, yeah! From a quick look, I do think they're all originating from GitHub.

**Comment by ibrahima** [comment] 2017-12-06 22:58
Definitely from Github in my case, because they're mostly being posted by a bot that posts Github comments for linter violations. (I've also seen it from real users because my team sometimes mixes using Reviewable and Github comments, but I think those are also all Github comments.)

**Comment by pkaminski** [comment] 2017-12-11 06:22
Turns out the GitHub comment syncing algorithm was a little over-eager to update comment dispositions, sometimes even when the comment was older than the current disposition.  Should be fixed now -- sorry about that!

**Closed by pkaminski** 2017-12-11 06:22 UTC
Labels: blocked, bug

**Comment by ibrahima** [comment] 2017-12-11 06:48
Awesome, thank you!
