### ISSUE TITLE
Feature Request: git show --color-moved equivalent

### ISSUE THREAD

**Issue by brendanwalters** [Reviewable/Reviewable#922] opened 2022-05-05 19:17 UTC
When a refactor moves large blocks of code unedited, I tend to review that in a terminal using `git show --color-moved $commit` instead of in Reviewable, because that lets me differentiate between moved blocks and edited blocks. It would be great if Reviewable could use git's moved-block detection and highlight those lines differently.

**Comment by pkaminski** [comment] 2022-05-05 19:18
Wholeheartedly agreed -- in fact, it's the oldest issue still open!  Closing as duplicate of #5.

**Closed by pkaminski** 2022-05-05 19:18 UTC
Labels: duplicate

**Comment by brendanwalters** [comment] 2022-05-05 19:29
Ah my bad, I searched for and didn't find anything with keyword "--color-moved". Thanks for the quick response!
