### ISSUE TITLE
High CPU usage in Edge after page should've settled down

### ISSUE THREAD

**Issue by adamncasey** [Reviewable/Reviewable#237] opened 2016-01-21 12:16 UTC
Hi there,

I hadn't used Reviewable before, but I noticed that when loading this review: https://reviewable.io/reviews/servo/servo/9385#-

CPU usage on Microsoft Edge spiked and seemingly never really recovered. The page was slow to interact with most of the time on my machine.

Potentially another problem, but still performance related: Whilst looking into the problem I hit my anonymous GitHub API limits, so no data was displayed, but the high CPU problem remained. Even after leaving the "You'ved reached your anonymous limit, sign in to continue" tab open for a few minutes, it still used ~30% CPU continuously. CPU Usage in Firefox for this error page seemed to also be around 30%.

Intel i5-4210U 1.7-2.4GHz. 8GB RAM. Windows 10.

I thought you might want to look into this. Let me know if I can provide any more information

**Comment by pbalcer** [comment] 2016-01-21 14:36
Can confirm. Reviewing moderately large (~4k modifications) pull requests feels very unresponsive. Even something as simple as text input has quite a large lag.

Tested using both firefox and chrome (versions from current ubuntu 14.04).

**Comment by pkaminski** [comment] 2016-01-21 21:53
Reproduced in Edge.  Running a quick profile indicates that 95% of CPU is spent on style and layout computation.  Since nothing similar happens in other mainstream browsers I'm inclined to guess that the issue is in Edge, not Reviewable.  There may be a workaround but since Edge + IE account for <1% of Reviewable users, it's not a high priority to look for one -- sorry.

I couldn't reproduce the 30% CPU usage in Firefox, even after running out of anonymous quota.  Note that if there's an animated butterfly on screen the animation will eat up some CPU power, but it shouldn't be 30% and the butterflies will disappear as you use the app.

@pbalcer I intend to do another pass over performance soon, and also allow users to force single-file mode to reduce the load further on low-spec machines.  I'd like to keep this issue specific to anomalous high CPU issues -- could you open up a separate one for general performance concerns and report your machine's specs?  Thanks.

**Comment by pkaminski** [comment] 2016-03-06 08:47
I looked into this some more and I think it's likely the same as issue #251.  Closing as duplicate, will explain further over there.

**Closed by pkaminski** 2016-03-06 08:47 UTC
Labels: bug, duplicate, low priority
