### ISSUE TITLE
@mentions not reflected in dashboard

### ISSUE THREAD

**Issue by macmason** [Reviewable/Reviewable#754] opened 2020-06-26 01:34 UTC
We're seeing @-mentioning someone fail to cause a change on the dashoard. (I expected it to get to "involving", at least). We get the e-mail, but no dashboard changes.

Thinking this was #636 we tried doing the mention in a comment within a file; no luck. 

Are we misconfigured somehow?

Normal github, normal reviewable; not enterprise anything. 

Thanks!

@danielgordon10 @katarinabouma

**Comment by dhbradshaw** [comment] 2020-06-26 17:10
So is this something that's worked for you in the past but is now failing?

**Comment by macmason** [comment] 2020-06-26 17:36
We believe so, yes.

**Comment by pkaminski** [comment] 2020-06-26 19:01
This GitHub bug is indeed extremely annoying and I don't think it's possible to work around it at present.  Here's what's happening:

GitHub has a bug where @-mentions in the top comment of a review aren't indexed properly.  Mentions in review line comments are indexed, as are those in PR/issue (non-review) comments of all kinds.  Reviewable used to post its comments as a batched issue comment but switched to a review comment so it could tie into GitHub's PR approval system.  Due to a deficient GitHub API (#437) we still need to batch up all Reviewable comments into one top-level (unindexed) GitHub comment, rather than keeping them as (indexed) line comments.

I think the current arrangement is the least bad trade-off given the constraints but I agree it's not great.  We may be able to strike a slightly different balance soon -- see my last comment in #437.

In the meantime, closing this as a duplicate of #636.

**Closed by pkaminski** 2020-06-26 19:01 UTC
Labels: duplicate
