### ISSUE TITLE
Can’t Re-Open Comment

### ISSUE THREAD

**Issue by jGleitz** [Reviewable/Reviewable#243] opened 2016-01-25 09:43 UTC
If I’ve opened a comment on a line, decided not to write a comment there and thus closed it again and try to open the comment again, Reviewable fails to open it. Reloading the page solves the issue.

Video: http://owncloud.joshuagleitze.de/index.php/s/OAFBarioMiSoNS7

**Comment by pkaminski** [comment] 2016-01-25 18:57
Woah, that's both really bad and really weird -- and I can't reproduce it.  Could you visit https://reviewable.io/reviews/pkaminski/sample/51#-, create an empty comment (on any line) and close it by clicking outside?  Perhaps I'll be able to get a clue by looking at your state for that review in the datastore.  (Try to do just the one comment creation/deletion to avoid confounding factors... thanks!)

**Comment by jGleitz** [comment] 2016-01-25 19:10
>  create an empty comment (on any line) and close it by clicking outside?

I did (on line `8`).

Please note that “Click on line” -> “Click outside” -> “Click on the same line” does **not** produce this behaviour for me! However, clicking three times on the same line (regardless of what was clicked in between) does reliably produce it.

**Comment by pkaminski** [comment] 2016-01-25 19:31
Ah, I didn't get that from your video -- I can reproduce now.  Thanks!

**Comment by pkaminski** [comment] 2016-01-26 00:41
That was a fun bug.  Fixed.

**Closed by pkaminski** 2016-01-26 00:41 UTC
Labels: bug
