### ISSUE TITLE
Undefined changes in a bunch of files

### ISSUE THREAD

**Issue by jdm** [Reviewable/Reviewable#89] opened 2015-05-01 21:44 UTC
See https://reviewable.io/reviews/servo/servo/5884 - constellation_msg.rs, msg/lib.rs, script/script_task.rs, servo/Cargo.lock, webdriver_server/Cargo.toml, and webdriver_server/lib.rs all show "undefined" instead of actual diffs.

**Comment by pkaminski** [comment] 2015-05-01 21:47
This sounds serious, but I can't reproduce it and my exception capture system doesn't have any related errors.  Could you please send a screenshot and check the console for any errors/warnings?  Are you currently signed in or using Reviewable anonymously?  Does it persist if you reload the page?

**Comment by jdm** [comment] 2015-05-01 22:03
I'm signed in, and I remember seeing it occur a couple days ago as well. I discovered that I could avoid it if I used the selector that's adjacent to each filename and explicitly selected the base revision, so I completed the review by adjusting the selector for each file with the problem.

**Comment by pkaminski** [comment] 2015-05-01 22:19
I figured it out: your diffs were being throttled (surprisingly, as that's usually only triggered for large reviews of 50+ files) and the throttling warning message was broken.  Fixed now -- sorry!

**Closed by pkaminski** 2015-05-01 22:19 UTC
Labels: bug

**Comment by jdm** [comment] 2015-05-01 22:28
Thanks!
