### ISSUE TITLE
Fastly error

### ISSUE THREAD

**Issue by erikwright** [Reviewable/Reviewable#381] opened 2016-08-08 18:18 UTC
My colleague reports the following:

`Fastly error: unknown domain: reviewable.io. Please check that this domain has been added to a service.` while trying to access https://reviewable.io/reviews/shopify/starscream/12216

**Comment by pkaminski** [comment] 2016-08-08 18:37
Looks like Reviewable's CDN was down for ~23 minutes, for causes unknown, after 297 days of uninterrupted uptime.  :cry:  It's back up now.  I'll try to find out the root cause, but given that the issue crosses multiple corporate entities I'm not holding my breath...

**Comment by erikwright** [comment] 2016-08-08 18:41
No worries, just reporting it to you for your interest. No follow-up
required on our end.

**Comment by pkaminski** [comment] 2016-08-08 18:45
Looks like it's still broken for some people.  Will point folks here and update as I get more info.

**Comment by pkaminski** [comment] 2016-08-08 19:49
Things appear to be working fine again all around the world so closing the issue.  Still looking into the root cause but I'm betting on some temporary misconfiguration either at Firebase or at Fastly.

**Closed by pkaminski** 2016-08-08 19:49 UTC
Labels: bug
